#ifndef GUARD_METATILE_BEHAVIORS_DUPLICATE_NAME_H
#define GUARD_METATILE_BEHAVIORS_DUPLICATE_NAME_H

#define MB_NORMAL 0x00
#define MB_SECRET_BASE_WALL 0x01
#define MB_TALL_GRASS 0x02
#define MB_LONG_GRASS 0x03
#define MB_DEEP_WATER 0x12

// Duplicate name with different value
#define MB_TALL_GRASS 0x05

#endif // GUARD_METATILE_BEHAVIORS_DUPLICATE_NAME_H
