#include "porytiles2/infra/config/default_provider.hpp"

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate via:
 *
 *   uv run Scripts/generate_config.py
 */

namespace {

const std::string source_info = "default value";

}

namespace porytiles2 {

std::string DefaultProvider::name() const
{
    return "DefaultProvider";
}

LayerValue<std::size_t> DefaultProvider::num_tiles_in_primary(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(512, "Number Of Tiles In Primary", source_info);
}

LayerValue<std::size_t>
DefaultProvider::num_tiles_total([[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(1024, "Number Of Tiles Total", source_info);
}

LayerValue<std::size_t> DefaultProvider::num_metatiles_in_primary(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(512, "Number Of Metatiles In Primary", source_info);
}

LayerValue<std::size_t> DefaultProvider::num_metatiles_total(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(1024, "Number Of Metatiles Total", source_info);
}

LayerValue<std::size_t> DefaultProvider::num_pals_in_primary(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(6, "Number Of Palettes In Primary", source_info);
}

LayerValue<std::size_t>
DefaultProvider::num_pals_total([[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(13, "Number Of Palettes Total", source_info);
}

LayerValue<std::size_t> DefaultProvider::max_map_data_size(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(10240, "Max Map Data Size", source_info);
}

LayerValue<std::size_t> DefaultProvider::num_tiles_per_metatile(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(8, "Number Of Tiles Per Metatile", source_info);
}

LayerValue<Rgba32> DefaultProvider::extrinsic_transparency(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<Rgba32>::valid(rgba_magenta, "Extrinsic Transparency", source_info);
}

LayerValue<ArtifactEditMode>
DefaultProvider::tiles_edit_mode([[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<ArtifactEditMode>::valid(ArtifactEditMode::optimize, "Tiles Edit Mode", source_info);
}

LayerValue<ArtifactEditMode>
DefaultProvider::pals_edit_mode([[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<ArtifactEditMode>::valid(ArtifactEditMode::optimize, "Palettes Edit Mode", source_info);
}

LayerValue<bool> DefaultProvider::pal_hints_enabled(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<bool>::valid(true, "Palette Hints Enabled", source_info);
}

LayerValue<std::vector<PaletteHint>>
DefaultProvider::pal_hints([[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::vector<PaletteHint>>::valid(std::vector<PaletteHint>{}, "Palette Hints", source_info);
}

LayerValue<TilesPalMode>
DefaultProvider::tiles_pal_mode([[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<TilesPalMode>::valid(TilesPalMode::true_color, "Tiles Palette Mode", source_info);
}

LayerValue<AnimPalResolutionStrategy> DefaultProvider::global_anim_pal_resolution_strategy(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<AnimPalResolutionStrategy>::valid(
        AnimPalResolutionStrategy::scan_local_metatiles, "Global Animation Palette Resolution Strategy", source_info);
}

LayerValue<AnimKeyFrameResolutionStrategy> DefaultProvider::global_anim_key_frame_resolution_strategy(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<AnimKeyFrameResolutionStrategy>::valid(
        AnimKeyFrameResolutionStrategy::error, "Global Animation Key Frame Resolution Strategy", source_info);
}

LayerValue<AnimMultiPalSubtileResolutionStrategy> DefaultProvider::global_anim_multi_pal_subtile_resolution_strategy(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<AnimMultiPalSubtileResolutionStrategy>::valid(
        AnimMultiPalSubtileResolutionStrategy::error,
        "Global Animation Multi-Pal Subtile Resolution Strategy",
        source_info);
}

LayerValue<FrameLinking> DefaultProvider::global_frame_linking(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<FrameLinking>::valid(FrameLinking::automatic, "Global Frame Linking", source_info);
}

LayerValue<PerAnimOverrides> DefaultProvider::per_anim_overrides(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<PerAnimOverrides>::valid(PerAnimOverrides{}, "Per-Animation Overrides", source_info);
}

LayerValue<bool> DefaultProvider::verify_checksums(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<bool>::valid(true, "Verify Checksums", source_info);
}

LayerValue<std::string> DefaultProvider::tileset_paths_primary_src(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::string>::valid("data/tilesets/primary", "Tileset Paths Primary Source", source_info);
}

LayerValue<std::string> DefaultProvider::tileset_paths_primary_bin(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::string>::valid("data/tilesets/primary", "Tileset Paths Primary Bin", source_info);
}

LayerValue<std::string> DefaultProvider::tileset_paths_secondary_src(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::string>::valid("data/tilesets/secondary", "Tileset Paths Secondary Source", source_info);
}

LayerValue<std::string> DefaultProvider::tileset_paths_secondary_bin(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::string>::valid("data/tilesets/secondary", "Tileset Paths Secondary Bin", source_info);
}

LayerValue<bool> DefaultProvider::tileset_animations_wire_anim_code(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<bool>::valid(true, "Tileset Animations Wire Anim Code", source_info);
}

} // namespace porytiles2