#include "porytiles2/infra/config/lazy_layered_config.hpp"

#include <any>
#include <functional>
#include <ranges>
#include <stdexcept>
#include <string>

#include "porytiles2/domain/config/tiles_pal_mode.hpp"
#include "porytiles2/utilities/panic/panic.hpp"
#include "porytiles2/utilities/source_locations.hpp"
#include "porytiles2/utilities/string_utils.hpp"
#include "porytiles2/xcut/config/config_value.hpp"

namespace porytiles2 {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate using
 * Scripts/generate_config.py.
 */

template <typename T>
ChainableResult<ConfigValue<T>> LazyLayeredConfig::resolve_config_value(
    const std::string &cache_key, std::function<LayerValue<T>(const ConfigProvider &)> provider_call) const
{
    /*
     * WARNING! HACK ALERT! WARNING!
     * DO NOT DELETE THESE USING STATEMENTS.
     *
     * We need to declare these here so that the to_string call below can resolve to either the std:: version or one of
     * our custom versions automagically. Both are needed because:
     * - std::to_string handles numeric types (size_t, bool, etc.)
     * - porytiles2::to_string handles custom types (Rgba32, std::string, std::vector<T>, etc.)
     */
    using porytiles2::to_string;
    using std::to_string;

    // Check if already cached
    if (cache_.contains(cache_key)) {
        T cached_value{};
        try {
            cached_value = std::any_cast<T>(cache_.at(cache_key));
        }
        catch (const std::bad_any_cast &) {
            panic(format_->format(
                "bad_any_cast for cache key '{}': cached type does not match requested type", cache_key));
        }
        std::string source = source_.at(cache_key);
        std::vector<std::string> source_details = source_details_.at(cache_key);
        return ConfigValue<T>{cached_value, cache_key, source, source_details};
    }

    // Search through providers in priority order
    for (const auto &provider : providers_) {
        LayerValue<T> layer_value = provider_call(*provider);

        // Check if provider found an invalid value - stop immediately and return error
        if (layer_value.state == ValidationState::invalid) {
            const auto source_info = format_->format("{}", layer_value.source_info);
            std::vector<std::string> error_lines;
            error_lines.push_back(format_->format(
                "invalid value for '{}' from config source '{}':",
                FormatParam{cache_key, Style::bold},
                FormatParam{source_info, Style::bold}));
            error_lines.emplace_back();
            error_lines.push_back("Details:");
            error_lines.push_back(format_->format("{}", layer_value.error_message));

            if (!layer_value.source_details.empty()) {
                error_lines.emplace_back(""); // Blank line separator
                for (const auto &detail : layer_value.source_details) {
                    error_lines.push_back(detail);
                }
            }

            return FormattableError{error_lines};
        }

        // Check if provider has a valid value
        if (layer_value.state == ValidationState::valid) {
            T resolved_value = layer_value.value.value();
            cache_[cache_key] = resolved_value;
            cache_value_strings_[cache_key] = to_string(resolved_value);
            std::string source = format_->format("{}", layer_value.source_info);
            source_[cache_key] = source;
            source_details_[cache_key] = layer_value.source_details;
            return ConfigValue<T>{resolved_value, cache_key, source, layer_value.source_details};
        }

        // Otherwise, state is not_provided - continue to next provider
        if (layer_value.state == ValidationState::not_provided) {
            continue;
        }

        panic("hit unexpected ValidationState");
    }

    // No value found in any layer - this is a programmer error
    panic(format_->format("no value found for '{}' in any config layer", cache_key));
}

template <typename T>
std::vector<ProvenanceChainLink<T>>
LazyLayeredConfig::collect_provenance_chain(std::function<LayerValue<T>(const ConfigProvider &)> provider_call) const
{
    std::vector<ProvenanceChainLink<T>> chain;
    chain.reserve(providers_.size());

    for (const auto &provider : providers_) {
        LayerValue<T> layer_value = provider_call(*provider);
        chain.push_back(ProvenanceChainLink<T>{provider->name(), std::move(layer_value)});
    }

    return chain;
}

ChainableResult<ConfigValue<std::size_t>>
LazyLayeredConfig::num_tiles_in_primary_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<std::size_t>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.num_tiles_in_primary(type, scope); });
}

ChainableResult<ConfigValue<std::size_t>>
LazyLayeredConfig::num_tiles_total_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<std::size_t>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.num_tiles_total(type, scope); });
}

ChainableResult<ConfigValue<std::size_t>>
LazyLayeredConfig::num_metatiles_in_primary_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<std::size_t>(key, [&type, &scope](const ConfigProvider &provider) {
        return provider.num_metatiles_in_primary(type, scope);
    });
}

ChainableResult<ConfigValue<std::size_t>>
LazyLayeredConfig::num_metatiles_total_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<std::size_t>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.num_metatiles_total(type, scope); });
}

ChainableResult<ConfigValue<std::size_t>>
LazyLayeredConfig::num_pals_in_primary_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<std::size_t>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.num_pals_in_primary(type, scope); });
}

ChainableResult<ConfigValue<std::size_t>>
LazyLayeredConfig::num_pals_total_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<std::size_t>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.num_pals_total(type, scope); });
}

ChainableResult<ConfigValue<std::size_t>>
LazyLayeredConfig::max_map_data_size_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<std::size_t>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.max_map_data_size(type, scope); });
}

ChainableResult<ConfigValue<std::size_t>>
LazyLayeredConfig::num_tiles_per_metatile_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<std::size_t>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.num_tiles_per_metatile(type, scope); });
}

ChainableResult<ConfigValue<Rgba32>>
LazyLayeredConfig::extrinsic_transparency_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<Rgba32>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.extrinsic_transparency(type, scope); });
}

ChainableResult<ConfigValue<ArtifactEditMode>>
LazyLayeredConfig::tiles_edit_mode_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<ArtifactEditMode>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.tiles_edit_mode(type, scope); });
}

ChainableResult<ConfigValue<ArtifactEditMode>>
LazyLayeredConfig::pals_edit_mode_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<ArtifactEditMode>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.pals_edit_mode(type, scope); });
}

ChainableResult<ConfigValue<bool>>
LazyLayeredConfig::pal_hints_enabled_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<bool>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.pal_hints_enabled(type, scope); });
}

ChainableResult<ConfigValue<std::vector<PaletteHint>>>
LazyLayeredConfig::pal_hints_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<std::vector<PaletteHint>>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.pal_hints(type, scope); });
}

ChainableResult<ConfigValue<TilesPalMode>>
LazyLayeredConfig::tiles_pal_mode_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<TilesPalMode>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.tiles_pal_mode(type, scope); });
}

ChainableResult<ConfigValue<AnimPalResolutionStrategy>>
LazyLayeredConfig::anim_pal_resolution_strategy_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<AnimPalResolutionStrategy>(key, [&type, &scope](const ConfigProvider &provider) {
        return provider.anim_pal_resolution_strategy(type, scope);
    });
}

ChainableResult<ConfigValue<AnimKeyFrameResolutionStrategy>>
LazyLayeredConfig::anim_key_frame_resolution_strategy_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<AnimKeyFrameResolutionStrategy>(key, [&type, &scope](const ConfigProvider &provider) {
        return provider.anim_key_frame_resolution_strategy(type, scope);
    });
}

ChainableResult<ConfigValue<bool>>
LazyLayeredConfig::verify_checksums_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<bool>(
        key, [&type, &scope](const ConfigProvider &provider) { return provider.verify_checksums(type, scope); });
}

ChainableResult<ConfigValue<std::string>>
LazyLayeredConfig::tileset_paths_primary_src_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<std::string>(key, [&type, &scope](const ConfigProvider &provider) {
        return provider.tileset_paths_primary_src(type, scope);
    });
}

ChainableResult<ConfigValue<std::string>>
LazyLayeredConfig::tileset_paths_primary_bin_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<std::string>(key, [&type, &scope](const ConfigProvider &provider) {
        return provider.tileset_paths_primary_bin(type, scope);
    });
}

ChainableResult<ConfigValue<std::string>>
LazyLayeredConfig::tileset_paths_secondary_src_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<std::string>(key, [&type, &scope](const ConfigProvider &provider) {
        return provider.tileset_paths_secondary_src(type, scope);
    });
}

ChainableResult<ConfigValue<std::string>>
LazyLayeredConfig::tileset_paths_secondary_bin_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<std::string>(key, [&type, &scope](const ConfigProvider &provider) {
        return provider.tileset_paths_secondary_bin(type, scope);
    });
}

ChainableResult<ConfigValue<bool>>
LazyLayeredConfig::tileset_animations_wire_anim_code_raw(ConfigScopeType type, const std::string &scope) const
{
    const auto name = extract_function_name();
    // Strip the _raw suffix from the function name for cache key
    const auto base_name = name.substr(0, name.size() - 4);
    const auto key = to_string(type) + ":" + scope + ":" + base_name;
    return resolve_config_value<bool>(key, [&type, &scope](const ConfigProvider &provider) {
        return provider.tileset_animations_wire_anim_code(type, scope);
    });
}

std::vector<ProvenanceChainLink<std::size_t>>
LazyLayeredConfig::num_tiles_in_primary_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<std::size_t>(
        [&type, &scope](const ConfigProvider &provider) { return provider.num_tiles_in_primary(type, scope); });
}

std::vector<ProvenanceChainLink<std::size_t>>
LazyLayeredConfig::num_tiles_total_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<std::size_t>(
        [&type, &scope](const ConfigProvider &provider) { return provider.num_tiles_total(type, scope); });
}

std::vector<ProvenanceChainLink<std::size_t>>
LazyLayeredConfig::num_metatiles_in_primary_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<std::size_t>(
        [&type, &scope](const ConfigProvider &provider) { return provider.num_metatiles_in_primary(type, scope); });
}

std::vector<ProvenanceChainLink<std::size_t>>
LazyLayeredConfig::num_metatiles_total_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<std::size_t>(
        [&type, &scope](const ConfigProvider &provider) { return provider.num_metatiles_total(type, scope); });
}

std::vector<ProvenanceChainLink<std::size_t>>
LazyLayeredConfig::num_pals_in_primary_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<std::size_t>(
        [&type, &scope](const ConfigProvider &provider) { return provider.num_pals_in_primary(type, scope); });
}

std::vector<ProvenanceChainLink<std::size_t>>
LazyLayeredConfig::num_pals_total_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<std::size_t>(
        [&type, &scope](const ConfigProvider &provider) { return provider.num_pals_total(type, scope); });
}

std::vector<ProvenanceChainLink<std::size_t>>
LazyLayeredConfig::max_map_data_size_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<std::size_t>(
        [&type, &scope](const ConfigProvider &provider) { return provider.max_map_data_size(type, scope); });
}

std::vector<ProvenanceChainLink<std::size_t>>
LazyLayeredConfig::num_tiles_per_metatile_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<std::size_t>(
        [&type, &scope](const ConfigProvider &provider) { return provider.num_tiles_per_metatile(type, scope); });
}

std::vector<ProvenanceChainLink<Rgba32>>
LazyLayeredConfig::extrinsic_transparency_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<Rgba32>(
        [&type, &scope](const ConfigProvider &provider) { return provider.extrinsic_transparency(type, scope); });
}

std::vector<ProvenanceChainLink<ArtifactEditMode>>
LazyLayeredConfig::tiles_edit_mode_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<ArtifactEditMode>(
        [&type, &scope](const ConfigProvider &provider) { return provider.tiles_edit_mode(type, scope); });
}

std::vector<ProvenanceChainLink<ArtifactEditMode>>
LazyLayeredConfig::pals_edit_mode_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<ArtifactEditMode>(
        [&type, &scope](const ConfigProvider &provider) { return provider.pals_edit_mode(type, scope); });
}

std::vector<ProvenanceChainLink<bool>>
LazyLayeredConfig::pal_hints_enabled_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<bool>(
        [&type, &scope](const ConfigProvider &provider) { return provider.pal_hints_enabled(type, scope); });
}

std::vector<ProvenanceChainLink<std::vector<PaletteHint>>>
LazyLayeredConfig::pal_hints_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<std::vector<PaletteHint>>(
        [&type, &scope](const ConfigProvider &provider) { return provider.pal_hints(type, scope); });
}

std::vector<ProvenanceChainLink<TilesPalMode>>
LazyLayeredConfig::tiles_pal_mode_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<TilesPalMode>(
        [&type, &scope](const ConfigProvider &provider) { return provider.tiles_pal_mode(type, scope); });
}

std::vector<ProvenanceChainLink<AnimPalResolutionStrategy>>
LazyLayeredConfig::anim_pal_resolution_strategy_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<AnimPalResolutionStrategy>(
        [&type, &scope](const ConfigProvider &provider) { return provider.anim_pal_resolution_strategy(type, scope); });
}

std::vector<ProvenanceChainLink<AnimKeyFrameResolutionStrategy>>
LazyLayeredConfig::anim_key_frame_resolution_strategy_provenance_chain(
    ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<AnimKeyFrameResolutionStrategy>([&type, &scope](const ConfigProvider &provider) {
        return provider.anim_key_frame_resolution_strategy(type, scope);
    });
}

std::vector<ProvenanceChainLink<bool>>
LazyLayeredConfig::verify_checksums_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<bool>(
        [&type, &scope](const ConfigProvider &provider) { return provider.verify_checksums(type, scope); });
}

std::vector<ProvenanceChainLink<std::string>>
LazyLayeredConfig::tileset_paths_primary_src_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<std::string>(
        [&type, &scope](const ConfigProvider &provider) { return provider.tileset_paths_primary_src(type, scope); });
}

std::vector<ProvenanceChainLink<std::string>>
LazyLayeredConfig::tileset_paths_primary_bin_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<std::string>(
        [&type, &scope](const ConfigProvider &provider) { return provider.tileset_paths_primary_bin(type, scope); });
}

std::vector<ProvenanceChainLink<std::string>>
LazyLayeredConfig::tileset_paths_secondary_src_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<std::string>(
        [&type, &scope](const ConfigProvider &provider) { return provider.tileset_paths_secondary_src(type, scope); });
}

std::vector<ProvenanceChainLink<std::string>>
LazyLayeredConfig::tileset_paths_secondary_bin_provenance_chain(ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<std::string>(
        [&type, &scope](const ConfigProvider &provider) { return provider.tileset_paths_secondary_bin(type, scope); });
}

std::vector<ProvenanceChainLink<bool>> LazyLayeredConfig::tileset_animations_wire_anim_code_provenance_chain(
    ConfigScopeType type, const std::string &scope) const
{
    return collect_provenance_chain<bool>([&type, &scope](const ConfigProvider &provider) {
        return provider.tileset_animations_wire_anim_code(type, scope);
    });
}

} // namespace porytiles2