name: Run Test Suite
description: Runs the Porytiles version printout and test suite
runs:
  using: composite
  steps:
    - name: Run version and test suite
      shell: bash
      run: |
        ./build/Legacy/tools/driver/porytiles-legacy --version
        ./build/Legacy/tests/LegacyTests
        ./build/Porytiles/tools/driver/porytiles --version
        ./build/Porytiles/tests/PorytilesUnitTests
        ./build/Porytiles/tests/PorytilesIntegrationTests