name: Run Test Suite
description: Runs the Porytiles version printout and test suite
runs:
  using: composite
  steps:
    - name: Run version and test suite
      shell: bash
      run: |
        ./build/Porytiles/tools/legacy_driver/porytiles --version
        ./build/Porytiles/doctests/PorytilesDocTests
        ./build/Porytiles/tools/driver/porytiles2 --version
        ./build/Porytiles/tests/PorytilesGoogleTests