name: Run Test Suite
description: Runs the Porytiles version printout and test suite
runs:
  using: composite
  steps:
    - name: Run version and test suite
      shell: bash
      run: |
        ./build/Porytiles1/tools/driver/porytiles --version
        ./build/Porytiles1/tests/Porytiles1Tests
        ./build/Porytiles2/tools/driver/porytiles2 --version
        ./build/Porytiles2/tests/Porytiles2Tests