#include "porytiles/infra/config/default_provider.hpp"

// NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
// To add new config values or make other changes, edit config_schema.yaml and regenerate via:
//
//   uv run scripts/generate_config.py

namespace {

const std::string source_info = "default value";

}

namespace porytiles {

std::string DefaultProvider::name() const
{
    return "DefaultProvider";
}

LayerValue<std::size_t> DefaultProvider::num_tiles_in_primary(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(512, "Number Of Tiles In Primary", source_info);
}

LayerValue<std::size_t>
DefaultProvider::num_tiles_total([[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(1024, "Number Of Tiles Total", source_info);
}

LayerValue<std::size_t> DefaultProvider::num_metatiles_in_primary(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(512, "Number Of Metatiles In Primary", source_info);
}

LayerValue<std::size_t> DefaultProvider::num_metatiles_total(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(1024, "Number Of Metatiles Total", source_info);
}

LayerValue<std::size_t> DefaultProvider::num_palettes_in_primary(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(6, "Number Of Palettes In Primary", source_info);
}

LayerValue<std::size_t> DefaultProvider::num_palettes_total(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(13, "Number Of Palettes Total", source_info);
}

LayerValue<std::size_t> DefaultProvider::max_map_data_size(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(10240, "Max Map Data Size", source_info);
}

LayerValue<std::size_t> DefaultProvider::num_tiles_per_metatile(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::size_t>::valid(8, "Number Of Tiles Per Metatile", source_info);
}

LayerValue<Rgba32> DefaultProvider::extrinsic_transparency(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<Rgba32>::valid(rgba_magenta, "Extrinsic Transparency", source_info);
}

LayerValue<bool> DefaultProvider::ignore_triple_layer_content(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<bool>::valid(false, "Ignore Triple Layer Content", source_info);
}

LayerValue<ArtifactEditMode>
DefaultProvider::tiles_edit_mode([[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<ArtifactEditMode>::valid(ArtifactEditMode::optimize, "Tiles Edit Mode", source_info);
}

LayerValue<ArtifactEditMode> DefaultProvider::palettes_edit_mode(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<ArtifactEditMode>::valid(ArtifactEditMode::optimize, "Palettes Edit Mode", source_info);
}

LayerValue<bool> DefaultProvider::palette_hints_enabled(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<bool>::valid(true, "Palette Hints Enabled", source_info);
}

LayerValue<std::vector<PaletteHint>>
DefaultProvider::palette_hints([[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::vector<PaletteHint>>::valid(std::vector<PaletteHint>{}, "Palette Hints", source_info);
}

LayerValue<PackingStrategyType> DefaultProvider::packing_strategy(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<PackingStrategyType>::valid(PackingStrategyType::backtracking, "Packing Strategy", source_info);
}

LayerValue<PackingStrategyParams> DefaultProvider::packing_strategy_params(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<PackingStrategyParams>::valid(PackingStrategyParams{}, "Packing Strategy Params", source_info);
}

LayerValue<TileSharingPacking> DefaultProvider::tile_sharing_packing(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<TileSharingPacking>::valid(TileSharingPacking::off, "Tile Sharing Packing", source_info);
}

LayerValue<TileSharingAlignment> DefaultProvider::tile_sharing_alignment(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<TileSharingAlignment>::valid(TileSharingAlignment::off, "Tile Sharing Alignment", source_info);
}

LayerValue<TilesPaletteMode> DefaultProvider::tiles_palette_mode(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<TilesPaletteMode>::valid(TilesPaletteMode::true_color, "Tiles Palette Mode", source_info);
}

LayerValue<AnimPaletteResolutionStrategy> DefaultProvider::global_anim_palette_resolution_strategy(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<AnimPaletteResolutionStrategy>::valid(
        AnimPaletteResolutionStrategy::scan_local_metatiles,
        "Global Animation Palette Resolution Strategy",
        source_info);
}

LayerValue<AnimKeyFrameResolutionStrategy> DefaultProvider::global_anim_key_frame_resolution_strategy(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<AnimKeyFrameResolutionStrategy>::valid(
        AnimKeyFrameResolutionStrategy::error, "Global Animation Key Frame Resolution Strategy", source_info);
}

LayerValue<AnimMultiPaletteSubtileResolutionStrategy>
DefaultProvider::global_anim_multi_palette_subtile_resolution_strategy(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<AnimMultiPaletteSubtileResolutionStrategy>::valid(
        AnimMultiPaletteSubtileResolutionStrategy::error,
        "Global Animation Multi-Palette Subtile Resolution Strategy",
        source_info);
}

LayerValue<FrameLinking> DefaultProvider::global_frame_linking(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<FrameLinking>::valid(FrameLinking::automatic, "Global Frame Linking", source_info);
}

LayerValue<PerAnimOverrides> DefaultProvider::per_anim_overrides(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<PerAnimOverrides>::valid(PerAnimOverrides{}, "Per-Animation Overrides", source_info);
}

LayerValue<bool> DefaultProvider::cross_tileset_anim_linking(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<bool>::valid(true, "Cross-Tileset Animation Linking", source_info);
}

LayerValue<bool> DefaultProvider::verify_checksums(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<bool>::valid(true, "Verify Checksums", source_info);
}

LayerValue<PrimaryPairingMode> DefaultProvider::primary_pairing_mode(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<PrimaryPairingMode>::valid(PrimaryPairingMode::automatic, "Primary Pairing Mode", source_info);
}

LayerValue<std::vector<std::string>> DefaultProvider::primary_pairing_partners(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::vector<std::string>>::valid(
        std::vector<std::string>{}, "Primary Pairing Partners", source_info);
}

LayerValue<std::vector<std::string>> DefaultProvider::diagnostic_warnings_exclude(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::vector<std::string>>::valid(
        std::vector<std::string>{}, "Diagnostic Warnings Exclude", source_info);
}

LayerValue<std::vector<std::string>> DefaultProvider::diagnostic_warnings_include(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::vector<std::string>>::valid(
        std::vector<std::string>{}, "Diagnostic Warnings Include", source_info);
}

LayerValue<std::vector<std::string>> DefaultProvider::diagnostic_remarks_exclude(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::vector<std::string>>::valid(
        std::vector<std::string>{}, "Diagnostic Remarks Exclude", source_info);
}

LayerValue<std::vector<std::string>> DefaultProvider::diagnostic_remarks_include(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::vector<std::string>>::valid(
        std::vector<std::string>{}, "Diagnostic Remarks Include", source_info);
}

LayerValue<std::string> DefaultProvider::tileset_paths_primary_src(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::string>::valid("data/tilesets/primary", "Tileset Paths Primary Source", source_info);
}

LayerValue<std::string> DefaultProvider::tileset_paths_primary_bin(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::string>::valid("data/tilesets/primary", "Tileset Paths Primary Bin", source_info);
}

LayerValue<std::string> DefaultProvider::tileset_paths_secondary_src(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::string>::valid("data/tilesets/secondary", "Tileset Paths Secondary Source", source_info);
}

LayerValue<std::string> DefaultProvider::tileset_paths_secondary_bin(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::string>::valid("data/tilesets/secondary", "Tileset Paths Secondary Bin", source_info);
}

LayerValue<std::optional<std::size_t>> DefaultProvider::metatile_attribute_size(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::optional<std::size_t>>::valid(std::nullopt, "Metatile Attribute Size", source_info);
}

LayerValue<std::optional<std::size_t>> DefaultProvider::metatile_attribute_declaration_size(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<std::optional<std::size_t>>::valid(
        std::nullopt, "Metatile Attribute Declaration Size", source_info);
}

LayerValue<MetatileAttributeFieldDefinitions> DefaultProvider::metatile_attribute_fields(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<MetatileAttributeFieldDefinitions>::valid(
        MetatileAttributeFieldDefinitions{}, "Metatile Attribute Fields", source_info);
}

LayerValue<MetatileAttributeFieldOverrides> DefaultProvider::metatile_attribute_field_overrides(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<MetatileAttributeFieldOverrides>::valid(
        MetatileAttributeFieldOverrides{}, "Metatile Attribute Field Overrides", source_info);
}

LayerValue<RolePinDefinitions>
DefaultProvider::role_pins([[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<RolePinDefinitions>::valid(RolePinDefinitions{}, "Role Pins", source_info);
}

LayerValue<bool> DefaultProvider::tileset_animations_wire_anim_code(
    [[maybe_unused]] ConfigScopeType type, [[maybe_unused]] const std::string &scope) const
{
    return LayerValue<bool>::valid(true, "Tileset Animations Wire Anim Code", source_info);
}

} // namespace porytiles