#include "porytiles/infra/config/header_define_provider.hpp"

#include <filesystem>
#include <string>
#include <vector>

#include "./header_define_provider_impl.ipp"

namespace porytiles {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate via:
 *
 *   uv run scripts/generate_config.py
 */

std::string HeaderDefineProvider::name() const
{
    return "HeaderDefineProvider";
}

LayerValue<std::size_t>
HeaderDefineProvider::num_tiles_in_primary(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    const auto header_path = project_root_ / header_relative_path_;
    return search_header_define<std::size_t>(
        parser_driver_,
        format_,
        header_path,
        "NUM_TILES_IN_PRIMARY",
        parse_size_t,
        "NUM_TILES_IN_PRIMARY",
        "NUM_TILES_IN_PRIMARY");
}

LayerValue<std::size_t>
HeaderDefineProvider::num_tiles_total(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    const auto header_path = project_root_ / header_relative_path_;
    return search_header_define<std::size_t>(
        parser_driver_, format_, header_path, "NUM_TILES_TOTAL", parse_size_t, "NUM_TILES_TOTAL", "NUM_TILES_TOTAL");
}

LayerValue<std::size_t>
HeaderDefineProvider::num_metatiles_in_primary(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    const auto header_path = project_root_ / header_relative_path_;
    return search_header_define<std::size_t>(
        parser_driver_,
        format_,
        header_path,
        "NUM_METATILES_IN_PRIMARY",
        parse_size_t,
        "NUM_METATILES_IN_PRIMARY",
        "NUM_METATILES_IN_PRIMARY");
}

LayerValue<std::size_t>
HeaderDefineProvider::num_metatiles_total(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    const auto header_path = project_root_ / header_relative_path_;
    return search_header_define<std::size_t>(
        parser_driver_,
        format_,
        header_path,
        "NUM_METATILES_TOTAL",
        parse_size_t,
        "NUM_METATILES_TOTAL",
        "NUM_METATILES_TOTAL");
}

LayerValue<std::size_t>
HeaderDefineProvider::num_pals_in_primary(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    const auto header_path = project_root_ / header_relative_path_;
    return search_header_define<std::size_t>(
        parser_driver_,
        format_,
        header_path,
        "NUM_PALS_IN_PRIMARY",
        parse_size_t,
        "NUM_PALS_IN_PRIMARY",
        "NUM_PALS_IN_PRIMARY");
}

LayerValue<std::size_t>
HeaderDefineProvider::num_pals_total(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    const auto header_path = project_root_ / header_relative_path_;
    return search_header_define<std::size_t>(
        parser_driver_, format_, header_path, "NUM_PALS_TOTAL", parse_size_t, "NUM_PALS_TOTAL", "NUM_PALS_TOTAL");
}

LayerValue<std::size_t>
HeaderDefineProvider::max_map_data_size(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    const auto header_path = project_root_ / header_relative_path_;
    return search_header_define<std::size_t>(
        parser_driver_,
        format_,
        header_path,
        "MAX_MAP_DATA_SIZE",
        parse_size_t,
        "MAX_MAP_DATA_SIZE",
        "MAX_MAP_DATA_SIZE");
}

LayerValue<std::size_t>
HeaderDefineProvider::num_tiles_per_metatile(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    const auto header_path = project_root_ / header_relative_path_;
    return search_header_define<std::size_t>(
        parser_driver_,
        format_,
        header_path,
        "NUM_TILES_PER_METATILE",
        parse_size_t,
        "NUM_TILES_PER_METATILE",
        "NUM_TILES_PER_METATILE");
}

LayerValue<Rgba32>
HeaderDefineProvider::extrinsic_transparency(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<Rgba32>::not_provided();
}

LayerValue<ArtifactEditMode>
HeaderDefineProvider::tiles_edit_mode(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<ArtifactEditMode>::not_provided();
}

LayerValue<ArtifactEditMode>
HeaderDefineProvider::pals_edit_mode(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<ArtifactEditMode>::not_provided();
}

LayerValue<bool> HeaderDefineProvider::pal_hints_enabled(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<bool>::not_provided();
}

LayerValue<std::vector<PaletteHint>>
HeaderDefineProvider::pal_hints(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<std::vector<PaletteHint>>::not_provided();
}

LayerValue<PackingStrategyType>
HeaderDefineProvider::packing_strategy(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<PackingStrategyType>::not_provided();
}

LayerValue<PackingStrategyParams>
HeaderDefineProvider::packing_strategy_params(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<PackingStrategyParams>::not_provided();
}

LayerValue<TileSharingPacking>
HeaderDefineProvider::tile_sharing_packing(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<TileSharingPacking>::not_provided();
}

LayerValue<TileSharingAlignment>
HeaderDefineProvider::tile_sharing_alignment(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<TileSharingAlignment>::not_provided();
}

LayerValue<TilesPalMode>
HeaderDefineProvider::tiles_pal_mode(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<TilesPalMode>::not_provided();
}

LayerValue<AnimPalResolutionStrategy>
HeaderDefineProvider::global_anim_pal_resolution_strategy(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<AnimPalResolutionStrategy>::not_provided();
}

LayerValue<AnimKeyFrameResolutionStrategy> HeaderDefineProvider::global_anim_key_frame_resolution_strategy(
    ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<AnimKeyFrameResolutionStrategy>::not_provided();
}

LayerValue<AnimMultiPalSubtileResolutionStrategy>
HeaderDefineProvider::global_anim_multi_pal_subtile_resolution_strategy(
    ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<AnimMultiPalSubtileResolutionStrategy>::not_provided();
}

LayerValue<FrameLinking>
HeaderDefineProvider::global_frame_linking(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<FrameLinking>::not_provided();
}

LayerValue<PerAnimOverrides>
HeaderDefineProvider::per_anim_overrides(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<PerAnimOverrides>::not_provided();
}

LayerValue<bool>
HeaderDefineProvider::cross_tileset_anim_linking(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<bool>::not_provided();
}

LayerValue<bool> HeaderDefineProvider::verify_checksums(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<bool>::not_provided();
}

LayerValue<PrimaryPairingMode>
HeaderDefineProvider::primary_pairing_mode(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<PrimaryPairingMode>::not_provided();
}

LayerValue<std::vector<std::string>>
HeaderDefineProvider::primary_pairing_partners(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<std::vector<std::string>>::not_provided();
}

LayerValue<std::vector<std::string>>
HeaderDefineProvider::diagnostic_warnings_exclude(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<std::vector<std::string>>::not_provided();
}

LayerValue<std::vector<std::string>>
HeaderDefineProvider::diagnostic_warnings_include(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<std::vector<std::string>>::not_provided();
}

LayerValue<std::vector<std::string>>
HeaderDefineProvider::diagnostic_remarks_exclude(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<std::vector<std::string>>::not_provided();
}

LayerValue<std::vector<std::string>>
HeaderDefineProvider::diagnostic_remarks_include(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<std::vector<std::string>>::not_provided();
}

LayerValue<std::string>
HeaderDefineProvider::tileset_paths_primary_src(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<std::string>::not_provided();
}

LayerValue<std::string>
HeaderDefineProvider::tileset_paths_primary_bin(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<std::string>::not_provided();
}

LayerValue<std::string>
HeaderDefineProvider::tileset_paths_secondary_src(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<std::string>::not_provided();
}

LayerValue<std::string>
HeaderDefineProvider::tileset_paths_secondary_bin(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<std::string>::not_provided();
}

LayerValue<std::size_t>
HeaderDefineProvider::metatile_attr_size(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<std::size_t>::not_provided();
}

LayerValue<MetatileAttrFieldSpecs>
HeaderDefineProvider::metatile_attr_fields(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<MetatileAttrFieldSpecs>::not_provided();
}

LayerValue<MetatileAttrFieldOverrides>
HeaderDefineProvider::metatile_attr_field_overrides(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<MetatileAttrFieldOverrides>::not_provided();
}

LayerValue<bool>
HeaderDefineProvider::tileset_animations_wire_anim_code(ConfigScopeType /*type*/, const std::string & /*scope*/) const
{
    // No header_define specified for this config value
    return LayerValue<bool>::not_provided();
}

} // namespace porytiles