#include "porytiles/infra/cli/cli_option_registration.hpp"

#include <string>

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate via:
 *
 *   uv run scripts/generate_config.py
 */

namespace porytiles {

void register_config_options(CLI::App &app, CliOptionStorage &storage)
{
    auto *config_group = app.add_option_group("Config Options", "Override configuration values");
    config_group->footer(""); // Clear inherited footer to prevent duplication in help output

    // Number Of Tiles In Primary (std::size_t, captured as string, parsed by CliOptionProvider)
    config_group->add_option(
        "--num-tiles-in-primary",
        storage.num_tiles_in_primary,
        "Number Of Tiles In Primary - The NUM_TILES_IN_PRIMARY setting from include/fieldmap.h.");

    // Number Of Tiles Total (std::size_t, captured as string, parsed by CliOptionProvider)
    config_group->add_option(
        "--num-tiles-total",
        storage.num_tiles_total,
        "Number Of Tiles Total - The NUM_TILES_TOTAL setting from include/fieldmap.h.");

    // Number Of Metatiles In Primary (std::size_t, captured as string, parsed by CliOptionProvider)
    config_group->add_option(
        "--num-metatiles-in-primary",
        storage.num_metatiles_in_primary,
        "Number Of Metatiles In Primary - The NUM_METATILES_IN_PRIMARY setting from include/fieldmap.h.");

    // Number Of Metatiles Total (std::size_t, captured as string, parsed by CliOptionProvider)
    config_group->add_option(
        "--num-metatiles-total",
        storage.num_metatiles_total,
        "Number Of Metatiles Total - The NUM_METATILES_TOTAL setting from include/fieldmap.h.");

    // Number Of Palettes In Primary (std::size_t, captured as string, parsed by CliOptionProvider)
    config_group->add_option(
        "--num-pals-in-primary",
        storage.num_pals_in_primary,
        "Number Of Palettes In Primary - The NUM_PALS_IN_PRIMARY setting from include/fieldmap.h.");

    // Number Of Palettes Total (std::size_t, captured as string, parsed by CliOptionProvider)
    config_group->add_option(
        "--num-pals-total",
        storage.num_pals_total,
        "Number Of Palettes Total - The NUM_PALS_TOTAL setting from include/fieldmap.h.");

    // Max Map Data Size (std::size_t, captured as string, parsed by CliOptionProvider)
    config_group->add_option(
        "--max-map-data-size",
        storage.max_map_data_size,
        "Max Map Data Size - The MAX_MAP_DATA_SIZE setting from include/fieldmap.h.");

    // Number Of Tiles Per Metatile (std::size_t, captured as string, parsed by CliOptionProvider)
    config_group->add_option(
        "--num-tiles-per-metatile",
        storage.num_tiles_per_metatile,
        "Number Of Tiles Per Metatile - The NUM_TILES_PER_METATILE setting from include/fieldmap.h.");

    // Extrinsic Transparency (Rgba32, captured as string, parsed by CliOptionProvider)
    config_group
        ->add_option(
            "--extrinsic-transparency",
            storage.extrinsic_transparency,
            "Extrinsic Transparency - The RGB color to treat as transparent during compilation. (format: R,G,B or "
            "R,G,B,A, values 0-255)")
        ->type_name("R,G,B[,A]");

    // Tiles Edit Mode (enum ArtifactEditMode, captured as string, parsed by CliOptionProvider)
    config_group
        ->add_option(
            "--tiles-edit-mode",
            storage.tiles_edit_mode,
            "Tiles Edit Mode - The allowed edit mode for the tiles.png artifact.")
        ->type_name("{locked|patch|optimize}");

    // Palettes Edit Mode (enum ArtifactEditMode, captured as string, parsed by CliOptionProvider)
    config_group
        ->add_option(
            "--pals-edit-mode",
            storage.pals_edit_mode,
            "Palettes Edit Mode - The allowed edit mode for the palettes/ artifacts.")
        ->type_name("{locked|patch|optimize}");

    // Palette Hints Enabled (bool with --flag/--no-flag, captured as "true"/"false" string)
    config_group->add_flag(
        "--pal-hints-enabled,!--no-pal-hints-enabled",
        [&storage](std::int64_t count) {
            if (count > 0) {
                storage.pal_hints_enabled = "true";
            }
            else if (count < 0) {
                storage.pal_hints_enabled = "false";
            }
            // count == 0 means neither flag was provided, leave optional empty
        },
        "Palette Hints Enabled - Enable configured palette hints.");

    // Packing Strategy (enum PackingStrategyType, captured as string, parsed by CliOptionProvider)
    config_group
        ->add_option(
            "--packing-strategy",
            storage.packing_strategy,
            "Packing Strategy - The palette packing algorithm to use during compilation.")
        ->type_name("{best-fusion|backtracking|overload-and-remove}");

    // Tile Sharing Packing (enum TileSharingPacking, captured as string, parsed by CliOptionProvider)
    config_group
        ->add_option(
            "--tile-sharing-packing",
            storage.tile_sharing_packing,
            "Tile Sharing Packing - Controls whether palette packing considers tile sharing.")
        ->type_name("{off|biased|optimal}");

    // Tile Sharing Alignment (enum TileSharingAlignment, captured as string, parsed by CliOptionProvider)
    config_group
        ->add_option(
            "--tile-sharing-alignment",
            storage.tile_sharing_alignment,
            "Tile Sharing Alignment - Controls palette slot alignment strategy for tile sharing.")
        ->type_name("{off|greedy|optimal}");

    // Tiles Palette Mode (enum TilesPalMode, captured as string, parsed by CliOptionProvider)
    config_group
        ->add_option(
            "--tiles-pal-mode",
            storage.tiles_pal_mode,
            "Tiles Palette Mode - The color mode to use when saving the tiles.png artifact.")
        ->type_name("{true-color|greyscale}");

    // Global Animation Palette Resolution Strategy (enum AnimPalResolutionStrategy, captured as string, parsed by
    // CliOptionProvider)
    config_group
        ->add_option(
            "--anim-pal-resolution-strategy",
            storage.global_anim_pal_resolution_strategy,
            "Global Animation Palette Resolution Strategy - The global strategy for determining which palette to use "
            "when decompiling animation tiles.")
        ->type_name(
            "{scan-local-metatiles|palette-00|palette-01|palette-02|palette-03|palette-04|palette-05|palette-06|"
            "palette-07|palette-08|palette-09|palette-10|palette-11|palette-12|palette-13|palette-14|palette-15|"
            "internal-png-pal|scan-all-tilesets}");

    // Global Animation Key Frame Resolution Strategy (enum AnimKeyFrameResolutionStrategy, captured as string, parsed
    // by CliOptionProvider)
    config_group
        ->add_option(
            "--anim-key-frame-resolution-strategy",
            storage.global_anim_key_frame_resolution_strategy,
            "Global Animation Key Frame Resolution Strategy - The strategy to use when decompilation encounters "
            "duplicate key frame subtiles.")
        ->type_name("{error|warning|mangle}");

    // Global Animation Multi-Pal Subtile Resolution Strategy (enum AnimMultiPalSubtileResolutionStrategy, captured as
    // string, parsed by CliOptionProvider)
    config_group
        ->add_option(
            "--anim-multi-pal-subtile-resolution-strategy",
            storage.global_anim_multi_pal_subtile_resolution_strategy,
            "Global Animation Multi-Pal Subtile Resolution Strategy - The strategy for handling animation subtiles "
            "referenced with multiple palettes.")
        ->type_name("{error|warning|split}");

    // Global Frame Linking (enum FrameLinking, captured as string, parsed by CliOptionProvider)
    config_group
        ->add_option(
            "--frame-linking",
            storage.global_frame_linking,
            "Global Frame Linking - The global default frame linking mode for animations.")
        ->type_name("{automatic|manual|hybrid}");

    // Cross-Tileset Animation Linking (bool with --flag/--no-flag, captured as "true"/"false" string)
    config_group->add_flag(
        "--cross-tileset-anim-linking,!--no-cross-tileset-anim-linking",
        [&storage](std::int64_t count) {
            if (count > 0) {
                storage.cross_tileset_anim_linking = "true";
            }
            else if (count < 0) {
                storage.cross_tileset_anim_linking = "false";
            }
            // count == 0 means neither flag was provided, leave optional empty
        },
        "Cross-Tileset Animation Linking - Enable automatic matching of secondary tiles against primary animation key "
        "frames.");

    // Verify Checksums (bool with --flag/--no-flag, captured as "true"/"false" string)
    config_group->add_flag(
        "--verify-checksums,!--no-verify-checksums",
        [&storage](std::int64_t count) {
            if (count > 0) {
                storage.verify_checksums = "true";
            }
            else if (count < 0) {
                storage.verify_checksums = "false";
            }
            // count == 0 means neither flag was provided, leave optional empty
        },
        "Verify Checksums - Enable or disable artifact checksum verification.");

    // Primary Pairing Mode (enum PrimaryPairingMode, captured as string, parsed by CliOptionProvider)
    config_group
        ->add_option(
            "--primary-pairing-mode",
            storage.primary_pairing_mode,
            "Primary Pairing Mode - How a secondary tileset resolves its partner primary for compilation.")
        ->type_name("{off|manual|automatic}");

    // Primary Pairing Partners (std::vector<std::string>, multi-value)
    config_group->add_option(
        "--primary-pairing-partners",
        storage.primary_pairing_partners,
        "Primary Pairing Partners - Tileset names to use as partner primaries in manual pairing mode.");

    // Diagnostic Warnings Exclude (std::vector<std::string>, multi-value)
    config_group->add_option(
        "--diagnostic-warnings-exclude",
        storage.diagnostic_warnings_exclude,
        "Diagnostic Warnings Exclude - Regex patterns for warning tags to exclude.");

    // Diagnostic Warnings Include (std::vector<std::string>, multi-value)
    config_group->add_option(
        "--diagnostic-warnings-include",
        storage.diagnostic_warnings_include,
        "Diagnostic Warnings Include - Regex patterns for warning tags to include (overrides excludes).");

    // Diagnostic Remarks Exclude (std::vector<std::string>, multi-value)
    config_group->add_option(
        "--diagnostic-remarks-exclude",
        storage.diagnostic_remarks_exclude,
        "Diagnostic Remarks Exclude - Regex patterns for remark tags to exclude.");

    // Diagnostic Remarks Include (std::vector<std::string>, multi-value)
    config_group->add_option(
        "--diagnostic-remarks-include",
        storage.diagnostic_remarks_include,
        "Diagnostic Remarks Include - Regex patterns for remark tags to include (overrides excludes).");

    // Tileset Paths Primary Source (std::string)
    config_group->add_option(
        "--tileset-paths-primary-src",
        storage.tileset_paths_primary_src,
        "Tileset Paths Primary Source - The directory for primary tileset Porytiles component assets.");

    // Tileset Paths Primary Bin (std::string)
    config_group->add_option(
        "--tileset-paths-primary-bin",
        storage.tileset_paths_primary_bin,
        "Tileset Paths Primary Bin - The directory for primary tileset Porymap component assets.");

    // Tileset Paths Secondary Source (std::string)
    config_group->add_option(
        "--tileset-paths-secondary-src",
        storage.tileset_paths_secondary_src,
        "Tileset Paths Secondary Source - The directory for secondary tileset Porytiles component assets.");

    // Tileset Paths Secondary Bin (std::string)
    config_group->add_option(
        "--tileset-paths-secondary-bin",
        storage.tileset_paths_secondary_bin,
        "Tileset Paths Secondary Bin - The directory for secondary tileset Porymap component assets.");

    // Write Layer Type Column (bool with --flag/--no-flag, captured as "true"/"false" string)
    config_group->add_flag(
        "--write-layer-type-column,!--no-write-layer-type-column",
        [&storage](std::int64_t count) {
            if (count > 0) {
                storage.write_layer_type_column = "true";
            }
            else if (count < 0) {
                storage.write_layer_type_column = "false";
            }
            // count == 0 means neither flag was provided, leave optional empty
        },
        "Write Layer Type Column - Emit and honor a layer_type column in the metatile attributes CSV.");

    // Use FRLG Alternate Masks (enum FrlgAlternateMaskMode, captured as string, parsed by CliOptionProvider)
    config_group
        ->add_option(
            "--use-frlg-alternate-masks",
            storage.use_frlg_alternate_masks,
            "Use FRLG Alternate Masks - Whether to select the FireRed/LeafGreen alternate metatile attribute masks for "
            "a tileset: automatic (cross-reference layouts.json), always, or never. true/false are accepted as aliases "
            "for always/never. Intended to be set at tileset scope in porytiles/tilesets/<name>/config.yaml.")
        ->type_name("{automatic|always|never}");

    // Metatile Layer Type Mask (optional mask, captured as string, parsed by CliOptionProvider)
    config_group->add_option(
        "--metatile-layer-type-mask",
        storage.metatile_layer_type_mask,
        "Metatile Layer Type Mask - Bit mask (a hex literal like 0xF000) for the layer-type bits of a metatile "
        "attribute. A mask of 0 disables the layer type, so every metatile is Normal and no layer-type bits are "
        "written. When unset, Porytiles infers the mask from the base game (METATILE_ATTR_LAYER_MASK / "
        "sMetatileAttrMasks) and falls back to the size convention. Intended to be set at tileset scope.");

    // Metatile Layer Type Mask FRLG (optional mask, captured as string, parsed by CliOptionProvider)
    config_group->add_option(
        "--metatile-layer-type-mask-frlg",
        storage.metatile_layer_type_mask_frlg,
        "Metatile Layer Type Mask FRLG - Bit mask (a hex literal like 0x60000000) for the layer-type bits under the "
        "FireRed/LeafGreen alternate attribute layout. A mask of 0 disables the layer type. When unset, Porytiles "
        "infers the mask from the base game and falls back to the size convention. Intended to be set at tileset "
        "scope.");

    // Tileset Animations Wire Anim Code (bool with --flag/--no-flag, captured as "true"/"false" string)
    config_group->add_flag(
        "--tileset-animations-wire-anim-code,!--no-tileset-animations-wire-anim-code",
        [&storage](std::int64_t count) {
            if (count > 0) {
                storage.tileset_animations_wire_anim_code = "true";
            }
            else if (count < 0) {
                storage.tileset_animations_wire_anim_code = "false";
            }
            // count == 0 means neither flag was provided, leave optional empty
        },
        "Tileset Animations Wire Anim Code - Enable or disable automatic animation code wiring.");
}

} // namespace porytiles