#pragma once

#include <string>

#include "porytiles2/templates/Result.hpp"

namespace porytiles {

/**
 * @brief Interface for modifying C source files to integrate new tilesets.
 *
 * @details
 * This interface provides a clean abstraction for modifying C header files
 * that define tileset data and structures. It focuses on file modification
 * operations without coupling to specific implementation strategies or
 * code generation details.
 *
 * The interface supports modification of the three main tileset-related
 * C header files in the pokeemerald project structure:
 * - `graphics.h` - Contains palette and tile data declarations
 * - `headers.h` - Contains tileset struct definitions
 * - `metatiles.h` - Contains metatile and attribute array declarations
 *
 * All operations return Result<void> to indicate success or failure with
 * descriptive error messages for debugging and user feedback.
 */
class CSourceFileModifier {
public:
  virtual ~CSourceFileModifier() = default;

  /**
   * @brief Append palette and tile declarations to the graphics header.
   *
   * @details
   * Modifies the `src/data/tilesets/graphics.h` file to include the necessary
   * palette and tile data declarations for the specified tileset. This includes
   * both the palette array declaration and the tile data declaration generated
   * by the CSourceGenerator.
   *
   * The method appends the declarations to the appropriate section of the file,
   * ensuring proper formatting and integration with existing content.
   *
   * @param tileset_name The name of the tileset (e.g., "MyTileset")
   * @return Result<void> indicating success or failure with error details
   */
  [[nodiscard]] virtual Result<void> AppendToGraphicsHeader(const std::string &tileset_name) = 0;

  /**
   * @brief Append tileset struct definition to the headers file.
   *
   * @details
   * Modifies the `src/data/tilesets/headers.h` file to include the tileset
   * struct definition for the specified tileset. This includes the complete
   * Tileset struct with all required fields and proper references to the
   * data arrays.
   *
   * The method appends the struct definition to the appropriate section of
   * the file, ensuring proper formatting and integration with existing content.
   *
   * @param tileset_name The name of the tileset (e.g., "MyTileset")
   * @return Result<void> indicating success or failure with error details
   */
  [[nodiscard]] virtual Result<void> AppendToHeadersHeader(const std::string &tileset_name) = 0;

  /**
   * @brief Append metatile and attribute declarations to the metatiles header.
   *
   * @details
   * Modifies the `src/data/tilesets/metatiles.h` file to include the necessary
   * metatile and metatile attribute array declarations for the specified tileset.
   * This includes both the metatile data declaration and the metatile attribute
   * data declaration generated by the CSourceGenerator.
   *
   * The method appends the declarations to the appropriate section of the file,
   * ensuring proper formatting and integration with existing content.
   *
   * @param tileset_name The name of the tileset (e.g., "MyTileset")
   * @return Result<void> indicating success or failure with error details
   */
  [[nodiscard]] virtual Result<void> AppendToMetatilesHeader(const std::string &tileset_name) = 0;

  /**
   * @brief Append all necessary declarations for a new tileset.
   *
   * @details
   * Convenience method that performs all three header file modifications
   * in a single operation. This method calls AppendToGraphicsHeader,
   * AppendToHeadersHeader, and AppendToMetatilesHeader in sequence.
   *
   * If any of the individual operations fail, the entire operation fails
   * and returns an error. This provides atomic behavior for tileset
   * integration - either all files are successfully modified or none are.
   *
   * @param tileset_name The name of the tileset (e.g., "MyTileset")
   * @return Result<void> indicating success or failure with error details
   */
  [[nodiscard]] virtual Result<void> AppendTilesetDeclarations(const std::string &tileset_name) = 0;
};

} // namespace porytiles