#ifndef GUARD_METATILE_BEHAVIORS_DUPLICATE_VALUE_H
#define GUARD_METATILE_BEHAVIORS_DUPLICATE_VALUE_H

#define MB_NORMAL 0x00
#define MB_SECRET_BASE_WALL 0x01
#define MB_TALL_GRASS 0x02
#define MB_LONG_GRASS 0x03
#define MB_DEEP_WATER 0x12

// Different name but same value as MB_TALL_GRASS
#define MB_GRASS_TALL 0x02

#endif // GUARD_METATILE_BEHAVIORS_DUPLICATE_VALUE_H
