#pragma once

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate via:
 *
 *   uv run Scripts/generate_config.py
 */

#include <memory>
#include <string>

#include "porytiles/app/config/app_config.hpp"
#include "porytiles/infra/config/config_provider.hpp"

namespace porytiles {

class MockAppConfig : public AppConfig {
  public:
    // Stub: mocks do not layer providers.
    void add_provider(std::unique_ptr<ConfigProvider>) override {}

    bool verify_checksums = true;
    PrimaryPairingMode primary_pairing_mode = PrimaryPairingMode::automatic;
    std::vector<std::string> primary_pairing_partners = std::vector<std::string>{};
    std::vector<std::string> diagnostic_warnings_exclude = std::vector<std::string>{};
    std::vector<std::string> diagnostic_warnings_include = std::vector<std::string>{};
    std::vector<std::string> diagnostic_remarks_exclude = std::vector<std::string>{};
    std::vector<std::string> diagnostic_remarks_include = std::vector<std::string>{};


  protected:

    [[nodiscard]] ChainableResult<ConfigValue<bool>>
    verify_checksums_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{
            verify_checksums, "Verify Checksums", "verify_checksums", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<PrimaryPairingMode>>
    primary_pairing_mode_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{
            primary_pairing_mode, "Primary Pairing Mode", "primary_pairing_mode", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<std::vector<std::string>>>
    primary_pairing_partners_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{
            primary_pairing_partners, "Primary Pairing Partners", "primary_pairing_partners", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_warnings_exclude_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{
            diagnostic_warnings_exclude, "Diagnostic Warnings Exclude", "diagnostic_warnings_exclude", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_warnings_include_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{
            diagnostic_warnings_include, "Diagnostic Warnings Include", "diagnostic_warnings_include", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_remarks_exclude_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{
            diagnostic_remarks_exclude, "Diagnostic Remarks Exclude", "diagnostic_remarks_exclude", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_remarks_include_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{
            diagnostic_remarks_include, "Diagnostic Remarks Include", "diagnostic_remarks_include", "mock", {}};
    }

};

} // namespace porytiles