#pragma once

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate via:
 *
 *   uv run Scripts/generate_config.py
 */

#include <string>
#include <vector>

#include "porytiles2/domain/config/domain_config.hpp"

namespace porytiles2 {

class MockDomainConfig : public DomainConfig {
  public:
    std::size_t num_tiles_in_primary = 512;
    std::size_t num_tiles_total = 1024;
    std::size_t num_metatiles_in_primary = 512;
    std::size_t num_metatiles_total = 1024;
    std::size_t num_pals_in_primary = 6;
    std::size_t num_pals_total = 13;
    std::size_t max_map_data_size = 10240;
    std::size_t num_tiles_per_metatile = 8;
    Rgba32 extrinsic_transparency = rgba_magenta;
    ArtifactEditMode tiles_edit_mode = ArtifactEditMode::optimize;
    ArtifactEditMode pals_edit_mode = ArtifactEditMode::optimize;
    bool pal_hints_enabled = true;
    std::vector<PaletteHint> pal_hints = std::vector<PaletteHint>{};
    PackingStrategyType packing_strategy = PackingStrategyType::backtracking;
    PackingStrategyParams packing_strategy_params = PackingStrategyParams{};
    TilesPalMode tiles_pal_mode = TilesPalMode::true_color;
    AnimPalResolutionStrategy global_anim_pal_resolution_strategy = AnimPalResolutionStrategy::scan_local_metatiles;
    AnimKeyFrameResolutionStrategy global_anim_key_frame_resolution_strategy = AnimKeyFrameResolutionStrategy::error;
    AnimMultiPalSubtileResolutionStrategy global_anim_multi_pal_subtile_resolution_strategy =
        AnimMultiPalSubtileResolutionStrategy::error;
    FrameLinking global_frame_linking = FrameLinking::automatic;
    PerAnimOverrides per_anim_overrides = PerAnimOverrides{};

  protected:
    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_tiles_in_primary_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{num_tiles_in_primary, "Number Of Tiles In Primary", "num_tiles_in_primary", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_tiles_total_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{num_tiles_total, "Number Of Tiles Total", "num_tiles_total", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_metatiles_in_primary_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{
            num_metatiles_in_primary, "Number Of Metatiles In Primary", "num_metatiles_in_primary", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_metatiles_total_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{num_metatiles_total, "Number Of Metatiles Total", "num_metatiles_total", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_pals_in_primary_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{num_pals_in_primary, "Number Of Palettes In Primary", "num_pals_in_primary", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_pals_total_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{num_pals_total, "Number Of Palettes Total", "num_pals_total", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    max_map_data_size_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{max_map_data_size, "Max Map Data Size", "max_map_data_size", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_tiles_per_metatile_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{
            num_tiles_per_metatile, "Number Of Tiles Per Metatile", "num_tiles_per_metatile", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<Rgba32>>
    extrinsic_transparency_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{extrinsic_transparency, "Extrinsic Transparency", "extrinsic_transparency", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<ArtifactEditMode>>
    tiles_edit_mode_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{tiles_edit_mode, "Tiles Edit Mode", "tiles_edit_mode", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<ArtifactEditMode>>
    pals_edit_mode_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{pals_edit_mode, "Palettes Edit Mode", "pals_edit_mode", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<bool>>
    pal_hints_enabled_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{pal_hints_enabled, "Palette Hints Enabled", "pal_hints_enabled", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<std::vector<PaletteHint>>>
    pal_hints_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{pal_hints, "Palette Hints", "pal_hints", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<PackingStrategyType>>
    packing_strategy_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{packing_strategy, "Packing Strategy", "packing_strategy", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<PackingStrategyParams>>
    packing_strategy_params_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{packing_strategy_params, "Packing Strategy Params", "packing_strategy_params", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<TilesPalMode>>
    tiles_pal_mode_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{tiles_pal_mode, "Tiles Palette Mode", "tiles_pal_mode", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<AnimPalResolutionStrategy>>
    global_anim_pal_resolution_strategy_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{
            global_anim_pal_resolution_strategy,
            "Global Animation Palette Resolution Strategy",
            "global_anim_pal_resolution_strategy",
            "mock",
            {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<AnimKeyFrameResolutionStrategy>>
    global_anim_key_frame_resolution_strategy_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{
            global_anim_key_frame_resolution_strategy,
            "Global Animation Key Frame Resolution Strategy",
            "global_anim_key_frame_resolution_strategy",
            "mock",
            {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<AnimMultiPalSubtileResolutionStrategy>>
    global_anim_multi_pal_subtile_resolution_strategy_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{
            global_anim_multi_pal_subtile_resolution_strategy,
            "Global Animation Multi-Pal Subtile Resolution Strategy",
            "global_anim_multi_pal_subtile_resolution_strategy",
            "mock",
            {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<FrameLinking>>
    global_frame_linking_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{global_frame_linking, "Global Frame Linking", "global_frame_linking", "mock", {}};
    }

    [[nodiscard]] ChainableResult<ConfigValue<PerAnimOverrides>>
    per_anim_overrides_raw(ConfigScopeType, const std::string &) const override
    {
        return ConfigValue{per_anim_overrides, "Per-Animation Overrides", "per_anim_overrides", "mock", {}};
    }
};

} // namespace porytiles2