#ifndef GUARD_GENERATED_ANIM_CODE_PorytilesTest_H
#define GUARD_GENERATED_ANIM_CODE_PorytilesTest_H

// Ensure INCBIN_U16 is available
#ifndef INCBIN_U16
#include "gba/defines.h"
#endif

/*
 * This file is auto-generated by Porytiles.
 * DO NOT EDIT THIS FILE MANUALLY (unless you know what you are doing).
 */

// ============================================
// Frame Data (INCBIN statements)
// ============================================

const u16 gTilesetAnims_PorytilesManaged_PorytilesTest_FlowerYellow_FrameCenter[] = INCBIN_U16("data/tilesets/primary/porytiles_test/anim/flower_yellow/center.4bpp");
const u16 gTilesetAnims_PorytilesManaged_PorytilesTest_FlowerYellow_FrameLeft[] = INCBIN_U16("data/tilesets/primary/porytiles_test/anim/flower_yellow/left.4bpp");
const u16 gTilesetAnims_PorytilesManaged_PorytilesTest_FlowerYellow_FrameRight[] = INCBIN_U16("data/tilesets/primary/porytiles_test/anim/flower_yellow/right.4bpp");

// ============================================
// Frame Pointer Arrays
// ============================================

const u16 *const gTilesetAnims_PorytilesManaged_PorytilesTest_FlowerYellow[] = {
    gTilesetAnims_PorytilesManaged_PorytilesTest_FlowerYellow_FrameCenter,
    gTilesetAnims_PorytilesManaged_PorytilesTest_FlowerYellow_FrameLeft,
    gTilesetAnims_PorytilesManaged_PorytilesTest_FlowerYellow_FrameCenter,
    gTilesetAnims_PorytilesManaged_PorytilesTest_FlowerYellow_FrameRight
};

// ============================================
// Queue Functions
// ============================================

static void QueueAnimTiles_PorytilesManaged_PorytilesTest_FlowerYellow(u16 timer)
{
    u16 i = timer % ARRAY_COUNT(gTilesetAnims_PorytilesManaged_PorytilesTest_FlowerYellow);
    AppendTilesetAnimToBuffer(gTilesetAnims_PorytilesManaged_PorytilesTest_FlowerYellow[i], (u16 *)(BG_VRAM + TILE_OFFSET_4BPP(234)), 4 * TILE_SIZE_4BPP);
}

// ============================================
// Driver Function
// ============================================

static void TilesetAnim_PorytilesManaged_PorytilesTest(u16 timer)
{
    if (timer % 16 == 0)
        QueueAnimTiles_PorytilesManaged_PorytilesTest_FlowerYellow(timer / 16);
}

// ============================================
// Init Function
// ============================================

void InitTilesetAnim_PorytilesManaged_PorytilesTest(void)
{
    sPrimaryTilesetAnimCounter = 0;
    sPrimaryTilesetAnimCounterMax = 256;
    sPrimaryTilesetAnimCallback = TilesetAnim_PorytilesManaged_PorytilesTest;
}

#endif // GUARD_GENERATED_ANIM_CODE_PorytilesTest_H
