#pragma once

#include <any>
#include <fmt/color.h>
#include <fmt/ranges.h>
#include <functional>
#include <sstream>
#include <string>

#include "../types.h"

namespace porytiles {

enum class diag_level { ignored, note, remark, warning, error, fatal };
std::string level_to_str(diag_level level);
fmt::terminal_color color_for_level(diag_level level);
int level_priority(diag_level level);

/// @brief diag_engine coordinates the generation and consumption of diagnostic
/// messages.
///
/// The full definition for this class is in diagnostics/diagnostic_engine.hpp.
class diag_engine;

/// @brief diag_templ defines a reusable template for standardized diagnostic
/// reporting.
///
/// @details
/// diag_templ is used by the diag_engine to construct the actual diagnostic
/// instance when one is in-flight. A diag_templ defines a unique name for the
/// diagnostic as well as some default settings. It provides a template for the
/// diagnostic message: either in the form of a static format string or a
/// dynamic builder function. It also contains a list of partner diagnostics.
/// Partner diagnostics are used for warnings/errors that have associated notes.
class diag_templ {

    /// @brief dynamic_msg_builder is an alias for a dynamic diagnostic message
    /// builder function.
    ///
    /// @details dynamic_msg_builder defines a function signature
    /// for building diagnostic messages dynamically. The function signature
    /// accepts a boolean flag indicating whether the output is directed to a
    /// tty (terminal), a diag_level noting the actual in-flight level of the
    /// diagnostic, and a vector of additional parameters (of type std::any)
    /// used to customize the diagnostic message. It returns a vector of
    /// formatted strings representing the final diagnostic message. Each
    /// element in the vector represents a single line of output for a
    /// diag_consumer to consume.
    using dynamic_msg_builder = std::function<std::vector<std::string>(
        const diag_engine &eng, diag_level in_flight_level, const std::vector<std::any> &args)>;

    std::string_view name_;
    diag_level default_level_;
    std::string_view static_msg_templ_;
    dynamic_msg_builder dynamic_msg_builder_;
    std::vector<diag_templ> partner_diags_;

  public:
    // @formatter:off
    // clang-format off
    explicit diag_templ(std::string_view name, diag_level default_level,
                      dynamic_msg_builder dynamic_msg_builder) noexcept
        : name_{name},
          default_level_{default_level},
          dynamic_msg_builder_{std::move(dynamic_msg_builder)} {}

    explicit diag_templ(std::string_view name, diag_level default_level,
                        dynamic_msg_builder dynamic_msg_builder, const std::vector<diag_templ> &partner_diags) noexcept
        : name_{name},
          default_level_{default_level},
          dynamic_msg_builder_{std::move(dynamic_msg_builder)},
          partner_diags_{partner_diags} {}

    explicit diag_templ(std::string_view name, diag_level default_level,
                    std::string_view static_msg_templ) noexcept
        : name_{name},
          default_level_{default_level},
          static_msg_templ_{static_msg_templ},
          dynamic_msg_builder_{nullptr} {}

    explicit diag_templ(std::string_view name, diag_level default_level,
                        std::string_view static_msg_templ, const std::vector<diag_templ> &partner_diags) noexcept
        : name_{name},
          default_level_{default_level},
          static_msg_templ_{static_msg_templ},
          dynamic_msg_builder_{nullptr},
          partner_diags_{partner_diags} {}
    // @formatter:on
    // clang-format on

    [[nodiscard]] std::string_view name() const {
        return name_;
    }

    [[nodiscard]] diag_level level() const {
        return default_level_;
    }

    [[nodiscard]] std::string_view static_msg_templ() const {
        return static_msg_templ_;
    }

    template <typename... Args>
    std::vector<std::string> build_dynamic_msg(const diag_engine &eng, const diag_level in_flight_level,
                                               Args &&...args) const {
        if (dynamic_msg_builder_ == nullptr) {
            std::vector<std::string> v{};
            v.push_back(fmt::format(fmt::runtime(static_msg_templ_), std::forward<Args>(args)...));
            return v;
        }
        const std::vector<std::any> v{std::forward<Args>(args)...};
        return dynamic_msg_builder_(eng, in_flight_level, v);
    }

    [[nodiscard]] const std::vector<diag_templ> &partner_diags() const {
        return partner_diags_;
    }
};

/// @brief in_flight_diag represents an in-flight diagnostic.
///
/// @details
/// in_flight_diag is generated by the diag_engine by combining the template
/// with context from the various user defined diagnostic parameters (e.g.
/// warnings as errors, specific warning disables, etc.).
class in_flight_diag {
  public:
    explicit in_flight_diag(diag_level level, std::string msg, diag_templ templ) noexcept
        : level_{level}, msg_{std::move(msg)}, templ_{std::move(templ)} {}

    [[nodiscard]] diag_level level() const noexcept {
        return level_;
    }

    [[nodiscard]] std::string msg() const noexcept {
        return msg_;
    }

    [[nodiscard]] const diag_templ &templ() const noexcept {
        return templ_;
    }

  private:
    diag_level level_;
    std::string msg_;
    diag_templ templ_;
};

class diag_consumer {
  public:
    virtual ~diag_consumer() = default;
    virtual void consume(const in_flight_diag &diag) = 0;
    [[nodiscard]] virtual bool is_a_tty() const = 0;
    [[nodiscard]] virtual in_flight_diag consumed_at(std::size_t i) const = 0;
    [[nodiscard]] virtual std::uint64_t consumed_count() const = 0;
};

/// @brief ignore_consumer is a consumer implementation that simply ignores the
/// diagnostic.
class ignore_consumer final : public diag_consumer {
  public:
    void consume(const in_flight_diag &diag) override;
    [[nodiscard]] bool is_a_tty() const override;
    [[nodiscard]] in_flight_diag consumed_at(std::size_t i) const override;
    [[nodiscard]] std::uint64_t consumed_count() const override;

  private:
    std::uint64_t consumed_count_{};
};

/// @brief stderr_consumer is a consumer implementation that pushes diagnostic
/// messages to stderr.
class stderr_consumer final : public diag_consumer {
  public:
    void consume(const in_flight_diag &diag) override;
    [[nodiscard]] bool is_a_tty() const override;
    [[nodiscard]] in_flight_diag consumed_at(std::size_t i) const override;
    [[nodiscard]] std::uint64_t consumed_count() const override;

  private:
    std::uint64_t consumed_count_{};
};

/// @brief vector_consumer is a consumer implementation that pushes diagnostic
/// messages to an internal vector for testing purposes.
class vector_consumer final : public diag_consumer {
  public:
    void consume(const in_flight_diag &diag) override;
    [[nodiscard]] bool is_a_tty() const override;
    [[nodiscard]] in_flight_diag consumed_at(std::size_t i) const override;
    [[nodiscard]] std::uint64_t consumed_count() const override;

  private:
    std::vector<in_flight_diag> diags_;
};

// @formatter:off
// clang-format off

////////////////////////////////////////////////////////////////////////////////
///
/// WARNINGS
///
////////////////////////////////////////////////////////////////////////////////
constexpr auto W_COLOR_PRECISION_LOSS = "color-precision-loss";
constexpr auto W_KEY_FRAME_NO_MATCHING_TILE = "key-frame-no-matching-tile";
constexpr auto W_KEY_FRAME_MISSING_COLORS = "key-frame-missing-colors";
constexpr auto W_ATTRIBUTE_FORMAT_MISMATCH = "attribute-format-mismatch";
constexpr auto W_MISSING_ATTRIBUTES_CSV = "missing-attributes-csv";
constexpr auto W_UNUSED_ATTRIBUTE = "unused-attribute";
constexpr auto W_TRANSPARENCY_COLLAPSE = "transparency-collapse";
constexpr auto W_UNUSED_MANUAL_PAL_COLOR = "unused-manual-pal-color";
constexpr auto W_TILE_INDEX_OUT_OF_RANGE = "tile-index-out-of-range";
constexpr auto W_PALETTE_INDEX_OUT_OF_RANGE = "palette-index-out-of-range";


////////////////////////////////////////////////////////////////////////////////
///
/// ERRORS
///
////////////////////////////////////////////////////////////////////////////////
constexpr auto E_GENERIC = "error-generic";
constexpr auto E_FATAL_GENERIC = "error-fatal-generic";

// @formatter:on
// clang-format on

/// @brief Retrieves the diagnostic template corresponding to a given diagnostic
/// name.
///
/// This function searches an internal table for the provided diagnostic
/// identifier. If the identifier is found, the corresponding diagnostic
/// template is returned. If not, the function triggers a panic with an error
/// message indicating an unknown diagnostic.
///
/// @param name A std::string_view representing the diagnostic name.
/// @return diag_template The diagnostic template associated with the given
/// identifier.
///
/// @note The function will terminate the program if the diagnostic name is
/// invalid.
diag_templ diag_templ_for(std::string_view name);

/// @brief Get an iterable view of all diag_templ names in the internal table.
///
/// The identifiers returned from this function can then be used for lookup in
/// diag_templ_for. This may be useful for range-based for-loops, or other use
/// cases where the user wants to perform an action for some or all diagnostics.
std::vector<const char *> all_diag_templ_names();

} // namespace porytiles
