#pragma once

#include <algorithm>
#include <cctype>
#include <format>
#include <optional>
#include <ostream>
#include <string>

#include "porytiles/utilities/panic/panic.hpp"

// NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
// To add new config values or make other changes, edit config_schema.yaml and regenerate via:
//
//   uv run scripts/generate_config.py

namespace porytiles {

/// @brief Strategy for handling animation subtiles referenced with multiple palettes.
///
/// @details
/// When decompiling animations using the scan_local_metatiles strategy, a single tile index
/// can be referenced by multiple metatile entries with different palette indices. This is valid
/// GBA behavior (the hardware selects palette per metatile entry, not per tile), but Porytiles
/// cannot represent multiple palette variants in a single RGBA layer PNG. This enum determines
/// how to handle such cases.
///
enum class AnimMultiPaletteSubtileResolutionStrategy {
    /// @brief Emit a formatted error and fail decompilation.
    error,
    /// @brief Emit a warning and continue decompilation using the lowest palette index.
    warning,
    /// @brief Split the animation into separate animations for each palette variant (not yet implemented).
    split
};

/// @brief Parses a string into a AnimMultiPaletteSubtileResolutionStrategy with fuzzy matching.
///
/// @details
/// Performs parsing in two phases:
/// 1. Exact match against C++ constant names (snake_case)
/// 2. Case-insensitive fuzzy match against configured fuzzy_names
///
/// This unified function is used by both CLI and YAML parsing. The fuzzy matching
/// allows users to use various common formats (kebab-case, snake_case, etc.) while
/// still getting good error messages through LazyLayeredConfig.
///
/// @param str The string to parse
/// @return The parsed value, or std::nullopt if the string is invalid
[[nodiscard]] inline std::optional<AnimMultiPaletteSubtileResolutionStrategy>
anim_multi_palette_subtile_resolution_strategy_from_str(const std::string &str)
{
    // Phase 1: Exact match against C++ constant names
    if (str == "error") {
        return std::optional{AnimMultiPaletteSubtileResolutionStrategy::error};
    }
    if (str == "warning") {
        return std::optional{AnimMultiPaletteSubtileResolutionStrategy::warning};
    }
    if (str == "split") {
        return std::optional{AnimMultiPaletteSubtileResolutionStrategy::split};
    }

    // Phase 2: Case-insensitive fuzzy match
    std::string lower_str = str;
    std::ranges::transform(
        lower_str, lower_str.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

    // Fuzzy names for error
    if (lower_str == "error") {
        return std::optional{AnimMultiPaletteSubtileResolutionStrategy::error};
    }
    if (lower_str == "err") {
        return std::optional{AnimMultiPaletteSubtileResolutionStrategy::error};
    }
    // Fuzzy names for warning
    if (lower_str == "warning") {
        return std::optional{AnimMultiPaletteSubtileResolutionStrategy::warning};
    }
    if (lower_str == "warn") {
        return std::optional{AnimMultiPaletteSubtileResolutionStrategy::warning};
    }
    // Fuzzy names for split
    if (lower_str == "split") {
        return std::optional{AnimMultiPaletteSubtileResolutionStrategy::split};
    }

    return std::nullopt;
}

/// @brief Converts a AnimMultiPaletteSubtileResolutionStrategy to its canonical string representation.
///
/// @details
/// Returns the C++ constant name (snake_case). This is the canonical form used for
/// general purpose string conversion, logging, and error messages.
///
/// @param m The value to convert
/// @return The canonical snake_case string representation
[[nodiscard]] inline std::string to_string(const AnimMultiPaletteSubtileResolutionStrategy m)
{
    switch (m) {
    case AnimMultiPaletteSubtileResolutionStrategy::error:
        return "error";
    case AnimMultiPaletteSubtileResolutionStrategy::warning:
        return "warning";
    case AnimMultiPaletteSubtileResolutionStrategy::split:
        return "split";
    }
    panic("unhandled AnimMultiPaletteSubtileResolutionStrategy value");
}

/// @brief Stream insertion operator for AnimMultiPaletteSubtileResolutionStrategy.
///
/// @param os The output stream
/// @param m The value to output
/// @return Reference to the output stream
inline std::ostream &operator<<(std::ostream &os, const AnimMultiPaletteSubtileResolutionStrategy m)
{
    return os << to_string(m);
}

} // namespace porytiles

template <>
struct std::formatter<porytiles::AnimMultiPaletteSubtileResolutionStrategy> {
    constexpr auto parse(std::format_parse_context &ctx)
    {
        return ctx.begin();
    }

    auto format(const porytiles::AnimMultiPaletteSubtileResolutionStrategy &value, auto &ctx) const
    {
        return std::format_to(ctx.out(), "{}", porytiles::to_string(value));
    }
};