#pragma once

#include <algorithm>
#include <cctype>
#include <format>
#include <optional>
#include <ostream>
#include <string>

#include "porytiles/utilities/panic/panic.hpp"

// NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
// To add new config values or make other changes, edit config_schema.yaml and regenerate via:
//
//   uv run scripts/generate_config.py

namespace porytiles {

/// @brief Specifies whether artifacts (tiles or palettes) can be modified during patch compilation.
///
/// @details
/// Controls the behavior of tile and palette handling when compiling a tileset patch. In locked mode,
/// the compiler must use only the existing artifacts from the base tileset without modifications. In
/// patch mode, the compiler can modify unused or "open" slots as needed. In optimize mode, artifacts
/// are cleared and packed optimally (Porytiles1 behavior).
///
enum class ArtifactEditMode {
    /// @brief Artifacts cannot be edited; must use existing from base tileset.
    locked,
    /// @brief Artifacts can be freely edited in "open" slots during compilation.
    patch,
    /// @brief The Porytiles1 behavior; artifact is cleared and packed optimally.
    optimize
};

/// @brief Parses a string into a ArtifactEditMode with fuzzy matching.
///
/// @details
/// Performs parsing in two phases:
/// 1. Exact match against C++ constant names (snake_case)
/// 2. Case-insensitive fuzzy match against configured fuzzy_names
///
/// This unified function is used by both CLI and YAML parsing. The fuzzy matching
/// allows users to use various common formats (kebab-case, snake_case, etc.) while
/// still getting good error messages through LazyLayeredConfig.
///
/// @param str The string to parse
/// @return The parsed value, or std::nullopt if the string is invalid
[[nodiscard]] inline std::optional<ArtifactEditMode> artifact_edit_mode_from_str(const std::string &str)
{
    // Phase 1: Exact match against C++ constant names
    if (str == "locked") {
        return std::optional{ArtifactEditMode::locked};
    }
    if (str == "patch") {
        return std::optional{ArtifactEditMode::patch};
    }
    if (str == "optimize") {
        return std::optional{ArtifactEditMode::optimize};
    }

    // Phase 2: Case-insensitive fuzzy match
    std::string lower_str = str;
    std::ranges::transform(
        lower_str, lower_str.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

    // Fuzzy names for locked
    if (lower_str == "locked") {
        return std::optional{ArtifactEditMode::locked};
    }
    // Fuzzy names for patch
    if (lower_str == "patch") {
        return std::optional{ArtifactEditMode::patch};
    }
    // Fuzzy names for optimize
    if (lower_str == "optimize") {
        return std::optional{ArtifactEditMode::optimize};
    }

    return std::nullopt;
}

/// @brief Converts a ArtifactEditMode to its canonical string representation.
///
/// @details
/// Returns the C++ constant name (snake_case). This is the canonical form used for
/// general purpose string conversion, logging, and error messages.
///
/// @param m The value to convert
/// @return The canonical snake_case string representation
[[nodiscard]] inline std::string to_string(const ArtifactEditMode m)
{
    switch (m) {
    case ArtifactEditMode::locked:
        return "locked";
    case ArtifactEditMode::patch:
        return "patch";
    case ArtifactEditMode::optimize:
        return "optimize";
    }
    panic("unhandled ArtifactEditMode value");
}

/// @brief Stream insertion operator for ArtifactEditMode.
///
/// @param os The output stream
/// @param m The value to output
/// @return Reference to the output stream
inline std::ostream &operator<<(std::ostream &os, const ArtifactEditMode m)
{
    return os << to_string(m);
}

} // namespace porytiles

template <>
struct std::formatter<porytiles::ArtifactEditMode> {
    constexpr auto parse(std::format_parse_context &ctx)
    {
        return ctx.begin();
    }

    auto format(const porytiles::ArtifactEditMode &value, auto &ctx) const
    {
        return std::format_to(ctx.out(), "{}", porytiles::to_string(value));
    }
};