#pragma once

#include <algorithm>
#include <cctype>
#include <format>
#include <optional>
#include <ostream>
#include <string>

#include "porytiles/utilities/panic/panic.hpp"

// NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
// To add new config values or make other changes, edit config_schema.yaml and regenerate via:
//
//   uv run scripts/generate_config.py

namespace porytiles {

/// @brief Controls how animation frames are linked to metatile entries.
///
/// @details
/// In automatic mode, Porytiles generates and uses key.png for frame linking.
/// In manual mode, Porytiles uses explicit overrides specified in anim.json.
///
enum class FrameLinking {
    /// @brief Use key.png for frame linking.
    automatic,
    /// @brief Use manual overrides in anim.json.
    manual,
    /// @brief Automatic key.png linking plus manual override pass (not yet implemented).
    hybrid
};

/// @brief Parses a string into a FrameLinking with fuzzy matching.
///
/// @details
/// Performs parsing in two phases:
/// 1. Exact match against C++ constant names (snake_case)
/// 2. Case-insensitive fuzzy match against configured fuzzy_names
///
/// This unified function is used by both CLI and YAML parsing. The fuzzy matching
/// allows users to use various common formats (kebab-case, snake_case, etc.) while
/// still getting good error messages through LazyLayeredConfig.
///
/// @param str The string to parse
/// @return The parsed value, or std::nullopt if the string is invalid
[[nodiscard]] inline std::optional<FrameLinking> frame_linking_from_str(const std::string &str)
{
    // Phase 1: Exact match against C++ constant names
    if (str == "automatic") {
        return std::optional{FrameLinking::automatic};
    }
    if (str == "manual") {
        return std::optional{FrameLinking::manual};
    }
    if (str == "hybrid") {
        return std::optional{FrameLinking::hybrid};
    }

    // Phase 2: Case-insensitive fuzzy match
    std::string lower_str = str;
    std::ranges::transform(
        lower_str, lower_str.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

    // Fuzzy names for automatic
    if (lower_str == "automatic") {
        return std::optional{FrameLinking::automatic};
    }
    if (lower_str == "auto") {
        return std::optional{FrameLinking::automatic};
    }
    // Fuzzy names for manual
    if (lower_str == "manual") {
        return std::optional{FrameLinking::manual};
    }
    // Fuzzy names for hybrid
    if (lower_str == "hybrid") {
        return std::optional{FrameLinking::hybrid};
    }

    return std::nullopt;
}

/// @brief Converts a FrameLinking to its canonical string representation.
///
/// @details
/// Returns the C++ constant name (snake_case). This is the canonical form used for
/// general purpose string conversion, logging, and error messages.
///
/// @param m The value to convert
/// @return The canonical snake_case string representation
[[nodiscard]] inline std::string to_string(const FrameLinking m)
{
    switch (m) {
    case FrameLinking::automatic:
        return "automatic";
    case FrameLinking::manual:
        return "manual";
    case FrameLinking::hybrid:
        return "hybrid";
    }
    panic("unhandled FrameLinking value");
}

/// @brief Stream insertion operator for FrameLinking.
///
/// @param os The output stream
/// @param m The value to output
/// @return Reference to the output stream
inline std::ostream &operator<<(std::ostream &os, const FrameLinking m)
{
    return os << to_string(m);
}

} // namespace porytiles

template <>
struct std::formatter<porytiles::FrameLinking> {
    constexpr auto parse(std::format_parse_context &ctx)
    {
        return ctx.begin();
    }

    auto format(const porytiles::FrameLinking &value, auto &ctx) const
    {
        return std::format_to(ctx.out(), "{}", porytiles::to_string(value));
    }
};