#pragma once

#include <algorithm>
#include <cctype>
#include <format>
#include <optional>
#include <ostream>
#include <string>

#include "porytiles/utilities/panic/panic.hpp"

// NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
// To add new config values or make other changes, edit config_schema.yaml and regenerate via:
//
//   uv run scripts/generate_config.py

namespace porytiles {

/// @brief Selects how transparent pixels are written to RGBA assets during tileset decompilation.
///
/// @details
/// When decompiling Porymap assets to RGBA layer images and animation frames, every palette index 0
/// pixel is transparent. This mode selects which pixel value represents that transparency in the
/// written PNGs: fully transparent (alpha 0) or the opaque extrinsic transparency color. Both forms
/// compile back to the same result, so the choice only affects how the assets look in an image editor.
///
enum class ImportTransparencyMode {
    /// @brief Write every transparent pixel as alpha 0.
    alpha,
    /// @brief Write every transparent pixel as the opaque extrinsic transparency color.
    extrinsic,
    /// @brief In dual-layer mode, write the layer group absent from the Porymap data as alpha 0 and other transparent
    /// pixels as the extrinsic transparency color. In triple-layer mode, same as extrinsic.
    mixed
};

/// @brief Parses a string into a ImportTransparencyMode with fuzzy matching.
///
/// @details
/// Performs parsing in two phases:
/// 1. Exact match against C++ constant names (snake_case)
/// 2. Case-insensitive fuzzy match against configured fuzzy_names
///
/// This unified function is used by both CLI and YAML parsing. The fuzzy matching
/// allows users to use various common formats (kebab-case, snake_case, etc.) while
/// still getting good error messages through LazyLayeredConfig.
///
/// @param str The string to parse
/// @return The parsed value, or std::nullopt if the string is invalid
[[nodiscard]] inline std::optional<ImportTransparencyMode> import_transparency_mode_from_str(const std::string &str)
{
    // Phase 1: Exact match against C++ constant names
    if (str == "alpha") {
        return std::optional{ImportTransparencyMode::alpha};
    }
    if (str == "extrinsic") {
        return std::optional{ImportTransparencyMode::extrinsic};
    }
    if (str == "mixed") {
        return std::optional{ImportTransparencyMode::mixed};
    }

    // Phase 2: Case-insensitive fuzzy match
    std::string lower_str = str;
    std::ranges::transform(
        lower_str, lower_str.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

    // Fuzzy names for alpha
    if (lower_str == "alpha") {
        return std::optional{ImportTransparencyMode::alpha};
    }
    if (lower_str == "intrinsic") {
        return std::optional{ImportTransparencyMode::alpha};
    }
    // Fuzzy names for extrinsic
    if (lower_str == "extrinsic") {
        return std::optional{ImportTransparencyMode::extrinsic};
    }
    // Fuzzy names for mixed
    if (lower_str == "mixed") {
        return std::optional{ImportTransparencyMode::mixed};
    }

    return std::nullopt;
}

/// @brief Converts a ImportTransparencyMode to its canonical string representation.
///
/// @details
/// Returns the C++ constant name (snake_case). This is the canonical form used for
/// general purpose string conversion, logging, and error messages.
///
/// @param m The value to convert
/// @return The canonical snake_case string representation
[[nodiscard]] inline std::string to_string(const ImportTransparencyMode m)
{
    switch (m) {
    case ImportTransparencyMode::alpha:
        return "alpha";
    case ImportTransparencyMode::extrinsic:
        return "extrinsic";
    case ImportTransparencyMode::mixed:
        return "mixed";
    }
    panic("unhandled ImportTransparencyMode value");
}

/// @brief Stream insertion operator for ImportTransparencyMode.
///
/// @param os The output stream
/// @param m The value to output
/// @return Reference to the output stream
inline std::ostream &operator<<(std::ostream &os, const ImportTransparencyMode m)
{
    return os << to_string(m);
}

} // namespace porytiles

template <>
struct std::formatter<porytiles::ImportTransparencyMode> {
    constexpr auto parse(std::format_parse_context &ctx)
    {
        return ctx.begin();
    }

    auto format(const porytiles::ImportTransparencyMode &value, auto &ctx) const
    {
        return std::format_to(ctx.out(), "{}", porytiles::to_string(value));
    }
};