#pragma once

#include <algorithm>
#include <cctype>
#include <format>
#include <optional>
#include <ostream>
#include <string>

#include "porytiles/utilities/panic/panic.hpp"

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate via:
 *
 *   uv run scripts/generate_config.py
 */

namespace porytiles {

/**
 * @brief Controls how tile orderings are generated during multi-start packing.
 *
 * @details
 * The packing algorithm can attempt multiple tile orderings to find a valid solution. This enum
 * controls the strategy used to generate those orderings after the initial FFD (First Fit Decreasing)
 * attempt.
 *
 */
enum class ShuffleStrategy {
    /**
     * @brief One FFD attempt only, no multi-start retries.
     */
    single_ffd,
    /**
     * @brief FFD first, then perturbed FFD orderings that preserve the large-first property.
     */
    noisy_ffd,
    /**
     * @brief FFD first, then fully random shuffles (original behavior).
     */
    random
};

/**
 * @brief Parses a string into a ShuffleStrategy with fuzzy matching.
 *
 * @details
 * Performs parsing in two phases:
 * 1. Exact match against C++ constant names (snake_case)
 * 2. Case-insensitive fuzzy match against configured fuzzy_names
 *
 * This unified function is used by both CLI and YAML parsing. The fuzzy matching
 * allows users to use various common formats (kebab-case, snake_case, etc.) while
 * still getting good error messages through LazyLayeredConfig.
 *
 * @param str The string to parse
 * @return The parsed value, or std::nullopt if the string is invalid
 */
[[nodiscard]] inline std::optional<ShuffleStrategy> shuffle_strategy_from_str(const std::string &str)
{
    // Phase 1: Exact match against C++ constant names
    if (str == "single_ffd") {
        return std::optional{ShuffleStrategy::single_ffd};
    }
    if (str == "noisy_ffd") {
        return std::optional{ShuffleStrategy::noisy_ffd};
    }
    if (str == "random") {
        return std::optional{ShuffleStrategy::random};
    }

    // Phase 2: Case-insensitive fuzzy match
    std::string lower_str = str;
    std::ranges::transform(
        lower_str, lower_str.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

    // Fuzzy names for single_ffd
    if (lower_str == "single-ffd") {
        return std::optional{ShuffleStrategy::single_ffd};
    }
    if (lower_str == "single_ffd") {
        return std::optional{ShuffleStrategy::single_ffd};
    }
    if (lower_str == "singleffd") {
        return std::optional{ShuffleStrategy::single_ffd};
    }
    // Fuzzy names for noisy_ffd
    if (lower_str == "noisy-ffd") {
        return std::optional{ShuffleStrategy::noisy_ffd};
    }
    if (lower_str == "noisy_ffd") {
        return std::optional{ShuffleStrategy::noisy_ffd};
    }
    if (lower_str == "noisyffd") {
        return std::optional{ShuffleStrategy::noisy_ffd};
    }
    // Fuzzy names for random
    if (lower_str == "random") {
        return std::optional{ShuffleStrategy::random};
    }

    return std::nullopt;
}

/**
 * @brief Converts a ShuffleStrategy to its canonical string representation.
 *
 * @details
 * Returns the C++ constant name (snake_case). This is the canonical form used for
 * general purpose string conversion, logging, and error messages.
 *
 * @param m The value to convert
 * @return The canonical snake_case string representation
 */
[[nodiscard]] inline std::string to_string(const ShuffleStrategy m)
{
    switch (m) {
    case ShuffleStrategy::single_ffd:
        return "single_ffd";
    case ShuffleStrategy::noisy_ffd:
        return "noisy_ffd";
    case ShuffleStrategy::random:
        return "random";
    }
    panic("unhandled ShuffleStrategy value");
}

/**
 * @brief Stream insertion operator for ShuffleStrategy.
 *
 * @param os The output stream
 * @param m The value to output
 * @return Reference to the output stream
 */
inline std::ostream &operator<<(std::ostream &os, const ShuffleStrategy m)
{
    return os << to_string(m);
}

} // namespace porytiles

template <>
struct std::formatter<porytiles::ShuffleStrategy> {
    constexpr auto parse(std::format_parse_context &ctx)
    {
        return ctx.begin();
    }

    auto format(const porytiles::ShuffleStrategy &value, auto &ctx) const
    {
        return std::format_to(ctx.out(), "{}", porytiles::to_string(value));
    }
};