#pragma once

#include <algorithm>
#include <cctype>
#include <format>
#include <optional>
#include <ostream>
#include <string>

#include "porytiles/utilities/panic/panic.hpp"

// NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
// To add new config values or make other changes, edit config_schema.yaml and regenerate via:
//
//   uv run scripts/generate_config.py

namespace porytiles {

/// @brief Controls how tiles.png is rendered.
///
/// @details
/// Controls how tiles.png is rendered.
enum class TilesPaletteMode {
    /// @brief Render tiles with true colors from the palette.
    true_color,
    /// @brief Render tiles in greyscale (useful for debugging).
    greyscale
};

/// @brief Parses a string into a TilesPaletteMode with fuzzy matching.
///
/// @details
/// Performs parsing in two phases:
/// 1. Exact match against C++ constant names (snake_case)
/// 2. Case-insensitive fuzzy match against configured fuzzy_names
///
/// This unified function is used by both CLI and YAML parsing. The fuzzy matching
/// allows users to use various common formats (kebab-case, snake_case, etc.) while
/// still getting good error messages through LazyLayeredConfig.
///
/// @param str The string to parse
/// @return The parsed value, or std::nullopt if the string is invalid
[[nodiscard]] inline std::optional<TilesPaletteMode> tiles_palette_mode_from_str(const std::string &str)
{
    // Phase 1: Exact match against C++ constant names
    if (str == "true_color") {
        return std::optional{TilesPaletteMode::true_color};
    }
    if (str == "greyscale") {
        return std::optional{TilesPaletteMode::greyscale};
    }

    // Phase 2: Case-insensitive fuzzy match
    std::string lower_str = str;
    std::ranges::transform(
        lower_str, lower_str.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

    // Fuzzy names for true_color
    if (lower_str == "true-color") {
        return std::optional{TilesPaletteMode::true_color};
    }
    if (lower_str == "true_color") {
        return std::optional{TilesPaletteMode::true_color};
    }
    if (lower_str == "truecolor") {
        return std::optional{TilesPaletteMode::true_color};
    }
    if (lower_str == "color") {
        return std::optional{TilesPaletteMode::true_color};
    }
    // Fuzzy names for greyscale
    if (lower_str == "greyscale") {
        return std::optional{TilesPaletteMode::greyscale};
    }
    if (lower_str == "grayscale") {
        return std::optional{TilesPaletteMode::greyscale};
    }
    if (lower_str == "grey") {
        return std::optional{TilesPaletteMode::greyscale};
    }
    if (lower_str == "gray") {
        return std::optional{TilesPaletteMode::greyscale};
    }

    return std::nullopt;
}

/// @brief Converts a TilesPaletteMode to its canonical string representation.
///
/// @details
/// Returns the C++ constant name (snake_case). This is the canonical form used for
/// general purpose string conversion, logging, and error messages.
///
/// @param m The value to convert
/// @return The canonical snake_case string representation
[[nodiscard]] inline std::string to_string(const TilesPaletteMode m)
{
    switch (m) {
    case TilesPaletteMode::true_color:
        return "true_color";
    case TilesPaletteMode::greyscale:
        return "greyscale";
    }
    panic("unhandled TilesPaletteMode value");
}

/// @brief Stream insertion operator for TilesPaletteMode.
///
/// @param os The output stream
/// @param m The value to output
/// @return Reference to the output stream
inline std::ostream &operator<<(std::ostream &os, const TilesPaletteMode m)
{
    return os << to_string(m);
}

} // namespace porytiles

template <>
struct std::formatter<porytiles::TilesPaletteMode> {
    constexpr auto parse(std::format_parse_context &ctx)
    {
        return ctx.begin();
    }

    auto format(const porytiles::TilesPaletteMode &value, auto &ctx) const
    {
        return std::format_to(ctx.out(), "{}", porytiles::to_string(value));
    }
};