#pragma once

#include "porytiles2/infra/config/config_provider.hpp"

namespace porytiles2 {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate using
 * Scripts/generate_config.py.
 */

/**
 * @brief A default implementation of ConfigProvider that provides sensible default values.
 *
 * @details
 * This provider returns default values for all configuration parameters. It's useful as a base layer in a configuration
 * system where other providers can override specific values.
 */
class DefaultProvider final : public ConfigProvider {
  public:
    /**
     * @brief Gets the name of this config layer.
     *
     * @return The name "DefaultProvider"
     */
    [[nodiscard]] std::string name() const override;

    [[nodiscard]] LayerValue<std::size_t>
    num_tiles_primary(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t>
    num_tiles_total(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t>
    num_metatiles_primary(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t>
    num_metatiles_total(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t>
    num_pals_primary(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t> num_pals_total(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t>
    max_map_data_size(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t>
    num_tiles_per_metatile(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<Rgba32>
    extrinsic_transparency(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<bool> verify_checksums(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<bool> patch_build_enabled(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<TilesPalMode>
    tiles_pal_mode(ConfigScopeType type, const std::string &scope) const override;
};

} // namespace porytiles2