#pragma once

#include <string>

#include "porytiles2/infra/config/tiles_pal_mode.hpp"
#include "porytiles2/xcut/config/config_scope_type.hpp"
#include "porytiles2/xcut/config/config_value.hpp"
#include "porytiles2/xcut/config/config_validators.hpp"
#include "porytiles2/utilities/result/chainable_result.hpp"

namespace porytiles2 {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate using
 * Scripts/generate_config.py.
 */

/**
 * @brief Interface that defines a complete infra layer configuration.
 */
class InfraConfig {
  public:
    virtual ~InfraConfig() = default;

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<TilesPalMode>>
    tiles_pal_mode(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = tiles_pal_mode_validated(type, scope);
        return validated_val;
    }

  protected:

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<TilesPalMode>>
    tiles_pal_mode_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = tiles_pal_mode_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<TilesPalMode>>
    tiles_pal_mode_raw(ConfigScopeType type, const std::string &scope) const = 0;
};

} // namespace porytiles2