#pragma once

#include <string>

#include "porytiles2/infra/config/tiles_pal_mode.hpp"
#include "porytiles2/xcut/config/config_value.hpp"
#include "porytiles2/xcut/config/config_validators.hpp"
#include "porytiles2/xcut/result/chainable_result.hpp"

namespace porytiles2 {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate using
 * Scripts/generate_config.py.
 */

/**
 * @brief Interface that defines a complete infra layer configuration.
 *
 * @details
 * The infra layer operates with this interface - it doesn't need to worry about implementation. Every config value is
 * either virtual (i.e., comes from the user) or defined in terms of other virtual values.
 */
class InfraConfig {
  public:
    virtual ~InfraConfig() = default;

    // Public method with validation
    [[nodiscard]] ChainableResult<ConfigValue<TilesPalMode>>
    tiles_pal_mode(const std::string &tileset) const
    {
        auto raw_val = tiles_pal_mode_raw(tileset);
        return raw_val;
    }

  protected:

    // Protected virtual method that fetches raw value from provider
    [[nodiscard]] virtual ChainableResult<ConfigValue<TilesPalMode>>
    tiles_pal_mode_raw(const std::string &tileset) const = 0;
};

} // namespace porytiles2