#pragma once

#include <string>

#include "porytiles2/utilities/result/chainable_result.hpp"
#include "porytiles2/xcut/config/config_scope_type.hpp"
#include "porytiles2/xcut/config/config_validators.hpp"
#include "porytiles2/xcut/config/config_value.hpp"

namespace porytiles2 {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate using
 * Scripts/generate_config.py.
 */

/**
 * @brief Interface that defines a complete infra layer configuration.
 */
class InfraConfig {
  public:
    virtual ~InfraConfig() = default;

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::string>>
    tileset_paths_primary_src(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = tileset_paths_primary_src_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::string>>
    tileset_paths_primary_bin(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = tileset_paths_primary_bin_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::string>>
    tileset_paths_secondary_src(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = tileset_paths_secondary_src_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::string>>
    tileset_paths_secondary_bin(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = tileset_paths_secondary_bin_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<bool>>
    tileset_animations_wire_anim_code(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = tileset_animations_wire_anim_code_validated(type, scope);
        return validated_val;
    }


  protected:

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_primary_src_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = tileset_paths_primary_src_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_primary_src_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_primary_bin_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = tileset_paths_primary_bin_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_primary_bin_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_secondary_src_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = tileset_paths_secondary_src_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_secondary_src_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_secondary_bin_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = tileset_paths_secondary_bin_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_secondary_bin_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<bool>>
    tileset_animations_wire_anim_code_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = tileset_animations_wire_anim_code_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<bool>>
    tileset_animations_wire_anim_code_raw(ConfigScopeType type, const std::string &scope) const = 0;

};

} // namespace porytiles2