#pragma once

#include <any>
#include <functional>
#include <map>
#include <memory>
#include <unordered_map>
#include <vector>

#include "gsl/pointers"

#include "porytiles2/app/config/app_config.hpp"
#include "porytiles2/domain/config/domain_config.hpp"
#include "porytiles2/domain/models/rgba32.hpp"
#include "porytiles2/infra/config/config_provider.hpp"
#include "porytiles2/infra/config/infra_config.hpp"
#include "porytiles2/infra/config/tiles_pal_mode.hpp"
#include "porytiles2/utilities/text/plain_text_formatter.hpp"
#include "porytiles2/utilities/text/text_formatter.hpp"
#include "porytiles2/xcut/config/config_value.hpp"
#include "porytiles2/xcut/result/chainable_result.hpp"

namespace porytiles2 {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate using
 * Scripts/generate_config.py.
 */

/*
 * TODO: implement a better system for configuration validation. Right now, we rely on each ConfigProvider
 * implementation to provide validation internally before returning LayerValue::invalid. However, this means certain
 * config validations will have to be repeated multiple times in every single ConfigProvider impl. This is fine for some
 * validation. E.g. CommandLineProvider and YamlProvider might have different format validation needs when parsing from
 * source. Hence they may have different parse_x implementations. However, some values need generic validation, e.g.
 * num_pals_primary must be less than num_pals_total.
 */

/**
 * @brief A Config implementation that lazily pulls a config value by consulting multiple priority-ordered backing
 * \link ConfigProvider ConfigProviders \endlink.
 *
 * @details
 * LazyLayeredConfig provides the following functionality:
 * - fetches the value from the highest priority layer, lazily (i.e., only loads upon first request, then caches)
 * - tracks the provenance of the value (e.g., did it come from tileset TOML? environment? default value?)
 * - hard panics if no value exists, this is a programmer error (programmer should at least provide a default layer)
 * - provides a way to dump itself for debugging purposes
 */
class LazyLayeredConfig final : public DomainConfig, public AppConfig, public InfraConfig {
  public:
    /**
     * @brief Constructs a LazyLayeredConfig with a list of \link ConfigProvider ConfigProviders \endlink in priority
     * order, highest to lowest.
     *
     * @details
     * The LazyLayeredConfig will attempt to resolve configuration values by traversing the provided list of \link
     * ConfigProvider ConfigProviders \endlink in order. That is, it will consult the first provider in the list first,
     * and the next provider only if the first does not supply the config value. And so on. It is the programmer's
     * responsibility to provide a default layer as the final provider in the list. If any config value resolution call
     * chain reaches the end of the provider list without finding a value, the LazyLayeredConfig will terminate with a
     * panic.
     *
     * @param format A pointer to the TextFormatter to use
     * @param providers The list of providers in priority order
     */
    explicit LazyLayeredConfig(
        gsl::not_null<TextFormatter *> format, std::vector<std::unique_ptr<ConfigProvider>> &&providers)
        : format_{format}, providers_{std::move(providers)}
    {
    }

    /**
     * @brief Constructs a LazyLayeredConfig with a default PlainTextFormatter.
     *
     * @details
     * This constructor creates an internally owned PlainTextFormatter instance and uses it for formatting. The
     * LazyLayeredConfig will attempt to resolve configuration values by traversing the provided list of \link
     * ConfigProvider ConfigProviders \endlink in order. It is the programmer's responsibility to provide a default
     * layer as the final provider in the list.
     *
     * @param providers The list of providers in priority order
     */
    explicit LazyLayeredConfig(std::vector<std::unique_ptr<ConfigProvider>> &&providers)
        : owned_format_{std::make_unique<PlainTextFormatter>()}, format_{owned_format_.get()},
          providers_{std::move(providers)}
    {
    }

  protected:
    /*
     * Domain Config Raw Methods
     */

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_tiles_primary_raw(const std::string &tileset) const override;

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_tiles_total_raw(const std::string &tileset) const override;

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_metatiles_primary_raw(const std::string &tileset) const override;

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_metatiles_total_raw(const std::string &tileset) const override;

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_pals_primary_raw(const std::string &tileset) const override;

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_pals_total_raw(const std::string &tileset) const override;

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    max_map_data_size_raw(const std::string &tileset) const override;

    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_tiles_per_metatile_raw(const std::string &tileset) const override;

    [[nodiscard]] ChainableResult<ConfigValue<Rgba32>>
    extrinsic_transparency_raw(const std::string &tileset) const override;

    [[nodiscard]] ChainableResult<ConfigValue<bool>>
    patch_build_enabled_raw(const std::string &tileset) const override;

    /*
     * App Config Raw Methods
     */

    /*
     * Infra Config Raw Methods
     */
    [[nodiscard]] ChainableResult<ConfigValue<TilesPalMode>> tiles_pal_mode_raw(const std::string &tileset) const override;

  public:

    /*
     * LazyLayeredConfig Specific Functionality
     */

    /**
     * @brief Dumps the current state of the config for debugging purposes.
     *
     * @details
     * Returns a string showing each cached config key, actual value, and source layer name with metadata. Only cached
     * values are shown (values that have been requested at least once).
     *
     * @return A formatted string representation of the config state
     */
    [[nodiscard]] std::string dump() const;

    /**
     * @brief Forces all configuration values to be cached immediately for all known tilesets.
     *
     * @details
     * This function eagerly evaluates and caches all configuration values by calling each config method. This is useful
     * for warming up the cache before performance-critical operations or for validating all config values at startup.
     * The function requires a list of tileset names to evaluate tileset-specific configuration values.
     *
     * @param tileset_names List of tileset names for which to evaluate the configuration
     */
    void warmup_cache(const std::vector<std::string> &tileset_names) const;

  private:
    std::unique_ptr<TextFormatter> owned_format_; // Optional owned formatter (when using default ctor)
    TextFormatter *format_;                       // Non-owning pointer to formatter
    // Providers in priority order (highest first)
    std::vector<std::unique_ptr<ConfigProvider>> providers_;

    // Config value cache
    mutable std::map<std::string, std::any> cache_;
    // Config value as string for debug printing
    mutable std::unordered_map<std::string, std::string> cache_value_strings_;

    // Config source and source_details
    mutable std::unordered_map<std::string, std::string> source_;
    mutable std::unordered_map<std::string, std::vector<std::string>> source_details_;

    /**
     * @brief Resolves config values using the common caching and provider iteration pattern.
     *
     * @tparam T The type of the config value
     * @param cache_key The key to use for caching this value (also used for value name)
     * @param provider_call Function that calls the appropriate method on a ConfigProvider
     * @return A ChainableResult containing either the resolved config value or an error
     */
    template <typename T>
    ChainableResult<ConfigValue<T>> resolve_config_value(
        const std::string &cache_key, std::function<LayerValue<T>(const ConfigProvider &)> provider_call) const;
};

} // namespace porytiles2