#pragma once

#include <string>
#include <unordered_set>

namespace porytiles2 {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate using
 * Scripts/generate_config.py.
 */

/**
 * @brief Set of valid YAML configuration paths.
 *
 * @details
 * This set contains all valid dot-separated paths that can appear in porytiles.yaml configuration files. Both leaf
 * paths (e.g., "fieldmap.num_tiles_in_primary") and intermediate paths (e.g., "fieldmap") are included.
 *
 * This is auto-generated from config_schema.yaml - do not edit directly.
 */
inline const std::unordered_set<std::string> valid_yaml_paths = {
    "fieldmap",
    "fieldmap.max_map_data_size",
    "fieldmap.num_metatiles_in_primary",
    "fieldmap.num_metatiles_total",
    "fieldmap.num_pals_in_primary",
    "fieldmap.num_pals_total",
    "fieldmap.num_tiles_in_primary",
    "fieldmap.num_tiles_per_metatile",
    "fieldmap.num_tiles_total",
    "tileset",
    "tileset.animations",
    "tileset.animations.key_frame_resolution_strategy",
    "tileset.animations.palette_resolution_strategy",
    "tileset.animations.wire_anim_code",
    "tileset.extrinsic_transparency",
    "tileset.palettes",
    "tileset.palettes.edit_mode",
    "tileset.palettes.packing",
    "tileset.palettes.packing.hints",
    "tileset.palettes.packing.hints_enabled",
    "tileset.paths",
    "tileset.paths.primary",
    "tileset.paths.primary.bin",
    "tileset.paths.primary.src",
    "tileset.paths.secondary",
    "tileset.paths.secondary.bin",
    "tileset.paths.secondary.src",
    "tileset.tiles",
    "tileset.tiles.edit_mode",
    "tileset.tiles.palette_mode",
    "verify_checksums",
};

} // namespace porytiles2