#pragma once

#include <string>
#include <unordered_set>

namespace porytiles2 {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate using
 * Scripts/generate_config.py.
 */

/**
 * @brief Set of valid YAML configuration paths.
 *
 * @details
 * This set contains all valid dot-separated paths that can appear in porytiles.yaml configuration files. Both leaf
 * paths (e.g., "fieldmap.num_tiles_in_primary") and intermediate paths (e.g., "fieldmap") are included.
 *
 * This is auto-generated from config_schema.yaml - do not edit directly.
 */
inline const std::unordered_set<std::string> valid_yaml_paths = {
    "extrinsic_transparency",
    "fieldmap",
    "fieldmap.max_map_data_size",
    "fieldmap.num_metatiles_in_primary",
    "fieldmap.num_metatiles_total",
    "fieldmap.num_pals_in_primary",
    "fieldmap.num_pals_total",
    "fieldmap.num_tiles_in_primary",
    "fieldmap.num_tiles_per_metatile",
    "fieldmap.num_tiles_total",
    "patch",
    "patch.enabled",
    "patch.palettes",
    "patch.tiles",
    "tiles_pal_mode",
    "verify_checksums",
};

} // namespace porytiles2