/*
Copyright © 2025 grunt-lucas grunt.lucas@yahoo.com
*/

package diagnostics

import (
	"fmt"
	"os"
	"strconv"
	"strings"
	"text/template"

	"github.com/fatih/color"
)

// Diagnostic represents a diagnostic message, including its template, level,
// message, and associated notes. An actual Diagnostic is generated by the
// DiagnosticEngine using the template as well the various user defined
// diagnostic parameters (e.g. warnings-as-errors, specific warning disables,
// etc.).
type Diagnostic struct {
	// id       int
	template DiagnosticTemplate
	level    DiagnosticLevel
	message  string
}

// DiagnosticConsumer provides a flexible interface so that users of the
// DiagnosticEngine can configure exactly how they want generated diagnostics
// to be processed.
type DiagnosticConsumer interface {
	ConsumeDiagnostic(diag Diagnostic)
}

// StderrConsumer is a DiagnosticConsumer that processes diagnostics by writing
// them to standard error. This is the default DiagnosticConsumer for Porytiles
// jobs.
type StderrConsumer struct{}

func (s StderrConsumer) ConsumeDiagnostic(diag Diagnostic) {
	// TODO : implement me
	switch diag.level {
	case Ignored:
		// Do nothing for ignored diagnostics
	case Note:
		cyan := color.New(color.FgCyan, color.Bold).SprintFunc()
		fmt.Fprintf(os.Stderr, "%s %s\n", cyan("note:"), diag.message)
	case Remark:
		green := color.New(color.FgGreen, color.Bold).SprintFunc()
		fmt.Fprintf(os.Stderr, "%s %s\n", green("remark:"), diag.message)
	case Warning:
		magenta := color.New(color.FgMagenta, color.Bold).SprintFunc()
		fmt.Fprintf(os.Stderr, "%s %s\n", magenta("warning:"), diag.message)
	case Error:
		red := color.New(color.FgRed, color.Bold).SprintFunc()
		fmt.Fprintf(os.Stderr, "%s %s\n", red("error:"), diag.message)
	case Fatal:
		red := color.New(color.FgRed, color.Bold).SprintFunc()
		fmt.Fprintf(os.Stderr, "%s %s\n", red("fatal error:"), diag.message)
		os.Exit(1)
	default:
		// Handle unexpected diagnostic levels
		PorytilesInternalPanic("unexpected Diagnostic level: " + strconv.Itoa(int(diag.level)))
	}
}

// DevNullConsumer is a DiagnosticConsumer that ignores all supplied
// diagnostics. It may be useful for testing purposes.
type DevNullConsumer struct{}

func (s DevNullConsumer) ConsumeDiagnostic(diag Diagnostic) {
	// explicitly do nothing
}

// DiagnosticEngine coordinates the generation and consumption of diagnostic
// messages. It manages settings for enabling, disabling, treating warnings as
// errors, etc. It uses a DiagnosticConsumer to process the generated
// diagnostics according to the engine user's preference.
type DiagnosticEngine struct {
	consumer               DiagnosticConsumer
	allWarningsEnabled     bool
	allWarningsDisabled    bool
	allWarningsAsErrors    bool
	userEnabledDiagnostics map[string]bool
}

// SetConsumer assigns the provided DiagnosticConsumer to the DiagnosticEngine.
func (engine *DiagnosticEngine) SetConsumer(consumer DiagnosticConsumer) {
	engine.consumer = consumer
}

func (engine *DiagnosticEngine) EnableDiagnostic(diagName string) {
	engine.userEnabledDiagnostics[diagName] = true
}

func (engine *DiagnosticEngine) DisableDiagnostic(diagName string) {
	engine.userEnabledDiagnostics[diagName] = false
}

// Report generates and consumes a diagnostic message using the provided name
// and message parameters. Report will consume the diagnostic using the
// DiagnosticEngine's configured DiagnosticConsumer. It will also compute the
// diagnostic's visibility and level by combining the default level with the
// various diagnostic parameters provided by the user.
func (engine *DiagnosticEngine) Report(diagName string, messageParams map[string]string) {
	// If this diagnostic is not enabled, exit now
	if !engine.diagnosticIsEnabled(diagName) {
		return
	}

	// Fetch the relevant diagnostic template
	diagTempl, ok := diagNameToTemplate[diagName]
	if !ok {
		PorytilesInternalPanic("diagnostic with name `" + diagName + "' not found")
	}

	// Format the diagnostic message
	var messageTempl = template.Must(template.New("message").Parse(diagTempl.MessageTemplate))
	var formattedMessage = &strings.Builder{}
	err := messageTempl.Execute(formattedMessage, messageParams)
	if err != nil {
		PorytilesInternalPanic("failed to format diagnostic message: " + err.Error())
	}

	// Format any diagnostic notes
	var formattedNotes []string
	for _, note := range diagTempl.NoteTemplates {
		var noteTempl = template.Must(template.New("note").Parse(note))
		var formattedNote = &strings.Builder{}
		err = noteTempl.Execute(formattedNote, messageParams)
		if err != nil {
			PorytilesInternalPanic("failed to format diagnostic note: " + err.Error())
		}
		formattedNotes = append(formattedNotes, formattedNote.String())
	}

	// Issue the parent diagnostic
	diagnostic := Diagnostic{
		diagTempl, diagTempl.DefaultLevel, formattedMessage.String(),
	}
	engine.consumer.ConsumeDiagnostic(diagnostic)

	// Issue separate diagnostics for any associated notes
	for _, note := range formattedNotes {
		// TODO : correct way to handle the diagTempl here
		noteDiagnostic := Diagnostic{diagTempl, Note, note}
		engine.consumer.ConsumeDiagnostic(noteDiagnostic)
	}
}

func (engine *DiagnosticEngine) diagnosticIsEnabled(diagName string) bool {
	/*
	 * TODO : here we need to actually determine the correct level according to the preference order.
	 * i.e. explicitly enabled/disabled takes precedence over globally enabled/disabled
	 */
	return false
}
