/*
Copyright © 2025 grunt-lucas grunt.lucas@yahoo.com
*/

package diagnostics

import (
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/fatih/color"
)

// InFlightDiagnostic represents a diagnostic message, including its template, level, message, and
// associated notes. An actual InFlightDiagnostic is generated by the DiagnosticEngine by combining
// the template with context from the various user defined diagnostic parameters (e.g. warnings as
// errors, specific warning disables, etc.).
type InFlightDiagnostic struct {
	// id       int
	template DiagnosticTemplate
	level    DiagnosticLevel
	message  string
}

// DiagnosticConsumer provides a flexible interface so that users of the DiagnosticEngine can
// configure exactly how they want the engine to process an InFlightDiagnostic.
type DiagnosticConsumer interface {
	ConsumeDiagnostic(diag InFlightDiagnostic)
}

// StderrConsumer is a DiagnosticConsumer that processes diagnostics by writing them to standard
// error. This is the default DiagnosticConsumer for Porytiles jobs.
type StderrConsumer struct{}

func (s StderrConsumer) ConsumeDiagnostic(diag InFlightDiagnostic) {
	// TODO : fully implement me
	// TODO : should we print newlines between each diagnostic?
	switch diag.level {
	case Ignored:
		// Do nothing for ignored diagnostics
	case Note:
		cyan := color.New(color.FgCyan, color.Bold).SprintFunc()
		fmt.Fprintf(os.Stderr, "%s%s\n", cyan(string(Note)+": "), diag.message)
	case Remark:
		green := color.New(color.FgGreen, color.Bold).SprintFunc()
		fmt.Fprintf(os.Stderr, "%s%s\n", green(string(Remark)+": "), diag.message)
	case Warning:
		magenta := color.New(color.FgMagenta, color.Bold).SprintFunc()
		fmt.Fprintf(os.Stderr, "%s%s\n", magenta(string(Warning)+": "), diag.message)
	case Error:
		red := color.New(color.FgRed, color.Bold).SprintFunc()
		fmt.Fprintf(os.Stderr, "%s%s\n", red(string(Error)+": "), diag.message)
	case Fatal:
		red := color.New(color.FgRed, color.Bold).SprintFunc()
		fmt.Fprintf(os.Stderr, "%s%s\n", red(string(Fatal)+": "), diag.message)
		os.Exit(1)
	default:
		// Handle unexpected diagnostic levels
		PorytilesInternalPanic("unexpected InFlightDiagnostic level: " + string(diag.level))
	}
}

// DevNullConsumer is a DiagnosticConsumer that ignores all supplied diagnostics. It may be useful
// for testing purposes.
type DevNullConsumer struct{}

func (s DevNullConsumer) ConsumeDiagnostic(diag InFlightDiagnostic) {
	// explicitly do nothing
}

// SliceConsumer is a DiagnosticConsumer that writes all diagnostics to a slice buffer. They can
// then be read back later in the order in which they were written. It may be useful for testing
// purposes.
type SliceConsumer struct {
	messages []string
}

func (s *SliceConsumer) ConsumeDiagnostic(diag InFlightDiagnostic) {
	switch diag.level {
	case Ignored:
		s.messages = append(s.messages, string(Ignored)+": "+diag.message)
	case Note:
		s.messages = append(s.messages, string(Note)+": "+diag.message)
	case Remark:
		s.messages = append(s.messages, string(Remark)+": "+diag.message)
	case Warning:
		s.messages = append(s.messages, string(Warning)+": "+diag.message)
	case Error:
		s.messages = append(s.messages, string(Error)+": "+diag.message)
	case Fatal:
		s.messages = append(s.messages, string(Fatal)+": "+diag.message)
	default:
		// Handle unexpected diagnostic levels
		PorytilesInternalPanic("unexpected InFlightDiagnostic level: " + string(diag.level))
	}
}

func (s *SliceConsumer) Len() int {
	return len(s.messages)
}

func (s *SliceConsumer) Pop() string {
	message := s.messages[0]
	s.messages = s.messages[1:]
	return message
}

// DiagnosticEngine coordinates the generation and consumption of diagnostic messages. It manages
// settings for enabling, disabling, treating warnings as errors, etc. It uses a DiagnosticConsumer
// to process the generated diagnostics according to the engine user's preference.
type DiagnosticEngine struct {
	consumer                     DiagnosticConsumer
	allWarningsEnabled           bool
	allWarningsDisabled          bool
	allWarningsAsErrors          bool
	explicitlyEnabledDiagnostics map[string]bool
	diagnosticLevelOverrides     map[string]DiagnosticLevel
}

func NewDiagnosticEngine() *DiagnosticEngine {
	return &DiagnosticEngine{
		explicitlyEnabledDiagnostics: make(map[string]bool),
		diagnosticLevelOverrides:     make(map[string]DiagnosticLevel),
	}
}

// SetConsumer assigns the provided DiagnosticConsumer to the DiagnosticEngine.
func (engine *DiagnosticEngine) SetConsumer(consumer DiagnosticConsumer) {
	engine.consumer = consumer
}

func (engine *DiagnosticEngine) EnableDiagnostic(diagName string) {
	engine.explicitlyEnabledDiagnostics[diagName] = true
}

func (engine *DiagnosticEngine) DisableDiagnostic(diagName string) {
	engine.explicitlyEnabledDiagnostics[diagName] = false
}

// Report generates and consumes a diagnostic message using the provided name and message
// parameters. Report will consume the diagnostic using the DiagnosticEngine's configured
// DiagnosticConsumer. It will also compute the diagnostic's visibility and level by combining the
// default level with the various diagnostic parameters provided by the user.
func (engine *DiagnosticEngine) Report(diagName string, messageParams map[string]string) {
	// If this diagnostic is not enabled, exit now
	if !engine.diagnosticIsEnabled(diagName) {
		return
	}

	// Fetch the relevant diagnostic template
	diagTempl := getDiagnosticTemplate(diagName)

	// Format the diagnostic message
	var messageTempl = template.Must(template.New("message").Parse(diagTempl.MessageTemplate))
	var formattedMessage = &strings.Builder{}
	err := messageTempl.Execute(formattedMessage, messageParams)
	if err != nil {
		PorytilesInternalPanic("failed to format diagnostic message: " + err.Error())
	}

	// Format any diagnostic notes
	var formattedNotes []string
	for _, note := range diagTempl.NoteTemplates {
		var noteTempl = template.Must(template.New("note").Parse(note))
		var formattedNote = &strings.Builder{}
		err = noteTempl.Execute(formattedNote, messageParams)
		if err != nil {
			PorytilesInternalPanic("failed to format diagnostic note: " + err.Error())
		}
		formattedNotes = append(formattedNotes, formattedNote.String())
	}

	// Issue the parent diagnostic
	diagLevel := engine.computeDiagnosticLevel(diagName)
	diagnostic := InFlightDiagnostic{
		diagTempl, diagLevel, formattedMessage.String(),
	}
	// TODO : should we supress consumption if lots of diagnostics of the same
	// type were issued? E.g. clang will say something like:
	//    129 similar warnings suppressed.
	engine.consumer.ConsumeDiagnostic(diagnostic)

	// Issue separate diagnostics for any associated notes
	for _, note := range formattedNotes {
		// TODO : correct way to handle the diagTempl here
		noteDiagnostic := InFlightDiagnostic{diagTempl, Note, note}
		engine.consumer.ConsumeDiagnostic(noteDiagnostic)
	}
}

func (engine *DiagnosticEngine) computeDiagnosticLevel(diagName string) DiagnosticLevel {
	diagTempl := getDiagnosticTemplate(diagName)
	// TODO : actually compute the level

	// Default to the default level from the template
	return diagTempl.DefaultLevel
}

func (engine *DiagnosticEngine) diagnosticIsEnabled(diagName string) bool {
	diagTempl := getDiagnosticTemplate(diagName)
	// TODO : finish implementing logic

	// Highest precedence is an explicitly enabled or disabled diagnostic. If the diagnostic is not
	// present in this map, that means it was not explicitly set by the user, so its enablement will
	// fall back to either a global setting or the template default.
	enabled, ok := engine.explicitlyEnabledDiagnostics[diagName]
	if ok {
		return enabled
	}

	// Next highest precedence: global warnings enable or disable

	// Lowest precedence is the DefaultEnabled setting from the template
	return diagTempl.DefaultEnabled
}
