#pragma once

#include <string>

#include "porytiles2/app/config/primary_pairing_mode.hpp"
#include "porytiles2/utilities/result/chainable_result.hpp"
#include "porytiles2/xcut/config/config_scope_type.hpp"
#include "porytiles2/xcut/config/config_value.hpp"
#include "porytiles2/xcut/config/xcut_config_validators.hpp"

namespace porytiles2 {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate via:
 *
 *   uv run Scripts/generate_config.py
 */

/**
 * @brief Interface that defines a complete app layer configuration.
 */
class AppConfig {
  public:
    virtual ~AppConfig() = default;

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<bool>>
    verify_checksums(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = verify_checksums_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<PrimaryPairingMode>>
    primary_pairing_mode(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = primary_pairing_mode_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::vector<std::string>>>
    primary_pairing_partners(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = primary_pairing_partners_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_warnings_exclude(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = diagnostic_warnings_exclude_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_warnings_include(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = diagnostic_warnings_include_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_remarks_exclude(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = diagnostic_remarks_exclude_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_remarks_include(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = diagnostic_remarks_include_validated(type, scope);
        return validated_val;
    }

  protected:
    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<bool>>
    verify_checksums_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = verify_checksums_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<bool>>
    verify_checksums_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<PrimaryPairingMode>>
    primary_pairing_mode_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = primary_pairing_mode_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<PrimaryPairingMode>>
    primary_pairing_mode_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::vector<std::string>>>
    primary_pairing_partners_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = primary_pairing_partners_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::vector<std::string>>>
    primary_pairing_partners_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_warnings_exclude_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = diagnostic_warnings_exclude_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_warnings_exclude_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_warnings_include_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = diagnostic_warnings_include_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_warnings_include_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_remarks_exclude_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = diagnostic_remarks_exclude_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_remarks_exclude_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_remarks_include_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = diagnostic_remarks_include_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::vector<std::string>>>
    diagnostic_remarks_include_raw(ConfigScopeType type, const std::string &scope) const = 0;
};

} // namespace porytiles2