name: Install GCC Linux
description: Installs GCC compiler for Linux platforms
runs:
  using: composite
  steps:
    - name: Install gcc for Linux
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt update
        sudo apt install gcc-14 g++-14 -y
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
