#pragma once

#include <string>

#include "porytiles/infra/cli/cli_option_storage.hpp"
#include "porytiles/infra/config/config_provider.hpp"
#include "porytiles/infra/config/layer_value.hpp"
#include "porytiles/xcut/config/config_scope_type.hpp"

namespace porytiles {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate via:
 *
 *   uv run scripts/generate_config.py
 */

/**
 * @brief ConfigProvider implementation that reads values from CLI options.
 *
 * @details
 * CliOptionProvider wraps a CliOptionStorage struct and implements the ConfigProvider interface.
 * For each config value, it returns LayerValue::valid() if the CLI option was provided, or
 * LayerValue::not_provided() if it was not. This provider should be first in the provider chain
 * to give CLI options the highest priority.
 */
class CliOptionProvider final : public ConfigProvider {
  public:
    explicit CliOptionProvider(const CliOptionStorage &storage);

    [[nodiscard]] std::string name() const override;

    /*
     * Domain Config
     */
    [[nodiscard]] LayerValue<std::size_t> num_tiles_in_primary(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t> num_tiles_total(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t> num_metatiles_in_primary(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t> num_metatiles_total(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t> num_pals_in_primary(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t> num_pals_total(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t> max_map_data_size(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t> num_tiles_per_metatile(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<Rgba32> extrinsic_transparency(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<ArtifactEditMode> tiles_edit_mode(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<ArtifactEditMode> pals_edit_mode(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<bool> pal_hints_enabled(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::vector<PaletteHint>> pal_hints(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<PackingStrategyType> packing_strategy(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<PackingStrategyParams> packing_strategy_params(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<TileSharingPacking> tile_sharing_packing(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<TileSharingAlignment> tile_sharing_alignment(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<TilesPalMode> tiles_pal_mode(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<AnimPalResolutionStrategy> global_anim_pal_resolution_strategy(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<AnimKeyFrameResolutionStrategy> global_anim_key_frame_resolution_strategy(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<AnimMultiPalSubtileResolutionStrategy> global_anim_multi_pal_subtile_resolution_strategy(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<FrameLinking> global_frame_linking(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<PerAnimOverrides> per_anim_overrides(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<bool> cross_tileset_anim_linking(ConfigScopeType type, const std::string &scope) const override;

    /*
     * App Config
     */
    [[nodiscard]] LayerValue<bool> verify_checksums(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<PrimaryPairingMode> primary_pairing_mode(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::vector<std::string>> primary_pairing_partners(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::vector<std::string>> diagnostic_warnings_exclude(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::vector<std::string>> diagnostic_warnings_include(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::vector<std::string>> diagnostic_remarks_exclude(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::vector<std::string>> diagnostic_remarks_include(ConfigScopeType type, const std::string &scope) const override;

    /*
     * Infra Config
     */
    [[nodiscard]] LayerValue<std::string> tileset_paths_primary_src(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::string> tileset_paths_primary_bin(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::string> tileset_paths_secondary_src(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::string> tileset_paths_secondary_bin(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t> metatile_attr_size(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<bool> tileset_animations_wire_anim_code(ConfigScopeType type, const std::string &scope) const override;

  private:
    const CliOptionStorage &storage_;
};

} // namespace porytiles