#pragma once

#include <string>

#include "porytiles/app/config/primary_pairing_mode.hpp"
#include "porytiles/domain/config/anim_key_frame_resolution_strategy.hpp"
#include "porytiles/domain/config/anim_palette_resolution_strategy.hpp"
#include "porytiles/domain/config/artifact_edit_mode.hpp"
#include "porytiles/domain/config/metatile_attribute_field_definition.hpp"
#include "porytiles/domain/config/packing_strategy_params.hpp"
#include "porytiles/domain/config/packing_strategy_type.hpp"
#include "porytiles/domain/config/per_anim_overrides.hpp"
#include "porytiles/domain/config/role_pin_definition.hpp"
#include "porytiles/domain/config/tile_sharing_alignment.hpp"
#include "porytiles/domain/config/tile_sharing_packing.hpp"
#include "porytiles/domain/config/tiles_palette_mode.hpp"
#include "porytiles/domain/models/rgba32.hpp"
#include "porytiles/domain/packing/models/palette_hint.hpp"
#include "porytiles/infra/config/layer_value.hpp"
#include "porytiles/infra/config/optional_size_format.hpp"
#include "porytiles/xcut/config/config_scope_type.hpp"

namespace porytiles {

// NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
// To add new config values or make other changes, edit config_schema.yaml and regenerate via:
//
//   uv run scripts/generate_config.py

/// @brief An interface which config implementations can use to load config values.
///
/// @details
/// ConfigProvider is basically just a copy of all three layer configs (domain, app, infra) but with LayerValue return
/// types. ConfigProvider provides a default implementation for each method which returns an empty LayerValue. This is
/// helpful for ConfigProvider implementations, since often the implementations may not want to provide a value for
/// every config param.
class ConfigProvider {
  public:
    virtual ~ConfigProvider() = default;

    /// @brief Gets the name of this ConfigProvider, useful for diagnostic purposes.
    ///
    /// @return The name of this ConfigProvider
    [[nodiscard]] virtual std::string name() const = 0;

    // Domain Config

    [[nodiscard]] virtual LayerValue<std::size_t>
    num_tiles_in_primary(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<std::size_t> num_tiles_total(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<std::size_t>
    num_metatiles_in_primary(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<std::size_t>
    num_metatiles_total(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<std::size_t>
    num_palettes_in_primary(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<std::size_t>
    num_palettes_total(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<std::size_t>
    max_map_data_size(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<std::size_t>
    num_tiles_per_metatile(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<Rgba32>
    extrinsic_transparency(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<bool>
    ignore_triple_layer_content(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<ArtifactEditMode>
    tiles_edit_mode(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<ArtifactEditMode>
    palettes_edit_mode(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<bool> palette_hints_enabled(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<std::vector<PaletteHint>>
    palette_hints(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<PackingStrategyType>
    packing_strategy(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<PackingStrategyParams>
    packing_strategy_params(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<TileSharingPacking>
    tile_sharing_packing(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<TileSharingAlignment>
    tile_sharing_alignment(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<TilesPaletteMode>
    tiles_palette_mode(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<AnimPaletteResolutionStrategy>
    global_anim_palette_resolution_strategy(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<AnimKeyFrameResolutionStrategy>
    global_anim_key_frame_resolution_strategy(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<AnimMultiPaletteSubtileResolutionStrategy>
    global_anim_multi_palette_subtile_resolution_strategy(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<FrameLinking>
    global_frame_linking(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<PerAnimOverrides>
    per_anim_overrides(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<bool>
    cross_tileset_anim_linking(ConfigScopeType type, const std::string &scope) const;

    // App Config

    [[nodiscard]] virtual LayerValue<bool> verify_checksums(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<PrimaryPairingMode>
    primary_pairing_mode(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<std::vector<std::string>>
    primary_pairing_partners(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<std::vector<std::string>>
    diagnostic_warnings_exclude(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<std::vector<std::string>>
    diagnostic_warnings_include(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<std::vector<std::string>>
    diagnostic_remarks_exclude(ConfigScopeType type, const std::string &scope) const;

    [[nodiscard]] virtual LayerValue<std::vector<std::string>>
    diagnostic_remarks_include(ConfigScopeType type, const std::string &scope) const;

    // Infra Config
    [[nodiscard]] virtual LayerValue<std::string>
    tileset_paths_primary_src(ConfigScopeType type, const std::string &scope) const;
    [[nodiscard]] virtual LayerValue<std::string>
    tileset_paths_primary_bin(ConfigScopeType type, const std::string &scope) const;
    [[nodiscard]] virtual LayerValue<std::string>
    tileset_paths_secondary_src(ConfigScopeType type, const std::string &scope) const;
    [[nodiscard]] virtual LayerValue<std::string>
    tileset_paths_secondary_bin(ConfigScopeType type, const std::string &scope) const;
    [[nodiscard]] virtual LayerValue<std::optional<std::size_t>>
    metatile_attribute_size(ConfigScopeType type, const std::string &scope) const;
    [[nodiscard]] virtual LayerValue<std::optional<std::size_t>>
    metatile_attribute_declaration_size(ConfigScopeType type, const std::string &scope) const;
    [[nodiscard]] virtual LayerValue<MetatileAttributeFieldDefinitions>
    metatile_attribute_fields(ConfigScopeType type, const std::string &scope) const;
    [[nodiscard]] virtual LayerValue<MetatileAttributeFieldOverrides>
    metatile_attribute_field_overrides(ConfigScopeType type, const std::string &scope) const;
    [[nodiscard]] virtual LayerValue<RolePinDefinitions>
    role_pins(ConfigScopeType type, const std::string &scope) const;
    [[nodiscard]] virtual LayerValue<bool>
    tileset_animations_wire_anim_code(ConfigScopeType type, const std::string &scope) const;
};

} // namespace porytiles