#pragma once

#include <filesystem>
#include <memory>
#include <optional>
#include <string>

#include "gsl/pointers"

#include "porytiles/infra/config/config_provider.hpp"
#include "porytiles/utilities/c_parser/c_parser_facade.hpp"
#include "porytiles/utilities/text/plain_text_formatter.hpp"
#include "porytiles/utilities/text/text_formatter.hpp"

namespace porytiles {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate via:
 *
 *   uv run scripts/generate_config.py
 */

/**
 * @brief A ConfigProvider implementation that reads configuration values from #define directives in a header file.
 *
 * @details
 * HeaderDefineProvider parses a C/C++ header file looking for #define directives that correspond to configuration
 * values. This is useful for reading configuration from decompilation project headers like include/fieldmap.h.
 *
 * The provider uses a full C parser that supports:
 * - Simple integer literals: `#define NUM_TILES 512`
 * - Hexadecimal, octal, and binary literals: `#define FLAGS 0xFF`
 * - Arithmetic expressions: `#define SIZE (1 << 10)`
 * - Macro references: `#define TOTAL (PRIMARY + SECONDARY)`
 *
 * The header file is loaded lazily and cached for performance. If the file doesn't exist or a define is not found,
 * methods return LayerValue::not_provided(), allowing graceful fallback to other providers.
 */
class HeaderDefineProvider final : public ConfigProvider {
  public:
    /**
     * @brief Constructs a HeaderDefineProvider that reads #define values from a header file.
     *
     * @details
     * This constructor sets up the provider to read configuration values from #define directives in the specified
     * header file. The header file is loaded lazily when first accessed and cached for subsequent lookups.
     *
     * @param header_relative_path The path to the header file relative to project_root
     * @param format A pointer to the TextFormatter to use
     * @param project_root The root directory of the project
     */
    explicit HeaderDefineProvider(
        std::filesystem::path project_root,
        std::filesystem::path header_relative_path,
        gsl::not_null<const TextFormatter *> format)
        : format_{format}, project_root_{std::move(project_root)},
          header_relative_path_{std::move(header_relative_path)}
    {
        // CParserFacade is lazily initialized on first define lookup
    }

    /**
     * @brief Constructs a HeaderDefineProvider with a default PlainTextFormatter.
     *
     * @details
     * This constructor creates an internally owned PlainTextFormatter instance and uses it for formatting. The
     * HeaderDefineProvider will read configuration values from #define directives in the specified header file. The
     * header file is loaded lazily when first accessed and cached for subsequent lookups.
     *
     * @param project_root The root directory of the project
     * @param header_relative_path The path to the header file relative to project_root
     */
    explicit HeaderDefineProvider(std::filesystem::path project_root, std::filesystem::path header_relative_path)
        : owned_format_{std::make_unique<PlainTextFormatter>()}, format_{owned_format_.get()},
          project_root_{std::move(project_root)}, header_relative_path_{std::move(header_relative_path)}
    {
        // CParserFacade is lazily initialized on first define lookup
    }

    /**
     * @brief Gets the name of this config layer.
     *
     * @return The name "HeaderDefineProvider"
     */
    [[nodiscard]] std::string name() const override;

    [[nodiscard]] LayerValue<std::size_t>
    num_tiles_in_primary(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t>
    num_tiles_total(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t>
    num_metatiles_in_primary(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t>
    num_metatiles_total(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t>
    num_pals_in_primary(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t> num_pals_total(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t>
    max_map_data_size(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::size_t>
    num_tiles_per_metatile(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<Rgba32>
    extrinsic_transparency(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<ArtifactEditMode>
    tiles_edit_mode(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<ArtifactEditMode>
    pals_edit_mode(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<bool> pal_hints_enabled(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::vector<PaletteHint>>
    pal_hints(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<PackingStrategyType>
    packing_strategy(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<PackingStrategyParams>
    packing_strategy_params(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<TileSharingPacking>
    tile_sharing_packing(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<TileSharingAlignment>
    tile_sharing_alignment(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<TilesPalMode>
    tiles_pal_mode(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<AnimPalResolutionStrategy>
    global_anim_pal_resolution_strategy(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<AnimKeyFrameResolutionStrategy>
    global_anim_key_frame_resolution_strategy(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<AnimMultiPalSubtileResolutionStrategy>
    global_anim_multi_pal_subtile_resolution_strategy(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<FrameLinking>
    global_frame_linking(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<PerAnimOverrides>
    per_anim_overrides(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<bool>
    cross_tileset_anim_linking(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<bool> verify_checksums(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<PrimaryPairingMode>
    primary_pairing_mode(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::vector<std::string>>
    primary_pairing_partners(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::vector<std::string>>
    diagnostic_warnings_exclude(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::vector<std::string>>
    diagnostic_warnings_include(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::vector<std::string>>
    diagnostic_remarks_exclude(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::vector<std::string>>
    diagnostic_remarks_include(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::string>
    tileset_paths_primary_src(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::string>
    tileset_paths_primary_bin(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::string>
    tileset_paths_secondary_src(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::string>
    tileset_paths_secondary_bin(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<MetatileAttrFieldSpecs>
    metatile_attr_fields(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<MetatileAttrFieldOverrides>
    metatile_attr_field_overrides(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<bool>
    write_layer_type_column(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<FrlgAlternateMaskMode>
    use_frlg_alternate_masks(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::optional<std::uint32_t>>
    metatile_layer_type_mask(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<std::optional<std::uint32_t>>
    metatile_layer_type_mask_frlg(ConfigScopeType type, const std::string &scope) const override;

    [[nodiscard]] LayerValue<bool>
    tileset_animations_wire_anim_code(ConfigScopeType type, const std::string &scope) const override;

  private:
    std::unique_ptr<TextFormatter> owned_format_; // Optional owned formatter (when using default ctor)
    const TextFormatter *format_;                 // Non-owning pointer to formatter
    std::filesystem::path project_root_;
    std::filesystem::path header_relative_path_;
    mutable std::optional<CParserFacade> parser_driver_; // Lazy-initialized C parser
};

} // namespace porytiles