#pragma once

#include <memory>
#include <string>

#include "porytiles/utilities/result/chainable_result.hpp"
#include "porytiles/xcut/config/config_scope_type.hpp"
#include "porytiles/xcut/config/config_value.hpp"
#include "porytiles/xcut/config/xcut_config_validators.hpp"

namespace porytiles {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate via:
 *
 *   uv run scripts/generate_config.py
 */

class ConfigProvider; // forward declaration; full type is in infra/config/config_provider.hpp

/**
 * @brief Interface that defines a complete infra layer configuration.
 */
class InfraConfig {
  public:
    virtual ~InfraConfig() = default;

    /**
     * @brief Prepends a @c ConfigProvider to the provider chain at highest priority.
     *
     * @details
     * Allows use cases to layer an override provider on top of the user's configuration for operations that run the
     * compiler on Porytiles's own behalf. Implementations must invalidate any cached value resolutions so that
     * subsequent reads consult the newly prepended provider.
     *
     * @param provider The provider to prepend. Must be non-null.
     */
    virtual void add_provider(std::unique_ptr<ConfigProvider> provider) = 0;

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::string>>
    tileset_paths_primary_src(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = tileset_paths_primary_src_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::string>>
    tileset_paths_primary_bin(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = tileset_paths_primary_bin_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::string>>
    tileset_paths_secondary_src(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = tileset_paths_secondary_src_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::string>>
    tileset_paths_secondary_bin(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = tileset_paths_secondary_bin_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    metatile_attr_size(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = metatile_attr_size_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<bool>>
    tileset_animations_wire_anim_code(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = tileset_animations_wire_anim_code_validated(type, scope);
        return validated_val;
    }

  protected:
    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_primary_src_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = tileset_paths_primary_src_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_primary_src_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_primary_bin_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = tileset_paths_primary_bin_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_primary_bin_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_secondary_src_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = tileset_paths_secondary_src_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_secondary_src_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_secondary_bin_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = tileset_paths_secondary_bin_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::string>>
    tileset_paths_secondary_bin_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    metatile_attr_size_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = metatile_attr_size_raw(type, scope);
        // Apply validators in sequence
        if (raw_val.has_value()) {
            raw_val = size_t_val_two_or_four(raw_val.value());
        }
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    metatile_attr_size_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<bool>>
    tileset_animations_wire_anim_code_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = tileset_animations_wire_anim_code_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<bool>>
    tileset_animations_wire_anim_code_raw(ConfigScopeType type, const std::string &scope) const = 0;
};

} // namespace porytiles