#pragma once

#include <optional>
#include <string>

#include "porytiles/infra/config/config_provider.hpp"

namespace porytiles {

// NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
// To add new config values or make other changes, edit config_schema.yaml and regenerate via:
//
//   uv run scripts/generate_config.py

/// @brief A @c ConfigProvider that overrides selected config values for a single scope.
///
/// @details
/// Intended for internal use by use cases that run the compiler on Porytiles's own behalf, such as
/// @c ImportPrimaryTileset (which performs a locked-mode recompile to validate decompiled output)
/// and @c CreatePrimaryTileset (which needs to force the baked-in sample @c extrinsic_transparency).
///
/// Each setter marks a single config value as "overridden"; only values explicitly set via setter are
/// answered by this provider, and answers are scoped to the single @c (ConfigScopeType, scope) pair
/// supplied at construction. All other queries return @c LayerValue::not_provided() and fall through
/// to the next provider in the @c LazyLayeredConfig chain, so user configuration for non-overridden
/// values is preserved.
class OverrideConfigProvider final : public ConfigProvider {
  public:
    /// @brief Constructs an @c OverrideConfigProvider scoped to a single config scope.
    ///
    /// @param scope_type The scope type the overrides apply to (typically @c ConfigScopeType::tileset).
    /// @param scope The scope identifier (e.g. tileset name) the overrides apply to.
    /// @param source_info A short, human-readable description of the operation that is layering these
    ///   overrides (e.g. @c "import-tileset internal locked recompile"). Surfaced in the provenance
    ///   chain to make diagnostics traceable back to the internal override.
    OverrideConfigProvider(ConfigScopeType scope_type, std::string scope, std::string source_info);

    [[nodiscard]] std::string name() const override;

    void set_num_tiles_in_primary(std::size_t value);
    void set_num_tiles_total(std::size_t value);
    void set_num_metatiles_in_primary(std::size_t value);
    void set_num_metatiles_total(std::size_t value);
    void set_num_palettes_in_primary(std::size_t value);
    void set_num_palettes_total(std::size_t value);
    void set_max_map_data_size(std::size_t value);
    void set_num_tiles_per_metatile(std::size_t value);
    void set_extrinsic_transparency(Rgba32 value);
    void set_ignore_triple_layer_content(bool value);
    void set_tiles_edit_mode(ArtifactEditMode value);
    void set_palettes_edit_mode(ArtifactEditMode value);
    void set_palette_hints_enabled(bool value);
    void set_palette_hints(std::vector<PaletteHint> value);
    void set_packing_strategy(PackingStrategyType value);
    void set_packing_strategy_params(PackingStrategyParams value);
    void set_tile_sharing_packing(TileSharingPacking value);
    void set_tile_sharing_alignment(TileSharingAlignment value);
    void set_tiles_palette_mode(TilesPaletteMode value);
    void set_global_anim_palette_resolution_strategy(AnimPaletteResolutionStrategy value);
    void set_global_anim_key_frame_resolution_strategy(AnimKeyFrameResolutionStrategy value);
    void set_global_anim_multi_palette_subtile_resolution_strategy(AnimMultiPaletteSubtileResolutionStrategy value);
    void set_global_frame_linking(FrameLinking value);
    void set_per_anim_overrides(PerAnimOverrides value);
    void set_cross_tileset_anim_linking(bool value);
    void set_create_sample_anims(bool value);
    void set_verify_checksums(bool value);
    void set_primary_pairing_mode(PrimaryPairingMode value);
    void set_primary_pairing_partners(std::vector<std::string> value);
    void set_diagnostic_warnings_exclude(std::vector<std::string> value);
    void set_diagnostic_warnings_include(std::vector<std::string> value);
    void set_diagnostic_remarks_exclude(std::vector<std::string> value);
    void set_diagnostic_remarks_include(std::vector<std::string> value);
    void set_tileset_paths_primary_src(std::string value);
    void set_tileset_paths_primary_bin(std::string value);
    void set_tileset_paths_secondary_src(std::string value);
    void set_tileset_paths_secondary_bin(std::string value);
    void set_metatile_attribute_size(std::optional<std::size_t> value);
    void set_metatile_attribute_declaration_size(std::optional<std::size_t> value);
    void set_metatile_attribute_fields(MetatileAttributeFieldDefinitions value);
    void set_metatile_attribute_field_overrides(MetatileAttributeFieldOverrides value);
    void set_role_pins(RolePinDefinitions value);
    void set_tileset_animations_wire_anim_code(bool value);

    [[nodiscard]] LayerValue<std::size_t>
    num_tiles_in_primary(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t>
    num_tiles_total(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t>
    num_metatiles_in_primary(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t>
    num_metatiles_total(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t>
    num_palettes_in_primary(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t>
    num_palettes_total(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t>
    max_map_data_size(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::size_t>
    num_tiles_per_metatile(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<Rgba32>
    extrinsic_transparency(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<bool>
    ignore_triple_layer_content(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<ArtifactEditMode>
    tiles_edit_mode(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<ArtifactEditMode>
    palettes_edit_mode(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<bool> palette_hints_enabled(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::vector<PaletteHint>>
    palette_hints(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<PackingStrategyType>
    packing_strategy(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<PackingStrategyParams>
    packing_strategy_params(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<TileSharingPacking>
    tile_sharing_packing(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<TileSharingAlignment>
    tile_sharing_alignment(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<TilesPaletteMode>
    tiles_palette_mode(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<AnimPaletteResolutionStrategy>
    global_anim_palette_resolution_strategy(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<AnimKeyFrameResolutionStrategy>
    global_anim_key_frame_resolution_strategy(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<AnimMultiPaletteSubtileResolutionStrategy>
    global_anim_multi_palette_subtile_resolution_strategy(
        ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<FrameLinking>
    global_frame_linking(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<PerAnimOverrides>
    per_anim_overrides(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<bool>
    cross_tileset_anim_linking(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<bool> create_sample_anims(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<bool> verify_checksums(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<PrimaryPairingMode>
    primary_pairing_mode(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::vector<std::string>>
    primary_pairing_partners(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::vector<std::string>>
    diagnostic_warnings_exclude(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::vector<std::string>>
    diagnostic_warnings_include(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::vector<std::string>>
    diagnostic_remarks_exclude(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::vector<std::string>>
    diagnostic_remarks_include(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::string>
    tileset_paths_primary_src(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::string>
    tileset_paths_primary_bin(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::string>
    tileset_paths_secondary_src(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::string>
    tileset_paths_secondary_bin(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::optional<std::size_t>>
    metatile_attribute_size(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<std::optional<std::size_t>>
    metatile_attribute_declaration_size(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<MetatileAttributeFieldDefinitions>
    metatile_attribute_fields(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<MetatileAttributeFieldOverrides>
    metatile_attribute_field_overrides(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<RolePinDefinitions>
    role_pins(ConfigScopeType type, const std::string &scope) const override;
    [[nodiscard]] LayerValue<bool>
    tileset_animations_wire_anim_code(ConfigScopeType type, const std::string &scope) const override;

  private:
    [[nodiscard]] bool scope_matches(ConfigScopeType type, const std::string &scope) const;

    ConfigScopeType scope_type_;
    std::string scope_;
    std::string source_info_;

    std::optional<std::size_t> num_tiles_in_primary_override_;
    std::optional<std::size_t> num_tiles_total_override_;
    std::optional<std::size_t> num_metatiles_in_primary_override_;
    std::optional<std::size_t> num_metatiles_total_override_;
    std::optional<std::size_t> num_palettes_in_primary_override_;
    std::optional<std::size_t> num_palettes_total_override_;
    std::optional<std::size_t> max_map_data_size_override_;
    std::optional<std::size_t> num_tiles_per_metatile_override_;
    std::optional<Rgba32> extrinsic_transparency_override_;
    std::optional<bool> ignore_triple_layer_content_override_;
    std::optional<ArtifactEditMode> tiles_edit_mode_override_;
    std::optional<ArtifactEditMode> palettes_edit_mode_override_;
    std::optional<bool> palette_hints_enabled_override_;
    std::optional<std::vector<PaletteHint>> palette_hints_override_;
    std::optional<PackingStrategyType> packing_strategy_override_;
    std::optional<PackingStrategyParams> packing_strategy_params_override_;
    std::optional<TileSharingPacking> tile_sharing_packing_override_;
    std::optional<TileSharingAlignment> tile_sharing_alignment_override_;
    std::optional<TilesPaletteMode> tiles_palette_mode_override_;
    std::optional<AnimPaletteResolutionStrategy> global_anim_palette_resolution_strategy_override_;
    std::optional<AnimKeyFrameResolutionStrategy> global_anim_key_frame_resolution_strategy_override_;
    std::optional<AnimMultiPaletteSubtileResolutionStrategy>
        global_anim_multi_palette_subtile_resolution_strategy_override_;
    std::optional<FrameLinking> global_frame_linking_override_;
    std::optional<PerAnimOverrides> per_anim_overrides_override_;
    std::optional<bool> cross_tileset_anim_linking_override_;
    std::optional<bool> create_sample_anims_override_;
    std::optional<bool> verify_checksums_override_;
    std::optional<PrimaryPairingMode> primary_pairing_mode_override_;
    std::optional<std::vector<std::string>> primary_pairing_partners_override_;
    std::optional<std::vector<std::string>> diagnostic_warnings_exclude_override_;
    std::optional<std::vector<std::string>> diagnostic_warnings_include_override_;
    std::optional<std::vector<std::string>> diagnostic_remarks_exclude_override_;
    std::optional<std::vector<std::string>> diagnostic_remarks_include_override_;
    std::optional<std::string> tileset_paths_primary_src_override_;
    std::optional<std::string> tileset_paths_primary_bin_override_;
    std::optional<std::string> tileset_paths_secondary_src_override_;
    std::optional<std::string> tileset_paths_secondary_bin_override_;
    std::optional<std::optional<std::size_t>> metatile_attribute_size_override_;
    std::optional<std::optional<std::size_t>> metatile_attribute_declaration_size_override_;
    std::optional<MetatileAttributeFieldDefinitions> metatile_attribute_fields_override_;
    std::optional<MetatileAttributeFieldOverrides> metatile_attribute_field_overrides_override_;
    std::optional<RolePinDefinitions> role_pins_override_;
    std::optional<bool> tileset_animations_wire_anim_code_override_;
};

} // namespace porytiles