#pragma once

#include <string>
#include <unordered_set>

namespace porytiles {

// NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
// To add new config values or make other changes, edit config_schema.yaml and regenerate via:
//
//   uv run scripts/generate_config.py

/// @brief Set of valid YAML configuration paths.
///
/// @details
/// This set contains all valid dot-separated paths that can appear in porytiles.yaml configuration files. Both leaf
/// paths (e.g., "fieldmap.num_tiles_in_primary") and intermediate paths (e.g., "fieldmap") are included.
///
/// This is auto-generated from config_schema.yaml - do not edit directly.
inline const std::unordered_set<std::string> valid_yaml_paths = {
    "diagnostics",
    "diagnostics.remarks",
    "diagnostics.remarks.exclude",
    "diagnostics.remarks.include",
    "diagnostics.warnings",
    "diagnostics.warnings.exclude",
    "diagnostics.warnings.include",
    "fieldmap",
    "fieldmap.max_map_data_size",
    "fieldmap.metatile_attribute_declaration_size",
    "fieldmap.metatile_attribute_field_overrides",
    "fieldmap.metatile_attribute_fields",
    "fieldmap.metatile_attribute_size",
    "fieldmap.num_metatiles_in_primary",
    "fieldmap.num_metatiles_total",
    "fieldmap.num_palettes_in_primary",
    "fieldmap.num_palettes_total",
    "fieldmap.num_tiles_in_primary",
    "fieldmap.num_tiles_per_metatile",
    "fieldmap.num_tiles_total",
    "fieldmap.role_pins",
    "tileset",
    "tileset.animations",
    "tileset.animations.cross_tileset_linking",
    "tileset.animations.frame_linking",
    "tileset.animations.key_frame_resolution_strategy",
    "tileset.animations.multi_palette_subtile_resolution_strategy",
    "tileset.animations.palette_resolution_strategy",
    "tileset.animations.per_animation_overrides",
    "tileset.animations.wire_anim_code",
    "tileset.extrinsic_transparency",
    "tileset.ignore_triple_layer_content",
    "tileset.palettes",
    "tileset.palettes.edit_mode",
    "tileset.palettes.packing",
    "tileset.palettes.packing.hints",
    "tileset.palettes.packing.hints_enabled",
    "tileset.palettes.packing.strategy",
    "tileset.palettes.packing.strategy_params",
    "tileset.paths",
    "tileset.paths.primary",
    "tileset.paths.primary.bin",
    "tileset.paths.primary.src",
    "tileset.paths.secondary",
    "tileset.paths.secondary.bin",
    "tileset.paths.secondary.src",
    "tileset.primary_pairing",
    "tileset.primary_pairing.mode",
    "tileset.primary_pairing.partners",
    "tileset.tiles",
    "tileset.tiles.edit_mode",
    "tileset.tiles.palette_mode",
    "tileset.tiles.sharing",
    "tileset.tiles.sharing.alignment",
    "tileset.tiles.sharing.packing",
    "verify_checksums",
};

/// @brief Set of YAML path prefixes that represent map-type configuration values.
///
/// @details
/// Map-type config values have dynamic children (e.g., animation names as keys). Paths that start with any of these
/// prefixes followed by a dot should not trigger "unknown configuration key" warnings, since the children are
/// user-defined keys rather than fixed config paths.
///
/// This is auto-generated from config_schema.yaml - do not edit directly.
inline const std::unordered_set<std::string> valid_yaml_map_prefixes = {
    "fieldmap.metatile_attribute_field_overrides",
    "tileset.animations.per_animation_overrides",
    "tileset.palettes.packing.strategy_params",
};

} // namespace porytiles