#pragma once

#include <algorithm>
#include <cctype>
#include <format>
#include <optional>
#include <ostream>
#include <string>

#include "porytiles2/utilities/panic/panic.hpp"

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate via:
 *
 *   uv run Scripts/generate_config.py
 */

namespace porytiles2 {

/**
 * @brief Strategy for resolving animation frame palette mismatches.
 *
 * @details
 * When processing animation frames, it's possible for frame palettes to not match the expected
 * tileset palette. This enum determines how to handle such cases during compilation.
 *
 */
enum class AnimPalResolutionStrategy {
    /**
     * @brief Disallow palette resolution fallback and error out.
     */
    error,
    /**
     * @brief Use palette 00.pal.
     */
    default_pal,
    /**
     * @brief Use the Porymap-component frame PNG internal palette, if present.
     */
    internal_png_pal,
    /**
     * @brief Scan layouts config and find all tilesets paired with current tileset, see if an index is present in any.
     */
    full_tileset_scan
};

/**
 * @brief Parses a string into a AnimPalResolutionStrategy with fuzzy matching.
 *
 * @details
 * Performs parsing in two phases:
 * 1. Exact match against C++ constant names (snake_case)
 * 2. Case-insensitive fuzzy match against configured fuzzy_names
 *
 * This unified function is used by both CLI and YAML parsing. The fuzzy matching
 * allows users to use various common formats (kebab-case, snake_case, etc.) while
 * still getting good error messages through LazyLayeredConfig.
 *
 * @param str The string to parse
 * @return The parsed value, or std::nullopt if the string is invalid
 */
[[nodiscard]] inline std::optional<AnimPalResolutionStrategy>
anim_pal_resolution_strategy_from_str(const std::string &str)
{
    // Phase 1: Exact match against C++ constant names
    if (str == "error") {
        return std::optional{AnimPalResolutionStrategy::error};
    }
    if (str == "default_pal") {
        return std::optional{AnimPalResolutionStrategy::default_pal};
    }
    if (str == "internal_png_pal") {
        return std::optional{AnimPalResolutionStrategy::internal_png_pal};
    }
    if (str == "full_tileset_scan") {
        return std::optional{AnimPalResolutionStrategy::full_tileset_scan};
    }

    // Phase 2: Case-insensitive fuzzy match
    std::string lower_str = str;
    std::ranges::transform(
        lower_str, lower_str.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

    // Fuzzy names for error
    if (lower_str == "error") {
        return std::optional{AnimPalResolutionStrategy::error};
    }
    if (lower_str == "err") {
        return std::optional{AnimPalResolutionStrategy::error};
    }
    // Fuzzy names for default_pal
    if (lower_str == "default-palette") {
        return std::optional{AnimPalResolutionStrategy::default_pal};
    }
    if (lower_str == "default-pal") {
        return std::optional{AnimPalResolutionStrategy::default_pal};
    }
    if (lower_str == "default_palette") {
        return std::optional{AnimPalResolutionStrategy::default_pal};
    }
    if (lower_str == "default_pal") {
        return std::optional{AnimPalResolutionStrategy::default_pal};
    }
    if (lower_str == "defaultpal") {
        return std::optional{AnimPalResolutionStrategy::default_pal};
    }
    if (lower_str == "default") {
        return std::optional{AnimPalResolutionStrategy::default_pal};
    }
    // Fuzzy names for internal_png_pal
    if (lower_str == "internal-png-palette") {
        return std::optional{AnimPalResolutionStrategy::internal_png_pal};
    }
    if (lower_str == "internal_png_palette") {
        return std::optional{AnimPalResolutionStrategy::internal_png_pal};
    }
    if (lower_str == "internal-png-pal") {
        return std::optional{AnimPalResolutionStrategy::internal_png_pal};
    }
    if (lower_str == "internal_png_pal") {
        return std::optional{AnimPalResolutionStrategy::internal_png_pal};
    }
    if (lower_str == "internalpngpal") {
        return std::optional{AnimPalResolutionStrategy::internal_png_pal};
    }
    // Fuzzy names for full_tileset_scan
    if (lower_str == "full-tileset-scan") {
        return std::optional{AnimPalResolutionStrategy::full_tileset_scan};
    }
    if (lower_str == "full_tileset_scan") {
        return std::optional{AnimPalResolutionStrategy::full_tileset_scan};
    }
    if (lower_str == "fulltilesetscan") {
        return std::optional{AnimPalResolutionStrategy::full_tileset_scan};
    }

    return std::nullopt;
}

/**
 * @brief Converts a AnimPalResolutionStrategy to its canonical string representation.
 *
 * @details
 * Returns the C++ constant name (snake_case). This is the canonical form used for
 * general purpose string conversion, logging, and error messages.
 *
 * @param m The value to convert
 * @return The canonical snake_case string representation
 */
[[nodiscard]] inline std::string to_string(const AnimPalResolutionStrategy m)
{
    switch (m) {
    case AnimPalResolutionStrategy::error:
        return "error";
    case AnimPalResolutionStrategy::default_pal:
        return "default_pal";
    case AnimPalResolutionStrategy::internal_png_pal:
        return "internal_png_pal";
    case AnimPalResolutionStrategy::full_tileset_scan:
        return "full_tileset_scan";
    }
    panic("unhandled AnimPalResolutionStrategy value");
}

/**
 * @brief Stream insertion operator for AnimPalResolutionStrategy.
 *
 * @param os The output stream
 * @param m The value to output
 * @return Reference to the output stream
 */
inline std::ostream &operator<<(std::ostream &os, const AnimPalResolutionStrategy m)
{
    return os << to_string(m);
}

} // namespace porytiles2

template <>
struct std::formatter<porytiles2::AnimPalResolutionStrategy> {
    constexpr auto parse(std::format_parse_context &ctx)
    {
        return ctx.begin();
    }

    auto format(const porytiles2::AnimPalResolutionStrategy &value, auto &ctx) const
    {
        return std::format_to(ctx.out(), "{}", porytiles2::to_string(value));
    }
};