#pragma once

#include <string>

#include "porytiles2/domain/models/rgba32.hpp"
#include "porytiles2/utilities/source_locations.hpp"
#include "porytiles2/utilities/text/plain_text_formatter.hpp"
#include "porytiles2/xcut/config/config_scope_type.hpp"
#include "porytiles2/xcut/config/config_value.hpp"
#include "porytiles2/xcut/config/config_validators.hpp"
#include "porytiles2/utilities/panic/panic.hpp"
#include "porytiles2/utilities/result/chainable_result.hpp"

namespace porytiles2 {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate using
 * Scripts/generate_config.py.
 */

/**
 * @brief Interface that defines a complete domain layer configuration.
 */
class DomainConfig {
  public:
    virtual ~DomainConfig() = default;

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_tiles_primary(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = num_tiles_primary_validated(type, scope);
        // Apply cross-field validators
        if (validated_val.has_value()) {
            validated_val = compare_less_equal<std::size_t>(
                validated_val.value(), *this, type, scope, "num_tiles_total",
                [](const DomainConfig &cfg, ConfigScopeType t, const std::string &s) { return cfg.num_tiles_total_validated(t, s); }
            );
        }
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_tiles_total(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = num_tiles_total_validated(type, scope);
        // Apply cross-field validators
        if (validated_val.has_value()) {
            validated_val = compare_greater_equal<std::size_t>(
                validated_val.value(), *this, type, scope, "num_tiles_primary",
                [](const DomainConfig &cfg, ConfigScopeType t, const std::string &s) { return cfg.num_tiles_primary_validated(t, s); }
            );
        }
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_metatiles_primary(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = num_metatiles_primary_validated(type, scope);
        // Apply cross-field validators
        if (validated_val.has_value()) {
            validated_val = compare_less_equal<std::size_t>(
                validated_val.value(), *this, type, scope, "num_metatiles_total",
                [](const DomainConfig &cfg, ConfigScopeType t, const std::string &s) { return cfg.num_metatiles_total_validated(t, s); }
            );
        }
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_metatiles_total(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = num_metatiles_total_validated(type, scope);
        // Apply cross-field validators
        if (validated_val.has_value()) {
            validated_val = compare_greater_equal<std::size_t>(
                validated_val.value(), *this, type, scope, "num_metatiles_primary",
                [](const DomainConfig &cfg, ConfigScopeType t, const std::string &s) { return cfg.num_metatiles_primary_validated(t, s); }
            );
        }
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_pals_primary(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = num_pals_primary_validated(type, scope);
        // Apply cross-field validators
        if (validated_val.has_value()) {
            validated_val = compare_less_equal<std::size_t>(
                validated_val.value(), *this, type, scope, "num_pals_total",
                [](const DomainConfig &cfg, ConfigScopeType t, const std::string &s) { return cfg.num_pals_total_validated(t, s); }
            );
        }
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_pals_total(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = num_pals_total_validated(type, scope);
        // Apply cross-field validators
        if (validated_val.has_value()) {
            validated_val = compare_greater_equal<std::size_t>(
                validated_val.value(), *this, type, scope, "num_pals_primary",
                [](const DomainConfig &cfg, ConfigScopeType t, const std::string &s) { return cfg.num_pals_primary_validated(t, s); }
            );
        }
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    max_map_data_size(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = max_map_data_size_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<std::size_t>>
    num_tiles_per_metatile(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = num_tiles_per_metatile_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<Rgba32>>
    extrinsic_transparency(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = extrinsic_transparency_validated(type, scope);
        return validated_val;
    }

    // Public method with cross-field validation only (Tier 3)
    [[nodiscard]] ChainableResult<ConfigValue<bool>>
    patch_build_enabled(ConfigScopeType type, const std::string &scope) const
    {
        auto validated_val = patch_build_enabled_validated(type, scope);
        return validated_val;
    }

  protected:
    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_tiles_primary_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = num_tiles_primary_raw(type, scope);
        // Apply validators in sequence
        if (raw_val.has_value()) {
            raw_val = size_t_val_greater_than_zero(raw_val.value());
        }
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_tiles_primary_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_tiles_total_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = num_tiles_total_raw(type, scope);
        // Apply validators in sequence
        if (raw_val.has_value()) {
            raw_val = size_t_val_greater_than_zero(raw_val.value());
        }
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_tiles_total_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_metatiles_primary_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = num_metatiles_primary_raw(type, scope);
        // Apply validators in sequence
        if (raw_val.has_value()) {
            raw_val = size_t_val_greater_than_zero(raw_val.value());
        }
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_metatiles_primary_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_metatiles_total_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = num_metatiles_total_raw(type, scope);
        // Apply validators in sequence
        if (raw_val.has_value()) {
            raw_val = size_t_val_greater_than_zero(raw_val.value());
        }
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_metatiles_total_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_pals_primary_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = num_pals_primary_raw(type, scope);
        // Apply validators in sequence
        if (raw_val.has_value()) {
            raw_val = size_t_val_greater_than_zero(raw_val.value());
        }
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_pals_primary_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_pals_total_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = num_pals_total_raw(type, scope);
        // Apply validators in sequence
        if (raw_val.has_value()) {
            raw_val = size_t_val_greater_than_zero(raw_val.value());
        }
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_pals_total_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    max_map_data_size_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = max_map_data_size_raw(type, scope);
        // Apply validators in sequence
        if (raw_val.has_value()) {
            raw_val = size_t_val_greater_than_zero(raw_val.value());
        }
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    max_map_data_size_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_tiles_per_metatile_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = num_tiles_per_metatile_raw(type, scope);
        // Apply validators in sequence
        if (raw_val.has_value()) {
            raw_val = size_t_val_eight_or_twelve(raw_val.value());
        }
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_tiles_per_metatile_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<Rgba32>>
    extrinsic_transparency_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = extrinsic_transparency_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<Rgba32>>
    extrinsic_transparency_raw(ConfigScopeType type, const std::string &scope) const = 0;

    // Protected method with single-value validation only (Tier 2)
    [[nodiscard]] virtual ChainableResult<ConfigValue<bool>>
    patch_build_enabled_validated(ConfigScopeType type, const std::string &scope) const
    {
        auto raw_val = patch_build_enabled_raw(type, scope);
        return raw_val;
    }

    // Protected virtual method that fetches raw value from provider (Tier 1)
    [[nodiscard]] virtual ChainableResult<ConfigValue<bool>>
    patch_build_enabled_raw(ConfigScopeType type, const std::string &scope) const = 0;

};

} // namespace porytiles2