#pragma once

#include <string>

#include "porytiles2/domain/models/rgba32.hpp"
#include "porytiles2/utilities/source_locations.hpp"
#include "porytiles2/utilities/text/plain_text_formatter.hpp"
#include "porytiles2/xcut/config/config_value.hpp"
#include "porytiles2/xcut/panic/panic.hpp"
#include "porytiles2/xcut/result/chainable_result.hpp"

namespace porytiles2 {

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate using
 * Scripts/generate_config.py.
 */

/**
 * @brief Interface that defines a complete domain layer configuration.
 *
 * @details
 * The domain layer operates with this interface - it doesn't need to worry about implementation. Every config value is
 * either virtual (i.e., comes from the user) or defined in terms of other virtual values (derived).
 */
class DomainConfig {
  public:
    virtual ~DomainConfig() = default;

    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_tiles_primary(const std::string &tileset) const = 0;

    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_tiles_total(const std::string &tileset) const = 0;

    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_metatiles_primary(const std::string &tileset) const = 0;

    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_metatiles_total(const std::string &tileset) const = 0;

    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_pals_primary(const std::string &tileset) const = 0;

    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_pals_total(const std::string &tileset) const = 0;

    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    max_map_data_size(const std::string &tileset) const = 0;

    [[nodiscard]] virtual ChainableResult<ConfigValue<std::size_t>>
    num_tiles_per_metatile(const std::string &tileset) const = 0;

    [[nodiscard]] virtual ChainableResult<ConfigValue<Rgba32>>
    extrinsic_transparency(const std::string &tileset) const = 0;

    [[nodiscard]] virtual ChainableResult<ConfigValue<bool>>
    patch_build_enabled(const std::string &tileset) const = 0;

};

} // namespace porytiles2