#pragma once

#include <algorithm>
#include <cctype>
#include <format>
#include <optional>
#include <ostream>
#include <string>

#include "porytiles2/utilities/panic/panic.hpp"

/*
 * NOTE: DO NOT EDIT THIS FILE DIRECTLY. It is AUTO-GENERATED from config_schema.yaml.
 * To add new config values or make other changes, edit config_schema.yaml and regenerate via:
 *
 *   uv run Scripts/generate_config.py
 */

namespace porytiles2 {

/**
 * @brief Selects the palette packing algorithm to use during tileset compilation.
 *
 * @details
 * Controls which algorithm is used to assign tiles to palettes. Each strategy offers different
 * trade-offs between speed, solution quality, and configurability. Backtracking is the default
 * and handles the widest range of inputs. Best Fusion is fast but may fail on hard instances.
 * Overload-And-Remove uses multi-start retries to escape local optima.
 *
 */
enum class PackingStrategyType {
    /**
     * @brief Greedy weighted-cost packing (fast, no retries).
     */
    best_fusion,
    /**
     * @brief DFS/BFS backtracking search (default).
     */
    backtracking,
    /**
     * @brief Greedy with overload-and-remove multi-start retries.
     */
    overload_and_remove
};

/**
 * @brief Parses a string into a PackingStrategyType with fuzzy matching.
 *
 * @details
 * Performs parsing in two phases:
 * 1. Exact match against C++ constant names (snake_case)
 * 2. Case-insensitive fuzzy match against configured fuzzy_names
 *
 * This unified function is used by both CLI and YAML parsing. The fuzzy matching
 * allows users to use various common formats (kebab-case, snake_case, etc.) while
 * still getting good error messages through LazyLayeredConfig.
 *
 * @param str The string to parse
 * @return The parsed value, or std::nullopt if the string is invalid
 */
[[nodiscard]] inline std::optional<PackingStrategyType> packing_strategy_type_from_str(const std::string &str)
{
    // Phase 1: Exact match against C++ constant names
    if (str == "best_fusion") {
        return std::optional{PackingStrategyType::best_fusion};
    }
    if (str == "backtracking") {
        return std::optional{PackingStrategyType::backtracking};
    }
    if (str == "overload_and_remove") {
        return std::optional{PackingStrategyType::overload_and_remove};
    }

    // Phase 2: Case-insensitive fuzzy match
    std::string lower_str = str;
    std::ranges::transform(
        lower_str, lower_str.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });

    // Fuzzy names for best_fusion
    if (lower_str == "best-fusion") {
        return std::optional{PackingStrategyType::best_fusion};
    }
    if (lower_str == "best_fusion") {
        return std::optional{PackingStrategyType::best_fusion};
    }
    if (lower_str == "bestfusion") {
        return std::optional{PackingStrategyType::best_fusion};
    }
    // Fuzzy names for backtracking
    if (lower_str == "backtracking") {
        return std::optional{PackingStrategyType::backtracking};
    }
    // Fuzzy names for overload_and_remove
    if (lower_str == "overload-and-remove") {
        return std::optional{PackingStrategyType::overload_and_remove};
    }
    if (lower_str == "overload_and_remove") {
        return std::optional{PackingStrategyType::overload_and_remove};
    }
    if (lower_str == "overloadandremove") {
        return std::optional{PackingStrategyType::overload_and_remove};
    }

    return std::nullopt;
}

/**
 * @brief Converts a PackingStrategyType to its canonical string representation.
 *
 * @details
 * Returns the C++ constant name (snake_case). This is the canonical form used for
 * general purpose string conversion, logging, and error messages.
 *
 * @param m The value to convert
 * @return The canonical snake_case string representation
 */
[[nodiscard]] inline std::string to_string(const PackingStrategyType m)
{
    switch (m) {
    case PackingStrategyType::best_fusion:
        return "best_fusion";
    case PackingStrategyType::backtracking:
        return "backtracking";
    case PackingStrategyType::overload_and_remove:
        return "overload_and_remove";
    }
    panic("unhandled PackingStrategyType value");
}

/**
 * @brief Stream insertion operator for PackingStrategyType.
 *
 * @param os The output stream
 * @param m The value to output
 * @return Reference to the output stream
 */
inline std::ostream &operator<<(std::ostream &os, const PackingStrategyType m)
{
    return os << to_string(m);
}

} // namespace porytiles2

template <>
struct std::formatter<porytiles2::PackingStrategyType> {
    constexpr auto parse(std::format_parse_context &ctx)
    {
        return ctx.begin();
    }

    auto format(const porytiles2::PackingStrategyType &value, auto &ctx) const
    {
        return std::format_to(ctx.out(), "{}", porytiles2::to_string(value));
    }
};