#pragma once

#include <set>
#include <string>

#include "porytiles2/domain/repos/artifact_key.hpp"
#include "porytiles2/domain/repos/tileset_artifact.hpp"

namespace porytiles2 {

/**
 * @brief Abstract interface for generating keys and discovering tileset artifacts in a backing store.
 *
 * @details
 * This interface provides the key generation and discovery functionality needed by the tileset repository system.
 * Implementations handle the specifics of how to organize and access artifacts in different backing stores (filesystem,
 * database, etc.).
 *
 * The interface separates key generation (which should be fast and stateless) from discovery operations (which may
 * involve I/O to search the backing store). Implementations may choose to cache expensive lookups during construction
 * to optimize performance.
 *
 * From the interface's perspective, tileset artifact keys are simple strings wrapped by the ArtifactKey class. If a
 * particular implementation requires a complex key type, the implementation must take care to ensure that this key type
 * is string-constructable. Luckily, rich string-based formats like JSON should be able to support almost any imaginable
 * key schema.
 */
class TilesetArtifactKeyProvider {
  public:
    virtual ~TilesetArtifactKeyProvider() = default;

    /**
     * @brief Constructs a key for a given tileset artifact.
     *
     * @details
     * This method should focus primarily on building keys from the provided parameters, not on searching the filesystem
     * or backing store. The key generation should be fast and deterministic based on the tileset name and artifact
     * specification.
     *
     * @param tileset_name The name of the tileset for the tileset artifact
     * @param artifact The artifact details specifying type, name, and index as applicable
     * @return The key for the given tileset artifact
     */
    [[nodiscard]] virtual ArtifactKey
    key_for(const std::string &tileset_name, const TilesetArtifact &artifact) const = 0;

    /**
     * @brief Checks whether an artifact exists in the backing store for the given key.
     *
     * @details
     * This method should perform the actual existence check against the backing store using the provided key. This may
     * involve filesystem operations, database queries, or other I/O depending on the implementation.
     *
     * @param key The key identifying the artifact to check (generated by key_for)
     * @return True if the artifact exists in the backing store, false otherwise
     */
    [[nodiscard]] virtual bool exists(const ArtifactKey &key) const = 0;

    /**
     * @brief Checks whether a tileset exists in the backing store for the given tileset name.
     *
     * @param tileset_name The name of the tileset to check
     * @return True if the tileset exists in the backing store, false otherwise
     */
    [[nodiscard]] virtual bool tileset_exists(const std::string &tileset_name) const = 0;

    /**
     * @brief Discovers the names of all Porytiles animations available for a tileset.
     *
     * @details
     * Searches the backing store to find all Porytiles animation directories or assets for the specified tileset.
     * Porytiles animations require both a key frame and at least one animation frame (00.png).
     *
     * @param tileset_name The name of the tileset to search for animations
     * @return Set of animation names found in the backing store
     */
    [[nodiscard]] virtual std::set<std::string> discover_porytiles_anims(const std::string &tileset_name) const = 0;

    /**
     * @brief Discovers the frame indices for a specific Porytiles animation.
     *
     * @details
     * Searches the backing store to find all animation frame files (excluding the key frame and 00.png) for a specific
     * Porytiles animation. The returned indices should be consecutive starting from 1. Since frame 0 is required,
     * callers don't need to discover it.
     *
     * @param tileset_name The name of the tileset containing the animation
     * @param anim_name The name of the animation to search for frames
     * @return Set of frame indices found in the backing store (typically starting from 1)
     */
    [[nodiscard]] virtual std::set<int>
    discover_porytiles_anim_frames(const std::string &tileset_name, const std::string &anim_name) const = 0;

    /**
     * @brief Discovers the names of all Porymap animations available for a tileset.
     *
     * @details
     * Searches the backing store to find all Porymap animation assets for the specified tileset. Porymap animations do
     * not require key frames, only sequential frame files.
     *
     * @param tileset_name The name of the tileset to search for animations
     * @return Set of animation names found in the backing store
     */
    [[nodiscard]] virtual std::set<std::string> discover_porymap_anims(const std::string &tileset_name) const = 0;

    /**
     * @brief Discovers the frame indices for a specific Porymap animation.
     *
     * @details
     * Searches the backing store to find all animation frame files (excluding the key frame and 00.png) for a specific
     * Porymap animation. The returned indices should be consecutive starting from 1. Since frame 0 is required, callers
     * don't need to discover it.
     *
     * @param tileset_name The name of the tileset containing the animation
     * @param anim_name The name of the animation to search for frames
     * @return Set of frame indices found in the backing store
     */
    [[nodiscard]] virtual std::set<int>
    discover_porymap_anim_frames(const std::string &tileset_name, const std::string &anim_name) const = 0;

    /**
     * @brief Gets the keys for all Porytiles artifacts present in the given Tileset.
     *
     * @details
     * Each Porytiles artifact has a unique key by which the ArtifactChecksumProvider and the TilesetRepo can identify
     * it. The format of these keys and the method for producing them are implementation-defined.
     *
     * @return A vector of Porytiles artifact keys for the given Tileset
     */
    [[nodiscard]] virtual std::vector<ArtifactKey> get_porytiles_artifact_keys(const std::string &tileset_name) const {
        using enum TilesetArtifact::Type;
        std::vector<ArtifactKey> result;

        const auto bottom_png_key = key_for(tileset_name, TilesetArtifact{bottom_png});
        result.push_back(bottom_png_key);
        const auto middle_png_key = key_for(tileset_name, TilesetArtifact{middle_png});
        result.push_back(middle_png_key);
        const auto top_png_key = key_for(tileset_name, TilesetArtifact{top_png});
        result.push_back(top_png_key);
        const auto attr_csv_key = key_for(tileset_name, TilesetArtifact{attributes_csv});
        result.push_back(attr_csv_key);

        // TODO: don't hardcode this num_pals value
        // TODO: warn user if we found overrides like 1.pal, these won't work they have to be 01.pal
        constexpr int num_pals = 16;
        for (int i = 0; i < num_pals; i++) {
            const auto override_key = key_for(tileset_name, TilesetArtifact{pal_override_n, i});
            if (exists(override_key)) {
                result.push_back(override_key);
            }
        }

        // TODO: fill in anims

        return result;
    }

    /**
     * @brief Gets the keys for all Porymap artifacts present in the given Tileset.
     *
     * @details
     * Each Porymap artifact has a unique key by which the ArtifactChecksumProvider and the TilesetRepo can identify it.
     * The format of these keys and the method for producing them are implementation-defined.
     *
     * @return A vector of Porymap artifact keys for the given Tileset
     */
    [[nodiscard]] virtual std::vector<ArtifactKey> get_porymap_artifact_keys(const std::string &tileset_name) const {
        using enum TilesetArtifact::Type;
        std::vector<ArtifactKey> result;

        const auto metatiles_key = key_for(tileset_name, TilesetArtifact{metatiles_bin});
        result.push_back(metatiles_key);
        const auto attr_key = key_for(tileset_name, TilesetArtifact{metatile_attributes_bin});
        result.push_back(attr_key);
        const auto tiles_png_key = key_for(tileset_name, TilesetArtifact{tiles_png});
        result.push_back(tiles_png_key);

        // TODO: don't hardcode this num_pals value
        // TODO: warn user if we found pals like 1.pal, these won't work they have to be 01.pal
        constexpr int num_pals = 16;
        for (int i = 0; i < num_pals; i++) {
            const auto pal_key = key_for(tileset_name, TilesetArtifact{pal_n, i});
            result.push_back(pal_key);
        }

        // TODO: fill in anims

        return result;
    }

    /**
     * @brief Gets the keys for all tileset artifacts (both Porytiles and Porymap) present in the given Tileset.
     *
     * @details
     * This method combines the results from both get_porytiles_artifact_keys() and get_porymap_artifact_keys() to
     * provide a comprehensive list of all artifact keys associated with the tileset.
     *
     * @param tileset_name The name of the Tileset for which to get all artifact keys
     * @return A vector containing all Porytiles and Porymap artifact keys for the given Tileset
     */
    [[nodiscard]] virtual std::vector<ArtifactKey> get_all_artifact_keys(const std::string &tileset_name) const {
        const auto porytiles_keys = get_porytiles_artifact_keys(tileset_name);
        const auto porymap_keys = get_porymap_artifact_keys(tileset_name);

        std::vector<ArtifactKey> result;
        result.reserve(porytiles_keys.size() + porymap_keys.size());
        result.insert(result.end(), porytiles_keys.begin(), porytiles_keys.end());
        result.insert(result.end(), porymap_keys.begin(), porymap_keys.end());

        return result;
    }
};

} // namespace porytiles2
