#pragma once

#include <any>
#include <set>

#include "porytiles2/domain/repos/tileset_artifact.hpp"

namespace porytiles2 {

/**
 * @brief Abstract interface for generating keys and discovering tileset artifacts in a backing store.
 *
 * @details
 * This interface provides the key generation and discovery functionality needed by the tileset repository system.
 * Implementations handle the specifics of how artifacts are organized and accessed in different backing stores
 * (filesystem, database, etc.).
 *
 * The interface separates key generation (which should be fast and stateless) from discovery operations (which may
 * involve I/O to search the backing store). Implementations may choose to cache expensive lookups during construction
 * to optimize performance.
 */
class TilesetArtifactKeyProvider {
  public:
    virtual ~TilesetArtifactKeyProvider() = default;

    /**
     * @brief Constructs a key for a given tileset artifact.
     *
     * @details
     * This method should focus primarily on building keys from the provided parameters, not on searching the filesystem
     * or backing store. The key generation should be fast and deterministic based on the tileset name and artifact
     * specification.
     *
     * @param tileset_name The name of the tileset for the tileset artifact
     * @param artifact The artifact details specifying type, name, and index as applicable
     * @return The key for the given tileset artifact (type-erased as std::any)
     */
    virtual std::any key_for(const std::string &tileset_name, const TilesetArtifact &artifact) const = 0;

    /**
     * @brief Discovers the names of all Porytiles animations available for a tileset.
     *
     * @details
     * Searches the backing store to find all Porytiles animation directories or assets for the specified tileset.
     * Porytiles animations require both a key frame and at least one animation frame (00.png).
     *
     * @param tileset_name The name of the tileset to search for animations
     * @return Set of animation names found in the backing store
     */
    virtual std::set<std::string> discover_porytiles_anims(const std::string &tileset_name) const = 0;

    /**
     * @brief Discovers the frame indices for a specific Porytiles animation.
     *
     * @details
     * Searches the backing store to find all animation frame files (excluding the key frame and 00.png) for a specific
     * Porytiles animation. The returned indices should be consecutive starting from 1, as frame 0 is handled
     * separately.
     *
     * @param tileset_name The name of the tileset containing the animation
     * @param anim_name The name of the animation to search for frames
     * @return Set of frame indices found in the backing store (typically starting from 1)
     */
    virtual std::set<int> discover_porytiles_anim_frames(const std::string &tileset_name,
                                                         const std::string &anim_name) const = 0;

    /**
     * @brief Discovers the names of all Porymap animations available for a tileset.
     *
     * @details
     * Searches the backing store to find all Porymap animation assets for the specified tileset. Porymap animations do
     * not require key frames, only sequential frame files.
     *
     * @param tileset_name The name of the tileset to search for animations
     * @return Set of animation names found in the backing store
     */
    virtual std::set<std::string> discover_porymap_anims(const std::string &tileset_name) const = 0;

    /**
     * @brief Discovers the frame indices for a specific Porymap animation.
     *
     * @details
     * Searches the backing store to find all animation frame files for a specific Porymap animation. Unlike Porytiles
     * animations, Porymap animations start directly with sequential frame numbering.
     *
     * @param tileset_name The name of the tileset containing the animation
     * @param anim_name The name of the animation to search for frames
     * @return Set of frame indices found in the backing store
     */
    virtual std::set<int> discover_porymap_anim_frames(const std::string &tileset_name,
                                                       const std::string &anim_name) const = 0;

    /**
     * @brief Checks whether an artifact exists in the backing store for the given key.
     *
     * @details
     * This method should perform the actual existence check against the backing store using the provided key. This may
     * involve filesystem operations, database queries, or other I/O depending on the implementation.
     *
     * @param key The key identifying the artifact to check (generated by key_for)
     * @return True if the artifact exists in the backing store, false otherwise
     */
    virtual bool exists(const std::any &key) const = 0;
};

} // namespace porytiles2
