#ifndef GUARD_METATILE_BEHAVIORS_ENUM_REFERENCES_H
#define GUARD_METATILE_BEHAVIORS_ENUM_REFERENCES_H

#define FIRST_BEHAVIOR_VALUE 0x10

enum {
    MB_NORMAL = FIRST_BEHAVIOR_VALUE,
    MB_TALL_GRASS = MB_NORMAL + 2,
};

#endif // GUARD_METATILE_BEHAVIORS_ENUM_REFERENCES_H
