#pragma once

#include <filesystem>
#include <string>

#include "gsl/pointers"

#include "porytiles2/infra/config/infra_config.hpp"
#include "porytiles2/utilities/result/chainable_result.hpp"
#include "porytiles2/xcut/diagnostics/user_diagnostics.hpp"

namespace porytiles2 {

/**
 * @brief Modifies tileset_anims.c to include Porytiles-managed animation code headers.
 *
 * @details
 * This service adds and removes #include directives in pokeemerald's src/tileset_anims.c that point to
 * Porytiles-generated animation code headers. The include directive follows the pattern:
 *
 *     // [Porytiles] Auto-generated include. Do not remove.
 *     #include "porytiles_generated/tilesets/{tileset_dir}/generated_anim_code.h"
 *
 * Note: The "include/" prefix is omitted from the directive because pokeemerald's makefile already adds
 * "include" to the include path. The actual file lives at include/porytiles_generated/tilesets/{tileset_dir}/...
 *
 * All tilesets (primary and secondary) use the same base path. The tileset_dir is the snake_case version of the
 * tileset shorthand (e.g., "general" for gTileset_General, "battle_frontier" for gTileset_BattleFrontier).
 *
 * The service appends includes at the bottom of the file with a comment indicating they were auto-generated by
 * Porytiles.
 *
 * @see IncbinDeclarationAppender for similar append/removal patterns
 * @see ProjectTilesetMetadataWriter for surgical file modification approach
 */
class ProjectTilesetAnimsModifier {
  public:
    /**
     * @brief Constructs a TilesetAnimsModifier with required dependencies.
     *
     * @param project_root Path to the pokeemerald project root directory
     * @param config Configuration interface for tileset paths (non-owning, must outlive this object)
     * @param diagnostics Diagnostics interface for warnings/notes (non-owning, must outlive this object)
     */
    ProjectTilesetAnimsModifier(
        std::filesystem::path project_root,
        gsl::not_null<const InfraConfig *> config,
        gsl::not_null<const UserDiagnostics *> diagnostics);

    /**
     * @brief Adds an #include directive for the tileset's generated animation code.
     *
     * @details
     * Appends an include directive at the bottom of tileset_anims.c, pointing to the generated animation code header
     * at:
     *
     *     porytiles_generated/tilesets/{snake_case_dir}/generated_anim_code.h
     *
     * The include is preceded by a comment indicating it was auto-generated by Porytiles.
     *
     * The operation is idempotent: if the include already exists, a warning is emitted and no changes are made.
     *
     * @param tileset_name The tileset name (e.g., "gTileset_General")
     * @param is_secondary True for secondary tilesets, false for primary (currently unused but kept for API symmetry)
     * @pre tileset_name must start with "gTileset_"
     * @return Success or error result with details
     */
    [[nodiscard]] ChainableResult<void>
    wire_include_for_tileset(const std::string &tileset_name, bool is_secondary) const;

    /**
     * @brief Removes the #include directive for the tileset's generated animation code.
     *
     * @details
     * Removes the include directive for the specified tileset from tileset_anims.c. Used during restore operations to
     * return the file to its original state.
     *
     * The operation is idempotent: if the include doesn't exist, a warning is emitted and no changes are made.
     *
     * @param tileset_name The tileset name (e.g., "gTileset_General")
     * @param is_secondary True for secondary tilesets, false for primary
     * @pre tileset_name must start with "gTileset_"
     * @return Success or error result with details
     */
    [[nodiscard]] ChainableResult<void>
    remove_include_for_tileset(const std::string &tileset_name, bool is_secondary) const;

  private:
    std::filesystem::path project_root_;
    const InfraConfig *config_;
    const UserDiagnostics *diagnostics_;
};

} // namespace porytiles2
