#pragma once

#include <memory>
#include <string>

#include "porytiles2/domain/services/CSourceFileModifier.hpp"
#include "porytiles2/domain/services/CSourceGenerator.hpp"
#include "porytiles2/infra/project/ProjectPaths.hpp"
#include "porytiles2/templates/Result.hpp"

#include <gsl/gsl>

namespace porytiles {

/**
 * @brief String-based implementation of CSourceFileModifier for pokeemerald projects.
 *
 * @details
 * This class provides a concrete implementation of the CSourceFileModifier interface
 * using simple string appending operations. It modifies C header files by reading
 * existing content, appending new declarations, and writing the modified content
 * back to the file system.
 *
 * The implementation uses text-based file modification rather than AST manipulation,
 * making it simpler to implement and debug while being sufficient for the tileset
 * integration use case.
 *
 * Dependencies:
 * - ProjectPaths: For computing file paths within the pokeemerald project structure
 * - CSourceGenerator: For generating the C code constructs to append
 *
 * This class follows the established patterns in the Porytiles2 codebase:
 * - Uses Result<T> for error handling
 * - Implements domain interface in infrastructure layer
 * - Uses dependency injection for services
 * - Provides detailed error messages for debugging
 */
class ProjectCSourceFileAppender final : public CSourceFileModifier {
public:
  /**
   * @brief Constructs a ProjectCSourceFileAppender with required dependencies.
   *
   * @param paths Project path computation service (must not be null)
   * @param generator C source code generation service
   */
  explicit ProjectCSourceFileAppender(const gsl::not_null<ProjectPaths *> paths,
                                      std::unique_ptr<CSourceGenerator> generator);

  /**
   * @brief Append palette and tile declarations to the graphics header.
   *
   * @details
   * Reads the existing `src/data/tilesets/graphics.h` file, appends the palette
   * and tile declarations generated by the CSourceGenerator, and writes the
   * modified content back to the file.
   *
   * @param tileset_name The name of the tileset (e.g., "MyTileset")
   * @return Result<void> indicating success or failure with error details
   */
  [[nodiscard]] Result<void> AppendToGraphicsHeader(const std::string &tileset_name) override;

  /**
   * @brief Append tileset struct definition to the headers file.
   *
   * @details
   * Reads the existing `src/data/tilesets/headers.h` file, appends the tileset
   * struct definition generated by the CSourceGenerator, and writes the
   * modified content back to the file.
   *
   * @param tileset_name The name of the tileset (e.g., "MyTileset")
   * @return Result<void> indicating success or failure with error details
   */
  [[nodiscard]] Result<void> AppendToHeadersHeader(const std::string &tileset_name) override;

  /**
   * @brief Append metatile and attribute declarations to the metatiles header.
   *
   * @details
   * Reads the existing `src/data/tilesets/metatiles.h` file, appends the metatile
   * and attribute declarations generated by the CSourceGenerator, and writes the
   * modified content back to the file.
   *
   * @param tileset_name The name of the tileset (e.g., "MyTileset")
   * @return Result<void> indicating success or failure with error details
   */
  [[nodiscard]] Result<void> AppendToMetatilesHeader(const std::string &tileset_name) override;

  /**
   * @brief Append all necessary declarations for a new tileset.
   *
   * @details
   * Performs all three header file modifications in sequence. If any operation
   * fails, the entire operation fails and returns an error.
   *
   * @param tileset_name The name of the tileset (e.g., "MyTileset")
   * @return Result<void> indicating success or failure with error details
   */
  [[nodiscard]] Result<void> AppendTilesetDeclarations(const std::string &tileset_name) override;

private:
  const ProjectPaths *paths_;
  std::unique_ptr<CSourceGenerator> generator_;

  /**
   * @brief Append content to a file.
   *
   * @details
   * Reads the existing file content, appends the new content with proper
   * formatting, and writes the result back to the file system.
   *
   * @param file_path The path to the file to modify
   * @param content The content to append
   * @return Result<void> indicating success or failure with error details
   */
  [[nodiscard]] Result<void> AppendToFile(const std::filesystem::path &file_path,
                                          const std::string &content);

  /**
   * @brief Read the entire contents of a file.
   *
   * @param file_path The path to the file to read
   * @return Result<std::string> containing the file contents or error details
   */
  [[nodiscard]] Result<std::string> ReadFile(const std::filesystem::path &file_path);

  /**
   * @brief Write content to a file.
   *
   * @param file_path The path to the file to write
   * @param content The content to write
   * @return Result<void> indicating success or failure with error details
   */
  [[nodiscard]] Result<void> WriteFile(const std::filesystem::path &file_path,
                                       const std::string &content);
};

} // namespace porytiles