name: Create Release Package

inputs:
  os-arch:
    description: The OS and arch to package (e.g. linux-amd64)
    required: true

description: Create a Porytiles release package
runs:
  using: composite
  steps:
    - name: Create a release package
      shell: bash
      run: |
        echo "Packaging release ${{ inputs.os-arch }}..."
        mkdir "porytiles-${{ inputs.os-arch }}"
        cp build/legacy/tools/driver/porytiles-legacy "./porytiles-${{ inputs.os-arch }}"
        cp build/porytiles/tools/driver/porytiles "./porytiles-${{ inputs.os-arch }}"
        cp build/legacy/tests/LegacyTests "./porytiles-${{ inputs.os-arch }}"
        cp build/porytiles/tests/PorytilesUnitTests "./porytiles-${{ inputs.os-arch }}"
        cp build/porytiles/tests/PorytilesIntegrationTests "./porytiles-${{ inputs.os-arch }}"
        cp README.md "./porytiles-${{ inputs.os-arch }}"
        cp LICENSE "./porytiles-${{ inputs.os-arch }}"
        mkdir -p "./porytiles-${{ inputs.os-arch }}/resources"
        cp -r resources/doctests "./porytiles-${{ inputs.os-arch }}/resources"
        cp -r resources/examples "./porytiles-${{ inputs.os-arch }}/resources"
        cp -r resources/readme "./porytiles-${{ inputs.os-arch }}/resources"
        cp -r resources/tests "./porytiles-${{ inputs.os-arch }}/resources"
        cp -r legacy/vendor "./porytiles-${{ inputs.os-arch }}"

        pushd "./porytiles-${{ inputs.os-arch }}"
        ./LegacyTests
        ./PorytilesUnitTests
        ./PorytilesIntegrationTests
        popd

        zip -r "./porytiles-${{ inputs.os-arch }}.zip" "./porytiles-${{ inputs.os-arch }}"