name: Create Release Package

inputs:
  os-arch:
    description: The OS and arch to package (e.g. linux-amd64)
    required: true

description: Create a Porytiles release package
runs:
  using: composite
  steps:
    - name: Create a release package
      shell: bash
      run: |
        echo "Packaging release ${{ inputs.os-arch }}..."
        mkdir "porytiles-${{ inputs.os-arch }}"
        cp build/Porytiles1/tools/driver/porytiles "./porytiles-${{ inputs.os-arch }}"
        cp build/Porytiles2/tools/driver/porytiles2 "./porytiles-${{ inputs.os-arch }}"
        cp build/Porytiles1/tests/Porytiles1Tests "./porytiles-${{ inputs.os-arch }}"
        cp build/Porytiles2/tests/Porytiles2Tests "./porytiles-${{ inputs.os-arch }}"
        cp README.md "./porytiles-${{ inputs.os-arch }}"
        cp LICENSE "./porytiles-${{ inputs.os-arch }}"
        mkdir -p "./porytiles-${{ inputs.os-arch }}/Resources"
        cp -r Resources/Doctests "./porytiles-${{ inputs.os-arch }}/Resources"
        cp -r Resources/Examples "./porytiles-${{ inputs.os-arch }}/Resources"
        cp -r Resources/Readme "./porytiles-${{ inputs.os-arch }}/Resources"
        cp -r Resources/Tests "./porytiles-${{ inputs.os-arch }}/Resources"
        cp -r Porytiles1/vendor "./porytiles-${{ inputs.os-arch }}"

        pushd "./porytiles-${{ inputs.os-arch }}"
        ./Porytiles1Tests
        ./Porytiles2UnitTests
        popd

        zip -r "./porytiles-${{ inputs.os-arch }}.zip" "./porytiles-${{ inputs.os-arch }}"