#ifndef GUARD_METATILE_BEHAVIORS_H
#define GUARD_METATILE_BEHAVIORS_H

enum {
    MB_NORMAL,
    MB_TALL_GRASS,
    MB_LONG_GRASS,
};

#define MB_INVALID UCHAR_MAX

#endif // GUARD_METATILE_BEHAVIORS_H
