name: macOS ARM64 Clang Reusable 0.x Build Workflow

on:
  workflow_call:

jobs:
  build-0x-macos-arm64-clang:
    name: Build 0.x on macos-amd64 with clang
    runs-on: macos-13
    # GitHub removed Intel Mac runners, so macos-latest is now arm64
    # We don't need to install zlib since it is shipped with macOS, CMake will find it
    steps:
      - name: Install clang and other build dependencies
        run: |
          brew update
          brew install zlib || true
          brew install libpng || true
          brew install cmake || true
          brew install llvm || true
          /usr/local/opt/llvm/bin/clang++ --version

      - name: Checkout porytiles
        uses: actions/checkout@v3

      # Use -DCMAKE_FIND_FRAMEWORK=NEVER, otherwise CMake sometimes picks up outdated
      # package versions deeply buried in some ancient macOS system framework
      - name: Build the project
        run: |
          export CXX=/usr/local/opt/llvm/bin/clang++
          cmake -DCMAKE_FIND_FRAMEWORK=NEVER -B build
          cd build
          cmake --build . --verbose

      - name: Run the tests
        run: |
          ./build/Porytiles-0.x/tests/Porytiles0xTestSuite
