name: Build Job Templates

on:
  workflow_call:

# PR and dev builds make sure all platforms build with clang. Nightly releases
# use clang to build so we don't want to let in a PR that's going to fail one
# of the nightly pipelines. Since we do still care about GCC compatibility,
# we'll build with GCC on x86-64 Ubuntu as well. PRs should not introduce code
# that breaks GCC builds.
jobs:
  build-linux-amd64-clang:
    name: Build on linux-amd64 with clang
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Porytiles repository
        uses: actions/checkout@v4

      - name: Install Porytiles build dependencies
        uses: ./.github/workflows/install_dependencies_linux

      - name: Install clang
        uses: ./.github/workflows/install_clang_linux

      - name: Build the project
        uses: ./.github/workflows/build_linux_clang

      - name: Run the test suite
        uses: ./.github/workflows/run_test_suite

  build-linux-amd64-gcc:
    name: Build on linux-amd64 with gcc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Porytiles repository
        uses: actions/checkout@v4

      - name: Install Porytiles build dependencies
        uses: ./.github/workflows/install_dependencies_linux

      - name: Install gcc
        uses: ./.github/workflows/install_gcc_linux

      - name: Build the project
        uses: ./.github/workflows/build_linux_gcc

      - name: Run the test suite
        uses: ./.github/workflows/run_test_suite

  build-linux-arm64-clang:
    name: Build on linux-arm64 with clang
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Porytiles repository
        uses: actions/checkout@v4

      - name: Install Porytiles build dependencies
        uses: ./.github/workflows/install_dependencies_linux

      - name: Install clang
        uses: ./.github/workflows/install_clang_linux

      - name: Build the project
        uses: ./.github/workflows/build_linux_clang

      - name: Run the test suite
        uses: ./.github/workflows/run_test_suite

  build-macos-arm64-clang:
    name: Build on macos-arm64 with clang
    runs-on: macos-latest
    steps:
      - name: Checkout Porytiles repository
        uses: actions/checkout@v4

      - name: Install Porytiles build dependencies
        uses: ./.github/workflows/install_dependencies_macos

      - name: Build the project
        uses: ./.github/workflows/build_macos_clang

      - name: Run the test suite
        uses: ./.github/workflows/run_test_suite

#  build-macos-amd64-clang:
#    name: Build on macos-amd64 with clang
#    runs-on: macos-13
#    steps:
#      - name: Checkout Porytiles repository
#        uses: actions/checkout@v4
#
#      - name: Install Porytiles build dependencies
#        uses: ./.github/workflows/install_dependencies_macos
#
#      - name: Build the project
#        uses: ./.github/workflows/build_macos_clang
#
#      - name: Run the test suite
#        uses: ./.github/workflows/run_test_suite