name: Porytiles Develop Branch Build
on:
  push:
    branches: [ "develop" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-linux-amd64-clang:
    uses: ./.github/workflows/linux_amd64_clang.yml
  build-linux-amd64-gcc:
    uses: ./.github/workflows/linux_amd64_gcc.yml
  build-macos-arm64-clang:
    uses: ./.github/workflows/macos_arm64_clang.yml
  build-macos-arm64-gcc:
    uses: ./.github/workflows/macos_arm64_gcc.yml
