name: Porytiles Nightly Release
on:
  #  schedule:
  #    - cron: "00 05 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Block nightly release pipeline if release was already built from this commit
  check-already-built:
    name: Check if we already built a nightly from this commit SHA
    runs-on: 'ubuntu-latest'
    steps:
      - uses: octokit/request-action@v2.x
        id: check_last_run
        with:
          route: GET /repos/${{github.repository}}/actions/workflows/nightly_release.yml/runs?per_page=1&status=completed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo Last nightly build: ${{fromJson(steps.check_last_run.outputs.data).workflow_runs[0].head_sha}}"
    outputs:
      last_sha: ${{fromJson(steps.check_last_run.outputs.data).workflow_runs[0].head_sha}}

  nightly-release-linux-amd64:
    name: Release a linux-amd64 binary based on the develop branch
    runs-on: ubuntu-latest
    needs: [ check-already-built ]
    if: needs.check-already-built.outputs.last_sha != github.sha
    steps:
      - name: Checkout the develop branch
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Install Porytiles build dependencies
        uses: ./.github/workflows/install_dependencies_linux

      - name: Install clang
        uses: ./.github/workflows/install_clang_linux

      - name: Build Porytiles
        uses: ./.github/workflows/build_linux_clang
        with:
          build-version: nightly-${{ github.sha }}

      - name: Run the test suite
        uses: ./.github/workflows/run_test_suite

      - name: Create release package
        uses: ./.github/workflows/create_release_package
        with:
          os-arch: linux-amd64

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly-${{github.sha}}
          files: porytiles-linux-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  nightly-release-linux-arm64:
    name: Release a linux-arm64 binary based on the develop branch
    runs-on: ubuntu-24.04-arm
    needs: [ check-already-built ]
    if: needs.check-already-built.outputs.last_sha != github.sha
    steps:
      - name: Checkout the develop branch
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Install Porytiles build dependencies
        uses: ./.github/workflows/install_dependencies_linux

      - name: Install clang
        uses: ./.github/workflows/install_clang_linux

      - name: Build Porytiles
        uses: ./.github/workflows/build_linux_clang
        with:
          build-version: nightly-${{ github.sha }}

      - name: Run the test suite
        uses: ./.github/workflows/run_test_suite

      - name: Create release package
        uses: ./.github/workflows/create_release_package
        with:
          os-arch: linux-arm64

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly-${{github.sha}}
          files: porytiles-linux-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  nightly-release-macos-amd64:
    name: Release a macos-amd64 binary based on the develop branch
    runs-on: macos-13
    needs: [ check-already-built ]
    if: needs.check-already-built.outputs.last_sha != github.sha
    steps:
      - name: Checkout the develop branch
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Install Porytiles build dependencies
        uses: ./.github/workflows/install_dependencies_macos

      - name: Build Porytiles
        uses: ./.github/workflows/build_macos_clang
        with:
          build-version: nightly-${{ github.sha }}

      - name: Run the test suite
        uses: ./.github/workflows/run_test_suite

      - name: Create release package
        uses: ./.github/workflows/create_release_package
        with:
          os-arch: macos-amd64

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly-${{github.sha}}
          files: porytiles-macos-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  nightly-release-macos-arm64:
    name: Release a macos-arm64 binary based on the develop branch
    runs-on: macos-latest
    needs: [ check-already-built ]
    if: needs.check-already-built.outputs.last_sha != github.sha
    steps:
      - name: Checkout the develop branch
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Install Porytiles build dependencies
        uses: ./.github/workflows/install_dependencies_macos

      - name: Build Porytiles
        uses: ./.github/workflows/build_macos_clang
        with:
          build-version: nightly-${{ github.sha }}

      - name: Run the test suite
        uses: ./.github/workflows/run_test_suite

      - name: Create release package
        uses: ./.github/workflows/create_release_package
        with:
          os-arch: macos-arm64

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly-${{github.sha}}
          files: porytiles-macos-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew-tap:
    name: Update Homebrew tap formula
    runs-on: ubuntu-latest
    needs: [ nightly-release-linux-amd64, nightly-release-linux-arm64, nightly-release-macos-amd64, nightly-release-macos-arm64 ]
    if: needs.check-already-built.outputs.last_sha != github.sha
    steps:
      - name: Checkout Homebrew tap repository
        uses: actions/checkout@v4
        with:
          repository: grunt-lucas/homebrew-porytiles
          token: ${{ secrets.PORYTILES_TAP_REPO_PAT }}

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github'

      - name: Define vars
        id: vars
        run: |
          echo "nightly_tag=nightly-${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "new_version=$(date +'%Y%m%d%H%M%S')-nightly-${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "formula_path=Formula/porytiles.rb" >> $GITHUB_OUTPUT

      - name: Download assets and calculate SHA256 checksums
        id: checksums
        run: |
          URL_BASE="https://github.com/${{ github.repository }}/releases/download/${{ steps.vars.outputs.nightly_tag }}"
          LINUX_AMD64_URL="$URL_BASE/porytiles-linux-amd64.zip"
          LINUX_ARM64_URL="$URL_BASE/porytiles-linux-arm64.zip"
          MACOS_AMD64_URL="$URL_BASE/porytiles-macos-amd64.zip"
          MACOS_ARM64_URL="$URL_BASE/porytiles-macos-arm64.zip"
          
          echo "Downloading $LINUX_AMD64_URL"
          curl -L -o porytiles-linux-amd64.zip $LINUX_AMD64_URL
          LINUX_AMD64_SHA=$(sha256sum porytiles-linux-amd64.zip | awk '{ print $1 }')
          echo "linux_amd64_sha=$LINUX_AMD64_SHA" >> $GITHUB_OUTPUT
          echo "Calculated SHA256 for linux-amd64: $LINUX_AMD64_SHA"
          
          echo "Downloading $LINUX_ARM64_URL"
          curl -L -o porytiles-linux-arm64.zip $LINUX_ARM64_URL
          LINUX_ARM64_SHA=$(sha256sum porytiles-linux-arm64.zip | awk '{ print $1 }')
          echo "linux_arm64_sha=$LINUX_ARM64_SHA" >> $GITHUB_OUTPUT
          echo "Calculated SHA256 for linux-arm64: $LINUX_ARM64_SHA"
          
          echo "Downloading $MACOS_AMD64_URL"
          curl -L -o porytiles-macos-amd64.zip $MACOS_AMD64_URL
          MACOS_AMD64_SHA=$(sha256sum porytiles-macos-amd64.zip | awk '{ print $1 }')
          echo "macos_amd64_sha=$MACOS_AMD64_SHA" >> $GITHUB_OUTPUT
          echo "Calculated SHA256 for macos-amd64: $MACOS_AMD64_SHA"

          echo "Downloading $MACOS_ARM64_URL"
          curl -L -o porytiles-macos-arm64.zip $MACOS_ARM64_URL
          MACOS_ARM64_SHA=$(sha256sum porytiles-macos-arm64.zip | awk '{ print $1 }')
          echo "macos_arm64_sha=$MACOS_ARM64_SHA" >> $GITHUB_OUTPUT
          echo "Calculated SHA256 for macos-arm64: $MACOS_ARM64_SHA"

      - name: Update formula file
        run: |
          FORMULA_PATH="${{ steps.vars.outputs.formula_path }}"
          sed -i "s/^    version \".*\"/    version \"${{ steps.vars.outputs.new_version }}\"/" "$FORMULA_PATH"
          sed -i "s/^    nightly = \".*\"/    nightly = \"${{ steps.vars.outputs.nightly_tag }}\"/" "$FORMULA_PATH"
          sed -i "/if OS.linux? && Hardware::CPU.intel?/,/elsif/ s/^    sha256 \".*\"/    sha256 \"${{ steps.checksums.outputs.linux_amd64_sha }}\"/" "$FORMULA_PATH"
          sed -i "/elsif OS.linux? && Hardware::CPU.arm?/,/elsif/ s/^    sha256 \".*\"/    sha256 \"${{ steps.checksums.outputs.linux_arm64_sha }}\"/" "$FORMULA_PATH"
          sed -i "/elsif OS.mac? && Hardware::CPU.intel?/,/elsif/ s/^    sha256 \".*\"/    sha256 \"${{ steps.checksums.outputs.macos_amd64_sha }}\"/" "$FORMULA_PATH"
          sed -i "/elsif OS.mac? && Hardware::CPU.arm?/,/end/ s/^    sha256 \".*\"/    sha256 \"${{ steps.checksums.outputs.macos_arm64_sha }}\"/" "$FORMULA_PATH"
          echo "Formula file updated:"
          cat "$FORMULA_PATH"

      - name: Commit and push changes
        run: |
          git add "${{ steps.vars.outputs.formula_path }}"
          git commit -m "Update porytiles formula to ${{ steps.vars.outputs.nightly_tag }}"
          git push

  test-linux-amd64-brew-tap:
    name: Test the brew tap on linux-amd64
    runs-on: ubuntu-latest
    needs: [ update-homebrew-tap ]
    if: needs.check-already-built.outputs.last_sha != github.sha
    steps:
      - name: Install Porytiles
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap grunt-lucas/porytiles
          brew update
          brew install porytiles

      - name: Test Porytiles
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          porytiles --version

  test-linux-arm64-brew-tap:
    name: Test the brew tap on linux-arm64
    runs-on: ubuntu-24.04-arm
    needs: [ update-homebrew-tap ]
    if: needs.check-already-built.outputs.last_sha != github.sha
    steps:
      - name: Install Porytiles
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap grunt-lucas/porytiles
          brew update
          brew install porytiles

      - name: Test Porytiles
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          porytiles --version

  test-macos-amd64-brew-tap:
    name: Test the brew tap on macos-amd64
    runs-on: macos-13
    needs: [ update-homebrew-tap ]
    if: needs.check-already-built.outputs.last_sha != github.sha
    steps:
      - name: Install Porytiles
        run: |
          brew tap grunt-lucas/porytiles
          brew update
          brew install porytiles

      - name: Test Porytiles
        run: |
          porytiles --version

  test-macos-arm64-brew-tap:
    name: Test the brew tap on macos-arm64
    runs-on: macos-latest
    needs: [ update-homebrew-tap ]
    if: needs.check-already-built.outputs.last_sha != github.sha
    steps:
      - name: Install Porytiles
        run: |
          brew tap grunt-lucas/porytiles
          brew update
          brew install porytiles

      - name: Test Porytiles
        run: |
          porytiles --version
