name: Porytiles PR Build
on:
  pull_request:
    branches: [ "develop" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pr-build-linux-amd64-clang-llvm:
    name: PR build on ubuntu-latest-amd64 with Clang+LLVM 16
    runs-on: ubuntu-latest
    steps:
      - name: Install Clang+LLVM 16 and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zlib1g-dev
          sudo apt-get install libpng-dev
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16 all
          clang++-16 --version
          clang++-16 -v

      - name: Checkout porytiles
        uses: actions/checkout@v3

      - name: Build debug and release executables
        run: |
          CXX=clang++-16 make all

      - name: Run tests on debug and release
        run: |
          CXX=clang++-16 make check

  pr-build-linux-amd64-gcc:
    name: PR build on ubuntu-latest-amd64 with GCC 13
    runs-on: ubuntu-latest
    steps:
      - name: Install GCC 13 and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install zlib1g-dev
          sudo apt-get install libpng-dev
          sudo apt-get install g++-13
          g++-13 --version
          g++-13 -v

      - name: Checkout porytiles
        uses: actions/checkout@v3

      - name: Build debug and release executables
        run: |
          CXX=g++-13 make all

      - name: Run tests on debug and release
        run: |
          CXX=g++-13 make check

  pr-build-macos-amd64-clang-llvm:
    name: PR build on macos-latest-amd64 with Clang+LLVM 16
    runs-on: macos-latest
    steps:
      - name: Install Clang+LLVM 16 and dependencies
        run: |
          brew update
          brew install zlib || true
          brew install libpng || true
          brew install llvm@16 || true
          /opt/homebrew/opt/llvm@16/bin/clang++ --version
          /opt/homebrew/opt/llvm@16/bin/clang++ -v

      - name: Checkout porytiles
        uses: actions/checkout@v3

      - name: Build debug and release executables
        run: |
          LDFLAGS='-L/opt/homebrew/opt/llvm@16/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm@16/lib/c++' CXXFLAGS='-I/opt/homebrew/opt/llvm@16/include/c++/v1' CXX=/opt/homebrew/opt/llvm@16/bin/clang++ make all

      - name: Run tests on debug and release
        run: |
          LDFLAGS='-L/opt/homebrew/opt/llvm@16/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm@16/lib/c++' CXXFLAGS='-I/opt/homebrew/opt/llvm@16/include/c++/v1' CXX=/opt/homebrew/opt/llvm@16/bin/clang++ make check

  pr-build-macos-aarch4-clang-llvm:
    name: PR build on macos-14-aarch64 with Clang+LLVM 16
    runs-on: macos-14
    steps:
      - name: Install Clang+LLVM 16 and dependencies
        run: |
          brew update
          brew install zlib || true
          brew install libpng || true
          brew install llvm@16 || true
          /opt/homebrew/opt/llvm@16/bin/clang++ --version
          /opt/homebrew/opt/llvm@16/bin/clang++ -v

      - name: Checkout porytiles
        uses: actions/checkout@v3

      - name: Build debug and release executables
        run: |
          LDFLAGS='-L/opt/homebrew/opt/llvm@16/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm@16/lib/c++' CXXFLAGS='-I/opt/homebrew/opt/llvm@16/include/c++/v1' CXX=/opt/homebrew/opt/llvm@16/bin/clang++ make all

      - name: Run tests on debug and release
        run: |
          LDFLAGS='-L/opt/homebrew/opt/llvm@16/lib/c++ -Wl,-rpath,/opt/homebrew/opt/llvm@16/lib/c++' CXXFLAGS='-I/opt/homebrew/opt/llvm@16/include/c++/v1' CXX=/opt/homebrew/opt/llvm@16/bin/clang++ make check
