name: Porytiles PR Build
on:
  pull_request:
    branches: [ "develop" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# PR builds make sure all platforms build with clang. Nightly releases use
# clang to build so we don't want to let in a PR that's going to fail one
# of the nightly pipelines. Since we do still care about gcc compatibility,
# we'll build with gcc on the develop branch build. Breaking gcc changes
# shouldn't block a PR, but we should know about them so they can be
# addressed at a later time.
jobs:
  build-0x-linux-amd64-clang:
    uses: ./.github/workflows/0x_linux_amd64_clang.yml
  build-0x-linux-arm64-clang:
    uses: ./.github/workflows/0x_linux_arm64_clang.yml
  build-0x-macos-amd64-clang:
    uses: ./.github/workflows/0x_macos_amd64_clang.yml
  build-0x-macos-arm64-clang:
    uses: ./.github/workflows/0x_macos_arm64_clang.yml
